/* PHASE 9 · ADMIN CONTROL PLANE, AI ROUTER, BACKGROUND JOBS, SELF-HEAL — in-memory database, fake model where needed. */
const { spawn } = require('child_process'); const fs = require('fs'); const path = require('path'); const PORT = 4484; const BASE = 'http://127.0.0.1:' + PORT;
const BAD = path.join(__dirname, 'fixtures_bad_ai.txt'); fs.writeFileSync(BAD, 'Sure! Here is the JSON you asked for: { "full_name": "Ghost", "phone": "0300", oops not valid');
const baseEnv = { NODE_ENV: 'test', FF_MEMDB: '1', FF_QUEUE: 'off', PORT: String(PORT), SUPABASE_URL: 'https://memdb.local', SUPABASE_ANON_KEY: 'x', SUPABASE_SERVICE_ROLE_KEY: 'x', ANTHROPIC_API_KEY: 'x', GEMINI_API_KEY: 'x', FF_DATA_KEY: '0000000000000000000000000000000000000000000000000000000000000001' };
const ID = n => 'd9d9d9d9-0000-4000-8000-0000000000' + n; const SUPER = ID('01'), ADMIN = ID('02'), STAFF = ID('03'), USER = ID('04');
const tok = u => 'test:' + u + ':' + u.slice(-2) + '@test.local';
async function boot(extra) { const env = Object.assign({}, process.env, baseEnv, extra || {}); const child = spawn(process.execPath, ['server.js'], { env, stdio: ['ignore', 'pipe', 'pipe'] }); let log = ''; child.stdout.on('data', d => { log += d; }); child.stderr.on('data', d => { log += d; }); for (let i = 0; i < 60; i++) { await new Promise(r => setTimeout(r, 250)); try { const r = await fetch(BASE + '/api/health'); if (r.ok) return { child, log: () => log }; } catch (e) {} } console.log('boot failed', log.slice(-300)); process.exit(1); }
async function req(p, { method = 'GET', body, user, headers, raw } = {}) { const h = Object.assign(raw ? {} : { 'content-type': 'application/json' }, headers || {}); if (user) h.authorization = 'Bearer ' + tok(user); const r = await fetch(BASE + p, { method, headers: h, body: raw ? raw : (body ? JSON.stringify(body) : undefined) }); let j = null; try { j = await r.json(); } catch (e) {} return { status: r.status, body: j }; }
const rows = async t => (await req('/__memdb/rows?table=' + t)).body.rows;
const seedRows = { profiles: [{ id: SUPER, email: '01@test.local', role: 'super_admin', full_name: 'Super' }, { id: ADMIN, email: '02@test.local', role: 'admin', full_name: 'Admin' }, { id: STAFF, email: '03@test.local', role: 'staff', full_name: 'Staff' }, { id: USER, email: '04@test.local', role: 'user', full_name: 'User' }] };
(async () => {
  let pass = 0, fail = 0; const ok = (n, c, x) => { if (c) { pass++; console.log('PASS  ' + n); } else { fail++; console.log('FAIL  ' + n + (x ? '  → ' + JSON.stringify(x).slice(0, 240) : '')); } };
  let srv = await boot(); global.__srv = srv; await req('/__memdb/seed', { method: 'POST', body: { reset: true, rows: seedRows } });
  // ---- admin tabs: every read route answers 200 for an admin, 403 for a user, 401 unauthenticated ----
  const tabs = ['overview', 'users', 'applications', 'payments', 'orgs', 'partners', 'prospects', 'brief', 'economics', 'settings', 'selfheal', 'simulate/latest', 'security/posture', 'audit', 'support', 'ai-costs', 'queue', 'cockpit', 'alerts', 'documents', 'countries', 'visa/rules', 'metrics', 'usage', 'sources'];
  let okTabs = 0, badTabs = []; for (const t of tabs) { const r = await req('/api/admin/' + t, { user: SUPER }); if (r.status === 200) okTabs++; else badTabs.push([t, r.status]); } ok('every admin tab route answers 200 for a super admin (' + okTabs + '/' + tabs.length + ')', badTabs.length === 0, badTabs);
  var r = await req('/api/admin/orgs', { user: ADMIN }); ok('organisation controls are super-admin only (admin 403)', r.status === 403, r.status);
  let denied = 0; for (const t of tabs) { const r = await req('/api/admin/' + t, { user: USER }); if (r.status === 403) denied++; } ok('every admin tab route is 403 for an applicant', denied === tabs.length, denied);
  let unauth = 0; for (const t of tabs.slice(0, 6)) { const r = await req('/api/admin/' + t); if (r.status === 401) unauth++; } ok('admin routes are 401 unauthenticated', unauth === 6, unauth);
  const w1 = await req('/api/admin/settings', { method: 'PUT', user: STAFF, body: { packages: {} } }); const w2 = await req('/api/admin/security/rotate-key', { method: 'POST', user: STAFF, body: { old_key: 'x', confirm: 'ROTATE' } }); ok('staff can read but not write settings or rotate keys (403/403)', w1.status === 403 && w2.status === 403, [w1.status, w2.status]);
  // ---- dangerous actions: permission + typed confirmation ----
  r = await req('/api/admin/simulate/purge', { method: 'POST', user: STAFF, body: { confirm: 'PURGE' } }); ok('purge SIM data: staff denied (403)', r.status === 403, r.status);
  r = await req('/api/admin/simulate/purge', { method: 'POST', user: ADMIN, body: {} }); ok('purge without the typed confirmation refused (400 CONFIRM_REQUIRED)', r.status === 400 && r.body.code === 'CONFIRM_REQUIRED', r.body);
  r = await req('/api/admin/simulate/purge', { method: 'POST', user: ADMIN, body: { confirm: 'PURGE' } }); ok('purge with confirmation runs and is audited', r.status === 200 && (await rows('audit_log')).some(a => a.event === 'SIM_PURGE'), r.body);
  r = await req('/api/admin/security/rotate-key', { method: 'POST', user: ADMIN, body: { old_key: 'x'.repeat(64) } }); ok('key rotation without ROTATE confirmation refused', r.status === 400 && r.body.code === 'CONFIRM_REQUIRED', r.body);
  r = await req('/api/admin/users/' + USER + '/role', { method: 'POST', user: STAFF, body: { role: 'admin', confirm: 'GRANT' } }); ok('staff cannot grant admin roles (403)', r.status === 403, r.status);
  r = await req('/api/admin/users/' + USER + '/role', { method: 'POST', user: SUPER, body: { role: 'admin' } }); ok('super admin must type GRANT to elevate (400)', r.status === 400 && r.body.code === 'CONFIRM_REQUIRED', r.body);
  r = await req('/api/admin/users/' + USER + '/role', { method: 'POST', user: SUPER, body: { role: 'admin', confirm: 'GRANT' } }); ok('super admin elevates with confirmation; role cache dropped (user now sees admin routes)', r.status === 200 && (await req('/api/admin/overview', { user: USER })).status === 200, r.body);
  r = await req('/api/admin/users/' + USER + '/role', { method: 'POST', user: SUPER, body: { role: 'user' } }); ok('demotion needs no typed confirmation', r.status === 200, r.body);
  r = await req('/api/payments/x/refund', { method: 'POST', user: STAFF }); ok('refund needs payments.write (staff 403 or 404, never 200)', r.status !== 200, r.status);
  // ---- background jobs: idempotency, retry, dead, timeout, restart recovery ----
  r = await req('/__memdb/enqueue', { method: 'POST', body: { kind: 'vault_read', payload: { docId: 'doc-1', userId: USER }, opts: { maxAttempts: 2, timeoutMs: 300 } } }); const j1 = r.body && r.body.id;
  r = await req('/__memdb/enqueue', { method: 'POST', body: { kind: 'vault_read', payload: { docId: 'doc-1', userId: USER }, opts: { maxAttempts: 2 } } }); ok('same job enqueued twice → one row (idempotency key)', r.body && r.body.id === j1 && (await rows('job_queue')).length === 1, [j1, r.body]);
  r = await req('/__memdb/enqueue', { method: 'POST', body: { kind: 'vault_read', payload: { docId: 'doc-2', userId: USER } } }); ok('a different document → a second job', (await rows('job_queue')).length === 2);
  await req('/__memdb/runone', { method: 'POST' }); await req('/__memdb/runone', { method: 'POST' }); let jobs = await rows('job_queue'); const jj = jobs.find(x => x.id === j1); ok('a failing handler (no document) → job retried with backoff, attempts 1, error kept', jj && jj.attempts === 1 && jj.status === 'queued' && jj.last_error && jj.run_after > new Date().toISOString(), jj);
  await req('/__memdb/patch', { method: 'POST', body: { table: 'job_queue', id: j1, patch: { run_after: new Date(Date.now() - 1000).toISOString() } } });
  await req('/__memdb/runone', { method: 'POST' }); await req('/__memdb/runone', { method: 'POST' }); jobs = await rows('job_queue'); ok('after max attempts the job is DEAD, not retried for ever', jobs.find(x => x.id === j1).status === 'dead', jobs.find(x => x.id === j1));
  r = await req('/__memdb/enqueue', { method: 'POST', body: { kind: '__sleep', payload: { ms: 1500, key: 's1' }, opts: { maxAttempts: 1, timeoutMs: 200 } } }); r = await req('/__memdb/runone', { method: 'POST' }); jobs = await rows('job_queue'); const sj = jobs.find(x => x.kind === '__sleep'); ok('a hanging job hits its timeout → failed/dead with the reason, worker freed', sj && sj.status === 'dead' && /timeout/.test(sj.last_error || ''), sj);
  await req('/__memdb/seed', { method: 'POST', body: { rows: { job_queue: [{ id: 'd9d9d9d9-0000-4000-8000-0000000000j1', kind: 'vault_read', payload: {}, status: 'running', locked_at: new Date(Date.now() - 30 * 60000).toISOString(), locked_by: 'dead-worker', attempts: 1, max_attempts: 3, run_after: new Date().toISOString() }] } } });
  r = await req('/__memdb/reap', { method: 'POST' }); jobs = await rows('job_queue'); ok('restart recovery: a job left running by a dead worker for 30 min is re-queued', jobs.find(x => x.id === 'd9d9d9d9-0000-4000-8000-0000000000j1').status === 'queued', jobs.find(x => x.id === 'd9d9d9d9-0000-4000-8000-0000000000j1'));
  r = await req('/api/admin/queue', { user: ADMIN }); ok('queue view shows dead jobs to a human', r.status === 200 && /dead/.test(JSON.stringify(r.body)), r.body && Object.keys(r.body));
  r = await req('/api/admin/selfheal', { method: 'POST', user: STAFF, body: { action: 'requeue_dead' } }); ok('self-heal actions are not available to plain staff (403)', r.status === 403, r.status);
  srv.child.kill(); await new Promise(x => setTimeout(x, 400));
  // ---- AI router: malformed output and total provider failure never corrupt state ----
  srv = await boot({ FF_FAKE_AI_FILE: BAD }); await req('/__memdb/seed', { method: 'POST', body: { reset: true, rows: seedRows } });
  await req('/api/me', { user: USER }); await req('/api/me', { method: 'PUT', user: USER, body: { full_name: 'Real Name' } });
  const b = '----ffa' + Date.now(); const body = Buffer.concat([Buffer.from('--' + b + '\r\nContent-Disposition: form-data; name="files"; filename="cv.txt"\r\nContent-Type: text/plain\r\n\r\nReal Name\nPharmacist\n'), Buffer.from('\r\n--' + b + '--\r\n')]);
  r = await req('/api/documents', { method: 'POST', raw: body, headers: { 'content-type': 'multipart/form-data; boundary=' + b, authorization: 'Bearer ' + tok(USER) } });
  r = await req('/__memdb/extract', { method: 'POST', user: USER }); const me1 = (await req('/api/me', { user: USER })).body.me; ok('malformed model output: extraction completes without throwing, profile untouched (no "Ghost")', r.status === 200 && me1.full_name === 'Real Name' && me1.phone !== '0300', [r.status, me1.full_name, me1.phone]);
  srv.child.kill(); await new Promise(x => setTimeout(x, 400));
  srv = await boot({ FF_FAKE_AI_FILE: '/nonexistent/none.txt' }); await req('/__memdb/seed', { method: 'POST', body: { reset: true, rows: seedRows } });
  await req('/api/me', { user: USER }); r = await req('/api/documents', { method: 'POST', raw: body, headers: { 'content-type': 'multipart/form-data; boundary=' + b, authorization: 'Bearer ' + tok(USER) } });
  r = await req('/__memdb/extract', { method: 'POST', user: USER }); const me2 = (await req('/api/me', { user: USER })).body.me; ok('every provider down: extraction fails cleanly (no 500 to the user path), profile unchanged', (r.status === 200 || r.status === 400) && !me2.headline && !me2.phone, [r.status, r.body && r.body.error && String(r.body.error).slice(0, 60)]);
  r = await req('/api/ask', { method: 'POST', user: USER, body: { question: 'Which visa?' } }); ok('assistant with no model: no 500; falls back to a ticket or a plain answer', r.status === 200 || r.status === 400, r.status);
  const D = require('../lib/docs.js'); { const m = D.minimisePII('CNIC 35202-1234567-1 card 4111 1111 1111 1111 IBAN PK36SCBL0000001123456702 +923001234567'); ok('DISC-005: national IDs, card numbers and IBANs are masked in text sent for extraction; phone kept', /\[national-id\]/.test(m) && /\[number\]/.test(m) && /IBAN \[masked\]/.test(m) && /\+923001234567/.test(m) && !/35202-1234567-1|4111|PK36SCBL/.test(m), m); }
  srv.child.kill(); console.log('\nadmin: ' + pass + ' pass / ' + fail + ' fail'); process.exit(fail ? 1 : 0);
})();
