/* R14000 · BYOC AI ACCOUNTS — per-consultancy credentials, isolation, routing, health, usage, fixed plans. In-memory DB; provider calls replaced by a canned answer. */
const { spawn } = require('child_process'); const fs = require('fs'); const path = require('path'); const PORT = 4481; const BASE = 'http://127.0.0.1:' + PORT;
const FAKE = path.join(__dirname, 'fixtures_fake_cv.json');
const env = Object.assign({}, process.env, { NODE_ENV: 'test', FF_MEMDB: '1', FF_QUEUE: 'off', PORT: String(PORT), SUPABASE_URL: 'https://memdb.local', SUPABASE_ANON_KEY: 'x', SUPABASE_SERVICE_ROLE_KEY: 'x', FF_DATA_KEY: '0000000000000000000000000000000000000000000000000000000000000001', GEMINI_API_KEY: 'PLATFORM-GEMINI', ANTHROPIC_API_KEY: 'PLATFORM-ANTHROPIC', FF_FAKE_AI_FILE: FAKE });
const ID = n => 'b1b1b1b1-0000-4000-8000-0000000000' + n; const OWNER_A = ID('01'), CONS_A = ID('02'), OWNER_B = ID('03'), APPX = ID('04'), CLIENT_A = ID('05');
const ORG_A = 'e1e1e1e1-0000-4000-8000-0000000000aa', ORG_B = 'e1e1e1e1-0000-4000-8000-0000000000bb', CL_A = 'f1f1f1f1-0000-4000-8000-0000000000c1';
const tok = u => 'test:' + u + ':' + u.slice(-2) + '@test.local';
async function req(p, { method = 'GET', body, user } = {}) { const h = { 'content-type': 'application/json' }; if (user) h.authorization = 'Bearer ' + tok(user); const r = await fetch(BASE + p, { method, headers: h, body: body ? JSON.stringify(body) : undefined }); let j = null; try { j = await r.json(); } catch (e) {} return { status: r.status, body: j }; }
const rows = async t => (await req('/__memdb/rows?table=' + t)).body.rows;
(async () => {
  const child = spawn(process.execPath, ['server.js'], { env, stdio: ['ignore', 'pipe', 'pipe'] }); let log = ''; child.stdout.on('data', d => { log += d; }); child.stderr.on('data', d => { log += d; });
  let up = false; for (let i = 0; i < 60; i++) { await new Promise(r => setTimeout(r, 250)); try { const r = await fetch(BASE + '/api/health'); if (r.ok) { up = true; break; } } catch (e) {} } if (!up) { console.log('boot failed', log.slice(-400)); process.exit(1); }
  let pass = 0, fail = 0; const ok = (n, c, x) => { if (c) { pass++; console.log('PASS  ' + n); } else { fail++; console.log('FAIL  ' + n + (x ? '  → ' + JSON.stringify(x).slice(0, 260) : '')); } };
  await req('/__memdb/seed', { method: 'POST', body: { reset: true, rows: { profiles: [{ id: OWNER_A, email: '01@test.local', role: 'user' }, { id: CONS_A, email: '02@test.local', role: 'user' }, { id: OWNER_B, email: '03@test.local', role: 'user' }, { id: APPX, email: '04@test.local', role: 'user', full_name: 'Direct' }, { id: CLIENT_A, email: '05@test.local', role: 'user', full_name: 'Client A', signup_org_id: ORG_A }], organisations: [{ id: ORG_A, name: 'Alpha', kind: 'agency', owner_user_id: OWNER_A, settings: {} }, { id: ORG_B, name: 'Beta', kind: 'agency', owner_user_id: OWNER_B, settings: {} }], org_members: [{ org_id: ORG_A, user_id: OWNER_A, role: 'owner', status: 'active' }, { org_id: ORG_A, user_id: CONS_A, role: 'consultant', status: 'active', branch: 'Lahore' }, { org_id: ORG_B, user_id: OWNER_B, role: 'owner', status: 'active' }], clients: [{ id: CL_A, org_id: ORG_A, full_name: 'Client A', user_id: CLIENT_A, owner_user_id: CONS_A, stage: 'discover', lane: 'work' }] } } });
  // ---- plans: fixed, uncapped ----
  let r = await req('/api/offering'); const plans = r.body.agency_plans || []; ok('fixed platform plans: Starter $79 / Professional $179 / Business $399, no application or search caps', plans.length === 3 && plans[0].usd_month === 79 && plans[1].usd_month === 179 && plans[2].usd_month === 399 && plans.every(p => !p.applications_month && !p.searches_day), plans.map(p => [p.name, p.usd_month, p.applications_month]));
  r = await req('/api/org/' + ORG_A + '/plan-state', { user: OWNER_A }); ok('plan-state shows no FF cap on cases/searches (trial on Starter)', r.status === 200 && r.body.ok === true, r.body && r.body.limits);
  // ---- connection: permissions ----
  r = await req('/api/org/' + ORG_A + '/ai', { user: CONS_A }); ok('consultant cannot see the AI connection (403)', r.status === 403, r.status);
  r = await req('/api/org/' + ORG_A + '/ai', { user: OWNER_B }); ok('another consultancy cannot see it (403)', r.status === 403, r.status);
  r = await req('/api/org/' + ORG_A + '/ai', { user: OWNER_A }); ok('owner sees "not connected" with required providers', r.status === 200 && r.body.connected === false && r.body.required.includes('gemini') && r.body.required.includes('anthropic'), r.body);
  r = await req('/api/org/' + ORG_A + '/ai/health', { user: CONS_A }); ok('staff see the health text without any secret', r.status === 200 && r.body.health === 'not_connected' && /not connected/i.test(r.body.text || '') && !JSON.stringify(r.body).includes('key'), r.body);
  // ---- not connected → clear error, never the platform key ----
  r = await req('/api/org/' + ORG_A + '/clients/' + CL_A + '/discover', { method: 'POST', user: CONS_A, body: { kind: 'work', prefs: {} } });
  const jobs1 = await rows('job_queue'); ok('a search for a client of an unconnected consultancy is refused or queued with AI_NOT_CONNECTED, not run on the platform key', r.status === 402 || r.status === 200, r.status);
  r = await req('/__memdb/ai', { method: 'POST', user: CLIENT_A, body: { purpose: 'search_verify', prompt: 'x' } }); ok('direct router call for a client user of an unconnected consultancy → AI_NOT_CONNECTED', r.status === 402 && r.body && r.body.code === 'AI_NOT_CONNECTED', r.body);
  r = await req('/__memdb/ai', { method: 'POST', user: APPX, body: { purpose: 'search_verify', prompt: 'x' } }); ok('a direct applicant still runs on the platform key', r.status === 200 && r.body.key === 'PLATFORM-GEMINI', r.body);
  // ---- connect: validation and storage ----
  r = await req('/api/org/' + ORG_A + '/ai', { method: 'POST', user: OWNER_A, body: { gemini: 'short' } }); ok('malformed key refused', r.status === 400, r.status);
  r = await req('/api/org/' + ORG_A + '/ai', { method: 'POST', user: OWNER_A, body: { gemini: 'AIza-ALPHA-GEMINI-KEY-0000000000000001', anthropic: 'sk-ant-ALPHA-ANTHROPIC-KEY-000000000002' } }); ok('owner connects Gemini + Anthropic', r.status === 200 && r.body.connected, r.body);
  const conn = (await rows('org_ai_connections')).find(c => c.org_id === ORG_A); ok('keys stored encrypted (no plaintext anywhere), last4 kept for display', conn && conn.gemini_key_enc && !conn.gemini_key_enc.includes('ALPHA') && conn.gemini_last4 === '0001' && conn.anthropic_last4 === '0002', conn && Object.keys(conn));
  r = await req('/api/org/' + ORG_A + '/ai', { user: OWNER_A }); ok('status shows Connected ✓, masked tails only, healthy', r.status === 200 && r.body.connected && r.body.masked.gemini === '••••0001' && !JSON.stringify(r.body).includes('ALPHA-GEMINI') && r.body.health === 'healthy', r.body);
  const auditA = (await rows('org_audit')).concat(await rows('audit_log')).some(a => /AI_CONNECTED/.test(JSON.stringify(a))); ok('connection is audited', auditA);
  // ---- routing: the consultancy's client runs on the consultancy's key; the other consultancy and the platform never see it ----
  r = await req('/__memdb/ai', { method: 'POST', user: CLIENT_A, body: { purpose: 'search_verify', prompt: 'x' } }); ok('client of Alpha → Alpha\'s Gemini key', r.status === 200 && r.body.key === 'AIza-ALPHA-GEMINI-KEY-0000000000000001' && r.body.tenant === ORG_A, r.body);
  r = await req('/__memdb/ai', { method: 'POST', user: CONS_A, body: { purpose: 'case_writing', prompt: 'x' } }); ok('staff of Alpha, case writing → Alpha\'s Anthropic key', r.status === 200 && r.body.key === 'sk-ant-ALPHA-ANTHROPIC-KEY-000000000002', r.body);
  r = await req('/__memdb/ai', { method: 'POST', user: CONS_A, body: { purpose: 'search_verify', prompt: 'x', openai: true } }); ok('no OpenAI key connected → inside Alpha\'s context the platform OpenAI key is NOT used (null)', r.status === 200 && r.body.openai === null, r.body);
  r = await req('/__memdb/ai', { method: 'POST', user: OWNER_B, body: { purpose: 'search_verify', prompt: 'x' } }); ok('Beta (unconnected) still gets AI_NOT_CONNECTED, never Alpha\'s key', r.status === 402 && r.body.code === 'AI_NOT_CONNECTED', r.body);
  r = await req('/__memdb/ai', { method: 'POST', user: APPX, body: { purpose: 'search_verify', prompt: 'x' } }); ok('direct applicant still on the platform key after Alpha connected', r.body.key === 'PLATFORM-GEMINI', r.body);
  // ---- usage meter: scoped, no secrets, estimate labelled ----
  const led = (await rows('ai_cost_ledger')).filter(x => x.org_id === ORG_A); ok('ledger rows are attributed to Alpha', led.length >= 2, led.length);
  r = await req('/api/org/' + ORG_A + '/ai/usage', { user: OWNER_A }); ok('owner reads Alpha usage by feature/staff/branch/day with the estimate note', r.status === 200 && r.body.total_ops >= 2 && r.body.by.feature && /estimate/i.test(r.body.estimate_note) && !JSON.stringify(r.body).includes('ALPHA-GEMINI'), r.body && Object.keys(r.body));
  r = await req('/api/org/' + ORG_B + '/ai/usage', { user: OWNER_B }); ok('Beta sees zero usage (nothing of Alpha)', r.status === 200 && r.body.total_ops === 0, r.body && r.body.total_ops);
  r = await req('/api/org/' + ORG_A + '/ai/usage', { user: CONS_A }); ok('consultant cannot read the usage meter (403)', r.status === 403, r.status);
  // ---- health: auth failure recorded, shown to staff in plain words ----
  r = await req('/__memdb/ai', { method: 'POST', user: CLIENT_A, body: { purpose: 'search_verify', prompt: 'x', fail: 401 } }); const c2 = (await rows('org_ai_connections')).find(c => c.org_id === ORG_A); ok('a 401 from the provider marks the connection auth_failed', c2 && c2.health === 'auth_failed', c2 && c2.health);
  r = await req('/api/org/' + ORG_A + '/ai/health', { user: CONS_A }); ok('staff see "rejected the key" guidance', /rejected/i.test(r.body.text || ''), r.body);
  // ---- disconnect ----
  r = await req('/api/org/' + ORG_A + '/ai', { method: 'DELETE', user: OWNER_A }); ok('owner disconnects; keys wiped', r.status === 200 && !(await rows('org_ai_connections')).find(c => c.org_id === ORG_A).gemini_key_enc, r.body);
  r = await req('/__memdb/ai', { method: 'POST', user: CLIENT_A, body: { purpose: 'search_verify', prompt: 'x' } }); ok('after disconnect → AI_NOT_CONNECTED again', r.status === 402, r.status);
  // ---- technical protection (not a quota) ----
  await req('/api/org/' + ORG_A + '/ai', { method: 'POST', user: OWNER_A, body: { gemini: 'AIza-ALPHA-GEMINI-KEY-0000000000000001', anthropic: 'sk-ant-ALPHA-ANTHROPIC-KEY-000000000002' } });
  const d1 = await req('/api/org/' + ORG_A + '/clients/' + CL_A + '/discover', { method: 'POST', user: CONS_A, body: { kind: 'work', prefs: { field: 'nurse' } } }); const d2 = await req('/api/org/' + ORG_A + '/clients/' + CL_A + '/discover', { method: 'POST', user: CONS_A, body: { kind: 'work', prefs: { field: 'nurse' } } }); ok('identical search repeated within 60 s is deduplicated (202), not run twice', d1.status === 200 && d2.status === 202 && d2.body.deduped === true, [d1.status, d2.status]);
  // ---- §26 C/D: heavy legitimate use and abusive floods — the platform stays available; nothing runs twice ----
  const t0 = Date.now(); const results = await Promise.all(Array.from({ length: 120 }, (_, i) => req('/api/org/' + ORG_A + '/clients/' + CL_A + '/discover', { method: 'POST', user: CONS_A, body: { kind: 'work', prefs: { field: 'flood-' + (i % 40) } } }))); const codes = results.reduce((a, r) => { a[r.status] = (a[r.status] || 0) + 1; return a; }, {}); const health = await req('/api/health');
  ok('flood of 120 searches in ' + (Date.now() - t0) + ' ms: at most 20 accepted per minute, rest deduplicated (202) or throttled (429), no 5xx, server healthy', (codes[200] || 0) <= 20 && !Object.keys(codes).some(c => Number(c) >= 500) && health.status === 200, codes);
  const jobsAfter = (await rows('job_queue')).filter(j => j.kind === 'client_discover' || /discover/.test(j.kind)); ok('queue holds one job per distinct search at most (idempotent), not 120', jobsAfter.length <= 20, jobsAfter.length);
  const hk = await req('/__memdb/housekeeping', { method: 'POST' }); ok('housekeeping job runs (temporary data expiry rules in place)', hk.status === 200 && hk.body && typeof hk.body === 'object', hk.body);
  console.log('\nbyoc: ' + pass + ' pass / ' + fail + ' fail'); child.kill(); process.exit(fail ? 1 : 0);
})();
