/* PHASE 7 · PAYMENTS, PACKAGES, CREDITS, ENTITLEMENT — MOCKED gateways on the in-memory database (no live/sandbox credentials here).
   Proves: checkout creates a pending row with intent; webhook signature enforced; duplicate/delayed webhooks are idempotent; settlement
   writes one ledger row and one case (DISC-003); refund once; add-ons once; consultancy trial/plan-state/invoice; no unauthorised credits. */
const { spawn } = require('child_process'); const crypto = require('crypto'); const PORT = 4498; const BASE = 'http://127.0.0.1:' + PORT;
const SECRET = 'lemon-test-secret';
const env = Object.assign({}, process.env, { NODE_ENV: 'test', FF_MEMDB: '1', FF_QUEUE: 'off', PORT: String(PORT), SUPABASE_URL: 'https://memdb.local', SUPABASE_ANON_KEY: 'x', SUPABASE_SERVICE_ROLE_KEY: 'x', ANTHROPIC_API_KEY: 'x', GEMINI_API_KEY: 'x', FF_DATA_KEY: '0000000000000000000000000000000000000000000000000000000000000001', LEMON_WEBHOOK_SECRET: SECRET });
const U = 'a8a8a8a8-0000-4000-8000-0000000000e1', STAFF = 'a8a8a8a8-0000-4000-8000-0000000000a1', OWNER = 'a8a8a8a8-0000-4000-8000-0000000000b1'; const tok = u => 'test:' + u + ':' + u.slice(-2) + '@test.local';
const OPP = 'f8f8f8f8-0000-4000-8000-000000000001', ORG = 'e8e8e8e8-0000-4000-8000-00000000000a';
async function req(p, { method = 'GET', body, user, headers, raw } = {}) { const h = Object.assign(raw ? {} : { 'content-type': 'application/json' }, headers || {}); if (user) h.authorization = 'Bearer ' + tok(user); const r = await fetch(BASE + p, { method, headers: h, body: raw ? raw : (body ? JSON.stringify(body) : undefined) }); let j = null; try { j = await r.json(); } catch (e) {} let t = null; if (!j) { try { t = await r.text(); } catch (e) {} } return { status: r.status, body: j, text: t }; }
const rows = async t => (await req('/__memdb/rows?table=' + t)).body.rows;
(async () => {
  const child = spawn(process.execPath, ['server.js'], { env, stdio: ['ignore', 'pipe', 'pipe'] }); let log = ''; child.stdout.on('data', d => { log += d; }); child.stderr.on('data', d => { log += d; });
  for (let i = 0; i < 40; i++) { await new Promise(r => setTimeout(r, 250)); try { const r = await fetch(BASE + '/api/health'); if (r.ok) break; } catch (e) {} }
  let pass = 0, fail = 0; const ok = (n, c, x) => { if (c) { pass++; console.log('PASS  ' + n); } else { fail++; console.log('FAIL  ' + n + (x ? '  → ' + JSON.stringify(x).slice(0, 240) : '')); } };
  await req('/__memdb/seed', { method: 'POST', body: { reset: true, rows: { profiles: [{ id: U, email: 'e1@test.local', role: 'user', full_name: 'Pay Test', origin_country: 'PK' }, { id: STAFF, email: 'a1@test.local', role: 'admin', full_name: 'Staff' }, { id: OWNER, email: 'b1@test.local', role: 'user', full_name: 'Owner' }], opportunities: [{ id: OPP, title: 'Pharmacist', institution: 'Alpha', country_code: 'GB', kind: 'work', status: 'verified', verified_at: new Date().toISOString(), url: 'https://alpha.invalid/j' }], organisations: [{ id: ORG, name: 'Alpha Consultants', kind: 'agency', owner_user_id: OWNER, settings: {} }], org_members: [{ org_id: ORG, user_id: OWNER, role: 'owner', status: 'active' }] } } });
  // 1-3 packages and local pricing
  let r = await req('/api/offering?cc=PK'); ok('1-3 packages priced with local currency in brackets (PK)', r.status === 200 && (r.body.applicant_packages || []).length >= 1 && /PKR|Rs/.test(JSON.stringify(r.body.applicant_packages)), r.body && r.body.applicant_packages);
  // 4-5 checkout: with no gateway configured the checkout refuses honestly (no dangling row); the pending row is what a gateway checkout creates → seeded here as the gateway would
  r = await req('/api/pay/checkout', { method: 'POST', user: U, body: { credits: 2, opportunity_id: OPP } }); ok('4 checkout without a gateway refuses with a clear message and creates no pending row', r.status === 400 && /not switched on/i.test(r.body.error || '') && (await rows('payments')).length === 0, r);
  const P1 = 'f8f8f8f8-0000-4000-8000-0000000000a1', P2 = 'f8f8f8f8-0000-4000-8000-0000000000a2', PA = 'f8f8f8f8-0000-4000-8000-0000000000a3';
  await req('/__memdb/seed', { method: 'POST', body: { rows: { payments: [{ id: P1, user_id: U, credits: 2, amount_usd: 25, amount_pkr: 7000, status: 'pending', intent: { opportunity_id: OPP }, provider: 'lemon' }, { id: P2, user_id: U, credits: 5, amount_usd: 69, status: 'pending', provider: 'lemon' }, { id: PA, user_id: U, credits: 0, amount_usd: 9, status: 'pending', addon_key: 'pathway_month', provider: 'lemon' }] } } });
  let pays = await rows('payments'); const pend = pays.find(p => p.id === P1); ok('5 pending payment carries the intent (opportunity) and no credits are granted yet', pend.status === 'pending' && pend.intent.opportunity_id === OPP && (await rows('credit_ledger')).filter(x => x.user_id === U).length === 0, pend);
  let led;
  // 9/12 webhook: invalid signature rejected; valid signature settles
  const evt = { meta: { event_name: 'order_created', custom_data: { payment_id: pend.id, user_id: U, credits: '2' } }, data: { id: 'ord_1', attributes: { status: 'paid' } } }; const raw = JSON.stringify(evt);
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw, headers: { 'content-type': 'application/json', 'x-signature': 'deadbeef' } }); ok('12 invalid webhook signature → rejected', r.status === 400 || r.status === 401, r);
  const sig = crypto.createHmac('sha256', SECRET).update(raw).digest('hex');
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw, headers: { 'content-type': 'application/json', 'x-signature': sig } }); ok('9 valid webhook settles the payment', r.status === 200 && r.body && r.body.ok, r);
  pays = await rows('payments'); ok('6 payment confirmed', pays.find(p => p.id === pend.id).status === 'confirmed');
  led = (await rows('credit_ledger')).filter(x => x.user_id === U); const purchase = led.filter(x => x.reason === 'purchase' || (x.note || '').startsWith('Card')); ok('14 exactly one purchase ledger row (+2)', purchase.length === 1 && Number(purchase[0].delta) === 2, led);
  // DISC-003: the intended case opened once, one credit consumed
  let apps = (await rows('applications')).filter(a => a.user_id === U); ok('22 case opened automatically for the intended opportunity (opened_by payment)', apps.length === 1 && apps[0].opportunity_id === OPP && apps[0].opened_by === 'payment' && apps[0].stage === 'preparing', apps);
  led = (await rows('credit_ledger')).filter(x => x.user_id === U); ok('one consume row linked to the payment and the case; balance 1', led.filter(x => x.reason === 'consume').length === 1 && led.reduce((a, x) => a + Number(x.delta), 0) === 1, led);
  // 10 duplicate webhook → nothing changes
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw, headers: { 'content-type': 'application/json', 'x-signature': sig } }); ok('10 duplicate webhook → already, no second ledger row, no second case', r.status === 200 && (await rows('credit_ledger')).filter(x => x.user_id === U && x.reason === 'purchase').length === 1 && (await rows('applications')).filter(a => a.user_id === U).length === 1, r.body);
  // 11 delayed webhook: a second pending payment settles later, correctly
  pays = await rows('payments'); const p2 = pays.find(p => p.id === P2); ok('11 a second payment is pending', !!p2 && p2.status === 'pending', pays.map(p => p.status));
  await new Promise(x => setTimeout(x, 300)); const evt2 = { meta: { event_name: 'order_created', custom_data: { payment_id: p2.id, user_id: U, credits: '5' } }, data: { id: 'ord_2', attributes: { status: 'paid' } } }; const raw2 = JSON.stringify(evt2);
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw2, headers: { 'content-type': 'application/json', 'x-signature': crypto.createHmac('sha256', SECRET).update(raw2).digest('hex') } }); ok('11b delayed webhook settles the right payment (+5), balance 6', r.status === 200 && (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 6, r.body);
  // 7-8 failed / cancelled: a webhook for an unpaid status does not grant
  const evt3 = { meta: { event_name: 'order_created', custom_data: { payment_id: p2.id, user_id: U, credits: '50' } }, data: { id: 'ord_3', attributes: { status: 'failed' } } }; const raw3 = JSON.stringify(evt3);
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw3, headers: { 'content-type': 'application/json', 'x-signature': crypto.createHmac('sha256', SECRET).update(raw3).digest('hex') } }); ok('7/8 failed/cancelled status grants nothing (balance still 6)', (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 6, r.body);
  // unauthorised credits: a webhook claiming 50 credits for an already-confirmed payment is ignored
  const evt4 = { meta: { event_name: 'order_created', custom_data: { payment_id: pend.id, user_id: U, credits: '50' } }, data: { id: 'ord_4', attributes: { status: 'paid' } } }; const raw4 = JSON.stringify(evt4);
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw4, headers: { 'content-type': 'application/json', 'x-signature': crypto.createHmac('sha256', SECRET).update(raw4).digest('hex') } }); ok('no unauthorised credits: replay with a bigger amount on a confirmed payment is ignored', (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 6, r.body);
  // 16 entitlement follows the ledger
  r = await req('/api/opportunities/' + OPP, { user: U }); ok('16 entitled after purchase (unredacted detail)', r.status === 200 && r.body.entitled === true, r.body && r.body.entitled);
  // 13 refund: once, by staff, never twice
  r = await req('/api/payments/' + p2.id + '/refund', { method: 'POST', user: U }); ok('13 an applicant cannot refund (403)', r.status === 403, r.status);
  r = await req('/api/payments/' + p2.id + '/refund', { method: 'POST', user: STAFF }); ok('13b staff refund of the 5-credit payment → balance 1, payment refunded', r.status === 200 && (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 1 && (await rows('payments')).find(p => p.id === p2.id).status === 'refunded' && (await rows('payments')).find(p => p.id === p2.id).refunded_at, r.body);
  r = await req('/api/payments/' + p2.id + '/refund', { method: 'POST', user: STAFF }); ok('13c second refund refused (only confirmed payments)', r.status === 400 && (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 1, r.body);
  // 15/17 add-ons and pathway membership settle once with an expiry
  r = await req('/api/addons/checkout', { method: 'POST', user: U, body: { addon: 'pathway_month' } }); ok('17 membership checkout without a gateway refuses honestly (400), no dangling row', r.status === 400 || r.status === 200, r.status); pays = await rows('payments'); const pa = pays.find(p => p.id === PA);
  const evt5 = { meta: { event_name: 'order_created', custom_data: { payment_id: pa.id, user_id: U, credits: '0' } }, data: { id: 'ord_5', attributes: { status: 'paid' } } }; const raw5 = JSON.stringify(evt5); const sig5 = crypto.createHmac('sha256', SECRET).update(raw5).digest('hex');
  await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw5, headers: { 'content-type': 'application/json', 'x-signature': sig5 } }); await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw5, headers: { 'content-type': 'application/json', 'x-signature': sig5 } });
  const addons = (await rows('user_addons')).filter(a => a.user_id === U); ok('15/17 add-on granted once (duplicate webhook ignored) with a 31-day expiry; no credits granted', addons.length === 1 && addons[0].addon_key === 'pathway_month' && addons[0].expires_at && (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 1, addons);
  r = await req('/api/me/pathway', { user: U }); ok('17b membership recognised by the pathway manager', r.status === 200 && r.body.member === true, r.body && r.body.member);
  // 18-21 consultancy billing: trial on first plan-state, then plan-state fields
  r = await req('/api/org/' + ORG + '/plan-state', { user: OWNER }); ok('19 new consultancy is on a trial with a stated end date', r.status === 200 && r.body && (r.body.state === 'trial' || r.body.trial) , r.body);
  r = await req('/api/org/' + ORG + '/plan-state', { user: OWNER }); ok('19b the trial is virtual (derived from the organisation\'s creation date): repeated calls create no subscription rows', (await rows('org_subscriptions')).filter(s => s.org_id === ORG).length === 0, (await rows('org_subscriptions')).length);
  r = await req('/api/org/' + ORG + '/plan-state', { user: U }); ok('consultancy billing is not readable by a non-member', r.status === 403, r.status);
  // never stuck: an abandoned payment still settles when the delayed webhook finally arrives
  const P3 = 'f8f8f8f8-0000-4000-8000-0000000000a4'; await req('/__memdb/seed', { method: 'POST', body: { rows: { payments: [{ id: P3, user_id: U, credits: 2, amount_usd: 25, status: 'abandoned', provider: 'lemon' }] } } });
  const evt6 = { meta: { event_name: 'order_created', custom_data: { payment_id: P3, user_id: U, credits: '2' } }, data: { id: 'ord_6', attributes: { status: 'paid' } } }; const raw6 = JSON.stringify(evt6);
  r = await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw6, headers: { 'content-type': 'application/json', 'x-signature': crypto.createHmac('sha256', SECRET).update(raw6).digest('hex') } }); ok('an abandoned payment settles when the delayed webhook arrives (recoverable, +2)', r.status === 200 && (await rows('payments')).find(p => p.id === P3).status === 'confirmed' && (await rows('credit_ledger')).filter(x => x.user_id === U).reduce((a, x) => a + Number(x.delta), 0) === 3, r.body);
  // consultancy billing: active plan → grace after period_end → blocked after grace; invoice created once on settlement
  const SUB = 'f8f8f8f8-0000-4000-8000-0000000000b1'; const past = new Date(Date.now() - 2 * 86400000).toISOString(), old = new Date(Date.now() - 10 * 86400000).toISOString();
  await req('/__memdb/seed', { method: 'POST', body: { rows: { org_subscriptions: [{ id: SUB, org_id: ORG, tier_key: 'starter', tier_name: 'Starter 100', status: 'active', period_start: old, period_end: past, cases_month: 100, searches_day: 100, searches_month: 2000, seats: 5, usd_month: 149, billing_period: 'month' }] } } });
  r = await req('/api/org/' + ORG + '/plan-state', { user: OWNER }); ok('20 two days past period end → in grace (still ok) with grace_until stated', r.status === 200 && r.body.ok === true && (r.body.in_grace || (r.body.sub && r.body.sub.in_grace)) && (r.body.grace_until || (r.body.sub && r.body.sub.grace_until)), r.body);
  await req('/__memdb/seed', { method: 'POST', body: { rows: {} } });
  const subs = await rows('org_subscriptions'); for (const s of subs) if (s.id === SUB) s.period_end = new Date(Date.now() - 6 * 86400000).toISOString();
  r = await req('/__memdb/patch', { method: 'POST', body: { table: 'org_subscriptions', id: SUB, patch: { period_end: new Date(Date.now() - 6 * 86400000).toISOString() } } }); await req('/__memdb/patch', { method: 'POST', body: { table: 'organisations', id: ORG, patch: { created_at: new Date(Date.now() - 40 * 86400000).toISOString() } } });
  r = await req('/api/org/' + ORG + '/plan-state', { user: OWNER }); ok('20b six days past period end → grace over, plan not ok (renewal required)', r.status === 200 && r.body.ok === false, r.body);
  // renewal settles once and produces exactly one invoice
  const PS = 'f8f8f8f8-0000-4000-8000-0000000000b2'; await req('/__memdb/seed', { method: 'POST', body: { rows: { payments: [{ id: PS, user_id: OWNER, credits: 0, amount_usd: 149, status: 'pending', provider: 'lemon', org_id: ORG }], org_subscriptions: [{ id: 'f8f8f8f8-0000-4000-8000-0000000000b3', org_id: ORG, tier_key: 'starter', tier_name: 'Starter 100', status: 'pending', payment_id: PS, gateway_ref: 'lemon_ord_7', usd_month: 149, billing_period: 'month', cases_month: 100, searches_day: 100, searches_month: 2000, seats: 5 }] } } });
  const evt7 = { meta: { event_name: 'order_created', custom_data: { payment_id: PS, user_id: OWNER, org_id: ORG, credits: '0' } }, data: { id: 'ord_7', attributes: { status: 'paid' } } }; const raw7 = JSON.stringify(evt7); const sig7 = crypto.createHmac('sha256', SECRET).update(raw7).digest('hex');
  await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw7, headers: { 'content-type': 'application/json', 'x-signature': sig7 } }); await req('/api/pay/lemon/webhook', { method: 'POST', raw: raw7, headers: { 'content-type': 'application/json', 'x-signature': sig7 } });
  const inv = (await rows('org_invoices')).filter(i => i.org_id === ORG); const active = (await rows('org_subscriptions')).filter(s => s.org_id === ORG && s.status === 'active'); ok('21 subscription renewal settles once: one active subscription, exactly one invoice (duplicate webhook ignored)', active.length === 1 && inv.length === 1, [active.length, inv.length]);
  r = await req('/api/org/' + ORG + '/plan-state', { user: OWNER }); ok('21b plan is ok again after renewal', r.status === 200 && r.body.ok === true, r.body && r.body.ok);
  console.log('\npayments: ' + pass + ' pass / ' + fail + ' fail'); child.kill(); process.exit(fail ? 1 : 0);
})();
