/* PHASE 6 · DOCUMENTS, COMPLETENESS, OFFER → VISA, VISA DESK — on the in-memory database with configured (seeded) rules.
   Nothing here relies on a model. Proves: route suggestion and assessment come from configured rules with sources; every document
   requirement is classified (required/conditional) and stated (missing/awaiting verification/needs review/verified/expired) with
   legalisation flags only when a rule says so; expired and replacement documents; contradictions surface for review; refusal handling;
   visa case creation gates; applicant vs CRM document permissions. */
const { spawn } = require('child_process'); const PORT = 4497; const BASE = 'http://127.0.0.1:' + PORT;
const env = Object.assign({}, process.env, { NODE_ENV: 'test', FF_MEMDB: '1', FF_QUEUE: 'off', PORT: String(PORT), SUPABASE_URL: 'https://memdb.local', SUPABASE_ANON_KEY: 'x', SUPABASE_SERVICE_ROLE_KEY: 'x', ANTHROPIC_API_KEY: 'x', GEMINI_API_KEY: 'x', FF_DATA_KEY: '0000000000000000000000000000000000000000000000000000000000000001' });
const U = 'a6a6a6a6-0000-4000-8000-0000000000f1', OTHER = 'a6a6a6a6-0000-4000-8000-0000000000f2', OWNER = 'a6a6a6a6-0000-4000-8000-0000000000a1', OWNER_B = 'a6a6a6a6-0000-4000-8000-0000000000b1'; const tok = u => 'test:' + u + ':' + u.slice(-2) + '@test.local';
const ORG = 'e6e6e6e6-0000-4000-8000-00000000000a', ORGB = 'e6e6e6e6-0000-4000-8000-00000000000b', CL = 'f6f6f6f6-0000-4000-8000-0000000000c1', OFFER = 'f6f6f6f6-0000-4000-8000-0000000000d1', PASS_OLD = 'f6f6f6f6-0000-4000-8000-0000000000e1';
async function req(p, { method = 'GET', body, user, headers, raw } = {}) { const h = Object.assign(raw ? {} : { 'content-type': 'application/json' }, headers || {}); if (user) h.authorization = 'Bearer ' + tok(user); const r = await fetch(BASE + p, { method, headers: h, body: raw ? raw : (body ? JSON.stringify(body) : undefined) }); let j = null; try { j = await r.json(); } catch (e) {} return { status: r.status, body: j }; }
function multipart(files) { const b = '----ffv' + Date.now(); const parts = []; for (const f of files) { parts.push(Buffer.from('--' + b + '\r\nContent-Disposition: form-data; name="files"; filename="' + f.name + '"\r\nContent-Type: ' + f.type + '\r\n\r\n')); parts.push(f.data); parts.push(Buffer.from('\r\n')); } parts.push(Buffer.from('--' + b + '--\r\n')); return { body: Buffer.concat(parts), type: 'multipart/form-data; boundary=' + b }; }
const pdf = Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF');
(async () => {
  const child = spawn(process.execPath, ['server.js'], { env, stdio: ['ignore', 'pipe', 'pipe'] }); let log = ''; child.stdout.on('data', d => { log += d; }); child.stderr.on('data', d => { log += d; });
  for (let i = 0; i < 40; i++) { await new Promise(r => setTimeout(r, 250)); try { const r = await fetch(BASE + '/api/health'); if (r.ok) break; } catch (e) {} }
  let pass = 0, fail = 0; const ok = (n, c, x) => { if (c) { pass++; console.log('PASS  ' + n); } else { fail++; console.log('FAIL  ' + n + (x ? '  → ' + JSON.stringify(x).slice(0, 260) : '')); } };
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10), later = new Date(Date.now() + 5 * 365 * 86400000).toISOString().slice(0, 10);
  await req('/__memdb/seed', { method: 'POST', body: { reset: true, rows: {
    profiles: [{ id: U, email: 'f1@test.local', role: 'user', full_name: 'Umar Test', origin_country: 'PK', lane_pref: 'study', target_countries: ['GB'], mobility: { funding_source: 'family', test_name: 'IELTS', visa_refusals: '' } }, { id: OTHER, email: 'f2@test.local', role: 'user', full_name: 'Other' }, { id: OWNER, email: 'a1@test.local', role: 'user', full_name: 'Owner A' }, { id: OWNER_B, email: 'b1@test.local', role: 'user', full_name: 'Owner B' }],
    organisations: [{ id: ORG, name: 'Alpha', kind: 'agency', owner_user_id: OWNER, settings: {} }, { id: ORGB, name: 'Beta', kind: 'agency', owner_user_id: OWNER_B, settings: {} }],
    org_members: [{ org_id: ORG, user_id: OWNER, role: 'owner', status: 'active' }, { org_id: ORGB, user_id: OWNER_B, role: 'owner', status: 'active' }],
    clients: [{ id: CL, org_id: ORG, full_name: 'Umar Test', user_id: U, owner_user_id: OWNER, stage: 'offer', lane: 'study' }],
    offers: [{ id: OFFER, user_id: U, issuer: 'Beta University', country_code: 'GB', status: 'received', conditions: [] }],
    visa_rules: [
      { id: 'r1', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'eligibility', text: 'Unconditional offer (CAS) from a licensed sponsor', status: 'verified', source_url: 'https://www.gov.uk/student-visa' },
      { id: 'r2', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'document', text: 'Valid passport', value: { doc_type: 'passport', validity: 'valid for the whole stay' }, status: 'verified', source_url: 'https://www.gov.uk/student-visa/documents-you-must-provide' },
      { id: 'r3', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'document', text: 'Bank statement showing funds held for 28 days; certified translation if not in English', value: { doc_type: 'bank_statement' }, status: 'verified', source_url: 'https://www.gov.uk/student-visa/money' },
      { id: 'r4', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'document', text: 'TB test certificate if you are from a listed country', value: { doc_type: 'medical', condition: 'applicants from listed countries (Pakistan is listed)' }, status: 'verified', source_url: 'https://www.gov.uk/tb-test-visa' },
      { id: 'r5', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'document', text: 'English test result at B2 (SELT)', value: { doc_type: 'english_test' }, status: 'verified', source_url: 'https://www.gov.uk/student-visa/knowledge-of-english' },
      { id: 'r6', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'attestation', text: 'Pakistani degrees: HEC attestation before submission', value: { origin: 'PK' }, status: 'verified', source_url: 'https://hec.gov.pk/attestation' },
      { id: 'r7', country_code: 'GB', lane: 'study', route_key: 'uk_student', route_name: 'UK Student visa', rule_type: 'financial', text: 'Show tuition plus 9 months living costs', status: 'verified', source_url: 'https://www.gov.uk/student-visa/money' }],
    documents: [{ id: PASS_OLD, user_id: U, name: 'passport_old.pdf', kind: 'passport', doc_type: 'passport', storage_key: 'u/p1.pdf', mime: 'application/pdf', size_bytes: 10, generated: false, doc_status: 'ok', expiry_date: yesterday, extracted: { full_name: 'Umar Tesst', passport_number: 'AB123' } }]
  } } });
  // route suggestion is from the configured rules
  let r = await req('/api/visa/suggest?cc=GB&lane=study', { user: U }); ok('route suggestion comes from configured rules (uk_student)', r.status === 200 && JSON.stringify(r.body).includes('uk_student'), r.body);
  // assessment: documents with requirement class, states, sources, legalisation flags only where a rule says so
  r = await req('/api/visa/assess?cc=GB&route=uk_student', { user: U }); const a = r.body || {}; const byT = Object.fromEntries((a.required || []).map(x => [x.type, x]));
  ok('assessment lists exactly the rule documents (passport, bank statement, medical, english test)', a.required && a.required.length === 4 && byT.passport && byT.bank_statement && byT.medical && byT.english_test, (a.required || []).map(x => x.type));
  ok('every document requirement is traceable: rule text + official source', (a.required || []).every(x => x.rule_text && x.source_url && x.rule_verified === true), (a.required || []).map(x => [x.type, x.source_url]));
  ok('classification: passport/bank/english required; TB test conditional with its condition', byT.passport.requirement === 'required' && byT.bank_statement.requirement === 'required' && byT.medical.requirement === 'conditional' && /listed countries/.test(byT.medical.condition || ''), [byT.medical.requirement, byT.medical.condition]);
  ok('legalisation only where the rule says so: bank statement → translation flag; passport → no flag + honest note', byT.bank_statement.legalisation && byT.bank_statement.legalisation.translation === true && byT.passport.legalisation === null && /not specified/.test(byT.passport.legalisation_note || ''), [byT.bank_statement.legalisation, byT.passport.legalisation_note]);
  ok('origin attestation (PK → HEC) attached with its source, not invented for others', Array.isArray(byT.passport.origin_attestation) && /HEC/.test(byT.passport.origin_attestation[0].text) && /hec\.gov\.pk/.test(byT.passport.origin_attestation[0].source_url), byT.passport.origin_attestation);
  ok('states: expired passport → expired; others missing', byT.passport.state === 'expired' && byT.passport.state_label === 'expired' && byT.bank_statement.state === 'missing', [byT.passport.state, byT.bank_statement.state]);
  ok('completeness: missing + expired lists are correct; not ready', Array.isArray(a.missing) && a.missing.includes('bank_statement') && a.expired.includes('passport') && a.ready === false, [a.missing, a.expired, a.ready]);
  ok('flags from rules: financial rule satisfied by profile; refusal none', Array.isArray(a.flags) && !a.flags.some(f => /Funding source not set/.test(f.text)), a.flags);
  // contradictory information: passport name differs from the profile → the reader marks it for review (cross-check)
  r = await req('/api/profile/conflicts', { user: U }); ok('contradiction surfaces: passport name vs profile name flagged for review, not silently accepted', r.status === 200 && JSON.stringify(r.body).toLowerCase().includes('name'), r.body);
  // replacement passport: new one live (version 2), old superseded but kept; state moves to awaiting verification
  let m = multipart([{ name: 'passport_new.pdf', type: 'application/pdf', data: pdf }]); r = await req('/api/documents', { method: 'POST', raw: m.body, headers: { 'content-type': m.type, authorization: 'Bearer ' + tok(U) } });
  ok('replacement passport accepted', r.status === 200 && r.body && (r.body.results || []).some(x => x.kind === 'passport'), r.body);
  const rows = (await req('/__memdb/rows?table=documents')).body.rows; const passes = rows.filter(x => x.user_id === U && x.doc_type === 'passport');
  ok('versioning: two passport rows kept; old superseded; new is version 2 and live', passes.length === 2 && passes.some(x => x.id === PASS_OLD && x.superseded_at) && passes.some(x => x.version === 2 && !x.superseded_at && x.supersedes_id === PASS_OLD), passes.map(x => [x.name, x.version, !!x.superseded_at]));
  r = await req('/api/visa/assess?cc=GB&route=uk_student', { user: U }); const p2 = ((r.body || {}).required || []).find(x => x.type === 'passport') || {}; ok('after replacement the passport is awaiting verification (not expired, not verified yet)', p2.state === 'reading' && p2.state_label === 'awaiting verification', p2);
  // visa case creation: gated by the add-on / package; a fresh unpaid applicant gets a clear gate, no 500
  r = await req('/api/visa/cases', { method: 'POST', user: U, body: { cc: 'GB', route: 'uk_student', offer_id: OFFER } }); ok('visa case creation returns a clear gate or a case (never 500)', r.status === 200 || r.status === 402 || r.status === 403, r);
  // seed a case directly and test refusal handling + manual status
  await req('/__memdb/seed', { method: 'POST', body: { rows: { visa_cases: [{ id: 'f6f6f6f6-0000-4000-8000-0000000000aa', user_id: U, country_code: 'GB', route_key: 'uk_student', status: 'submitted', submitted_on: yesterday }] } } });
  r = await req('/api/visa/desk/f6f6f6f6-0000-4000-8000-0000000000aa/manual', { method: 'POST', user: U, body: { status: 'refused', note: 'Refused on funds' } }); ok('manual refusal recorded with the note', r.status === 200 && r.body.ok && r.body.patch.status === 'refused', r);
  r = await req('/api/visa/desk', { user: U }); const file = ((r.body || {}).files || (r.body || {}).cases || []).find(x => x.id === 'f6f6f6f6-0000-4000-8000-0000000000aa') || {}; ok('visa desk shows the refusal with source manual and the note', file.status === 'refused' && file.decision_source === 'manual' && /funds/.test(file.manual_note || ''), file);
  r = await req('/api/visa/desk/f6f6f6f6-0000-4000-8000-0000000000aa/manual', { method: 'POST', user: OTHER, body: { status: 'granted' } }); const f2 = ((await req('/api/visa/desk', { user: U })).body.files || []).find(x => x.id === 'f6f6f6f6-0000-4000-8000-0000000000aa') || {}; ok('another applicant cannot change my visa status (404, unchanged)', r.status === 404 && f2.status === 'refused', [r.status, f2.status]);
  // permissions: applicant vs CRM
  r = await req('/api/documents/' + PASS_OLD + '/url', { user: OTHER }); ok('another applicant cannot fetch my document URL', r.status === 403 || r.status === 404, r);
  r = await req('/api/org/' + ORG + '/clients/' + CL + '/overview', { user: OWNER }); ok('the consultancy that owns the client can open the client (documents visible through the client screen)', r.status === 200, r);
  r = await req('/api/org/' + ORGB + '/clients/' + CL + '/overview', { user: OWNER_B }); ok('another consultancy cannot open the client', r.status === 404 || r.status === 403, r);
  console.log('\nvisa: ' + pass + ' pass / ' + fail + ' fail'); child.kill(); process.exit(fail ? 1 : 0);
})();
