// lib/attestation.js — document attestation & legalisation rules, ORIGIN × DESTINATION, each with its source.
// Hague Apostille members accept a single apostille from the origin's competent authority; non-members need
// the embassy legalisation chain. Special regimes (e.g. Germany's APS for Pakistani/Indian applicants) are
// recorded explicitly. Everything is seeded UNVERIFIED into the same rules registry and verified by the team.
const HCCH = 'https://www.hcch.net/en/instruments/conventions/status-table/?cid=41';
// Destinations that are Apostille Convention parties (status table is the authority; verify at seed time).
const HAGUE = new Set(['DE', 'NO', 'FI', 'SE', 'DK', 'NL', 'AT', 'BE', 'IE', 'GB', 'PL', 'CZ', 'HU', 'EE', 'LV', 'LT', 'PT', 'ES', 'IT', 'FR', 'CH', 'LU', 'MT', 'CY', 'GR', 'HR', 'SI', 'SK', 'BG', 'RO', 'US', 'CA', 'AU', 'NZ', 'TR', 'AZ', 'GE', 'KZ', 'UZ', 'JP', 'KR', 'CN', 'HK', 'BN', 'OM', 'BH', 'SA']);
// Notes: Saudi Arabia acceded 2022 (in force Dec 2022); Bahrain, Oman are parties; UAE, Qatar, Kuwait, Malaysia, Singapore(no), Thailand(no), Taiwan(no) are NOT parties -> embassy legalisation.
const ORIGIN = {
  PK: { name: 'Pakistan', hague_member: true, competent: 'Ministry of Foreign Affairs (MOFA) Pakistan - apostille since 9 March 2023', steps_apostille: ['HEC attestation of degree and transcripts (online portal or HEC office)', 'MOFA apostille sticker (Islamabad or MOFA camp offices)'], steps_legalisation: ['HEC attestation', 'MOFA attestation', 'Destination embassy/consulate attestation in Pakistan'], sources: [['https://hec.gov.pk/english/services/students/DAS/Pages/default.aspx', 'HEC - Degree Attestation'], ['https://mofa.gov.pk/attestation', 'MOFA Pakistan - Attestation & Apostille'], [HCCH, 'HCCH - Apostille status table']] },
  IN: { name: 'India', hague_member: true, competent: 'Ministry of External Affairs (MEA) - apostille', steps_apostille: ['University / State HRD (Regional Authentication Centre) authentication', 'MEA apostille via authorised outsourcing agencies'], steps_legalisation: ['State HRD authentication', 'MEA attestation', 'Destination embassy attestation in India'], sources: [['https://www.mea.gov.in/apostille.htm', 'MEA - Apostille & Attestation'], [HCCH, 'HCCH - Apostille status table']] },
  BD: { name: 'Bangladesh', hague_member: true, competent: 'Ministry of Foreign Affairs - apostille (Convention in force for Bangladesh from 2025; verify)', steps_apostille: ['Education Board / UGC verification', 'Ministry of Education attestation', 'MOFA apostille'], steps_legalisation: ['Education Board / UGC verification', 'Ministry of Education attestation', 'MOFA attestation', 'Destination embassy attestation in Dhaka'], sources: [['https://mofa.gov.bd/', 'MOFA Bangladesh'], [HCCH, 'HCCH - Apostille status table']] },
  AE: { name: 'United Arab Emirates', hague_member: false, competent: 'MOFAIC attestation', steps_apostille: [], steps_legalisation: ['Issuing authority attestation', 'MOFAIC attestation', 'Destination embassy attestation in UAE'], sources: [['https://www.mofaic.gov.ae/en/services/attestation', 'MOFAIC - Attestation services']] },
  SA: { name: 'Saudi Arabia', hague_member: true, competent: 'Ministry of Foreign Affairs - apostille', steps_apostille: ['Ministry of Education attestation (for KSA-issued degrees)', 'MOFA apostille'], steps_legalisation: ['Ministry of Education attestation', 'MOFA attestation', 'Destination embassy attestation'], sources: [['https://www.mofa.gov.sa/', 'MOFA Saudi Arabia'], [HCCH, 'HCCH - Apostille status table']] },
  NP: { name: 'Nepal', hague_member: false, competent: 'Ministry of Foreign Affairs', steps_apostille: [], steps_legalisation: ['University / Ministry of Education attestation', 'MOFA attestation', 'Destination embassy attestation'], sources: [['https://mofa.gov.np/', 'MOFA Nepal']] },
  LK: { name: 'Sri Lanka', hague_member: false, competent: 'Ministry of Foreign Affairs - Consular Affairs', steps_apostille: [], steps_legalisation: ['University / Ministry of Education authentication', 'MFA Consular authentication', 'Destination embassy attestation'], sources: [['https://www.mfa.gov.lk/', 'MFA Sri Lanka']] },
  NG: { name: 'Nigeria', hague_member: true, competent: 'Ministry of Foreign Affairs - apostille (in force 2024; verify)', steps_apostille: ['University / Ministry of Education verification', 'MFA apostille'], steps_legalisation: ['Ministry of Education verification', 'MFA authentication', 'Destination embassy attestation'], sources: [[HCCH, 'HCCH - Apostille status table']] },
  EG: { name: 'Egypt', hague_member: false, competent: 'Ministry of Foreign Affairs', steps_apostille: [], steps_legalisation: ['Ministry of Higher Education authentication', 'MFA authentication', 'Destination embassy attestation'], sources: [['https://www.mfa.gov.eg/', 'MFA Egypt']] }
};
const SPECIAL = {
  DE: { for: ['PK', 'IN', 'VN', 'CN', 'MN'], text: 'Germany requires an APS certificate (Akademische Prüfstelle) for study applicants from Pakistan (and India, China, Vietnam, Mongolia) BEFORE the visa: document check and, for some, an interview. Apply early; it takes weeks.', source: ['https://www.aps-pakistan.de/', 'APS Pakistan (German Embassy)'] },
  AE: { for: ['*'], text: 'UAE is not an Apostille Convention party: degrees need MOFA attestation in the origin country, then UAE embassy attestation there, then MOFAIC attestation after arrival. Healthcare and teaching roles also require a DataFlow primary-source verification.', source: ['https://www.mofaic.gov.ae/en/services/attestation', 'MOFAIC - Attestation'] },
  QA: { for: ['*'], text: 'Qatar is not an Apostille party: origin MOFA attestation, Qatar embassy attestation, then Qatar MOFA after arrival; DataFlow for health professionals.', source: ['https://hukoomi.gov.qa', 'Hukoomi Qatar'] },
  KW: { for: ['*'], text: 'Kuwait is not an Apostille party: origin MOFA attestation, Kuwait embassy attestation, then Kuwait MOFA after arrival.', source: ['https://www.moi.gov.kw/', 'Kuwait MOI'] },
  MY: { for: ['*'], text: 'Malaysia is not an Apostille party: EMGS verifies academic documents for the Student Pass; keep certified true copies from the issuing institution.', source: ['https://visa.educationmalaysia.gov.my', 'EMGS'] },
  SG: { for: ['*'], text: 'Singapore is not an Apostille party (it uses notarised/legalised copies as the institution requires).', source: ['https://www.ica.gov.sg/', 'ICA Singapore'] },
  TH: { for: ['*'], text: 'Thailand is not an Apostille party: origin MOFA attestation and Thai embassy legalisation where required.', source: ['https://www.thaievisa.go.th/', 'Thailand e-Visa'] },
  TW: { for: ['*'], text: 'Taiwan is not an Apostille party: authentication by the Taipei representative office in the origin country.', source: ['https://www.boca.gov.tw/', 'Taiwan BOCA'] },
  GB: { for: ['*'], text: 'UK universities usually accept scanned originals; an apostille is rarely needed for admission. ECCTIS (UK ENIC) statements are needed for some professional registrations (GMC, NMC, GPhC).', source: ['https://www.enic.org.uk/', 'UK ENIC'] },
  CA: { for: ['*'], text: 'Canada accepts apostilles since January 2024; for immigration streams an Educational Credential Assessment (WES, ICAS, IQAS, CES, ICES) is what counts, not attestation.', source: ['https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/education-assessed.html', 'IRCC - Educational credential assessment'] },
  AU: { for: ['*'], text: 'Australia: skills assessments by the relevant authority (e.g. AHPRA, VETASSESS, Engineers Australia) matter more than attestation; certified copies by an authorised person.', source: ['https://immi.homeaffairs.gov.au/', 'Home Affairs'] },
  SA: { for: ['*'], text: 'Saudi Arabia joined the Apostille Convention (Dec 2022) but many employers still require Saudi Cultural Attaché attestation and SCFHS DataFlow for health roles; check the employer letter.', source: ['https://scfhs.org.sa', 'SCFHS'] }
};
function rulesFor(origin, dest) {
  const o = ORIGIN[origin] || (() => { const w = require('./world').origin(origin); return { name: w.name, hague_member: w.hague_member, competent: 'the competent authority designated under the Apostille Convention (listed on the HCCH status table) or the Ministry of Foreign Affairs', steps_apostille: ['Education ministry / university verification', 'Apostille by the designated competent authority'], steps_legalisation: ['Education ministry / university verification', 'Ministry of Foreign Affairs attestation', 'Destination embassy attestation'], sources: [[HCCH, 'HCCH - Apostille status table']] }; })(); const d = String(dest || '').toUpperCase(); const hague = HAGUE.has(d) && o.hague_member;
  const steps = hague ? o.steps_apostille : o.steps_legalisation;
  const out = [{ rule_type: 'attestation', text: (hague ? 'Apostille route (both ' + o.name + ' and ' + d + ' are Apostille Convention parties): ' : 'Embassy legalisation route (' + (o.hague_member ? d + ' is not an Apostille party' : o.name + ' is not an Apostille party') + '): ') + steps.join(' → ') + '. Keep two attested sets; translations must be attested too when the destination requires its language.', value: { origin, destination: d, route: hague ? 'apostille' : 'legalisation', steps }, source_url: o.sources[0][0], source_title: o.sources[0][1] }];
  for (const s of o.sources.slice(1)) out.push({ rule_type: 'attestation', text: 'Competent authority for ' + o.name + ': ' + o.competent + '.', value: { origin, destination: d }, source_url: s[0], source_title: s[1] });
  const sp = SPECIAL[d]; if (sp && (sp.for.includes('*') || sp.for.includes(origin))) out.push({ rule_type: 'attestation', text: sp.text, value: { origin, destination: d, special: true }, source_url: sp.source[0], source_title: sp.source[1] });
  return out.map(r => Object.assign({ country_code: d, route_key: d.toLowerCase() + '_attest_' + origin.toLowerCase(), route_name: 'Document attestation ' + o.name + ' → ' + d, lane: 'both' }, r));
}
module.exports = { HAGUE, ORIGIN, SPECIAL, rulesFor };
