// lib/caseview.js — ONE CASE, ONE SCREEN. Everything about a case in one payload: the timeline (created, prepared, sent,
// every reply and its classification, interviews, offers, visa file steps, decisions), documents and requirements on the
// side, the next action pinned on top, the estimated chance and the preflight state. Every other screen is a filter of this.
const { admin } = require('./supa');
const ST = { grey: ['draft', 'new', 'lead', 'discover'], blue: ['queued', 'sent', 'submitted', 'preparing', 'ready', 'decision_pending', 'interview', 'in_progress'], amber: ['needs_confirmation', 'waiting_on_you', 'action_required', 'needs_review', 'draft_ready'], green: ['offer', 'granted', 'done', 'accepted', 'hired', 'enrolled', 'verified'], red: ['rejected', 'refused', 'failed', 'closed', 'expired', 'blocked', 'withdrawn'] };
function colour(status) { const s = String(status || '').toLowerCase(); for (const [c, list] of Object.entries(ST)) if (list.includes(s)) return c; return 'grey'; }
async function view(userId, appId, opts) {
  const isStaff = opts && opts.staff; let q = admin().from('applications').select('*, opportunities(*)').eq('id', appId); if (!isStaff) q = q.eq('user_id', userId); const { data: a } = await q.maybeSingle(); if (!a) throw new Error('Case not found'); const uid = a.user_id; const o = a.opportunities || {};
  const [msgs, offers, visas, docs, tasks, interviews] = await Promise.all([
    admin().from('case_messages').select('id,direction,subject,from_addr,to_addr,classification,triage,needs_confirmation,confidence,received_at,read_at,extracted').eq('application_id', appId).order('received_at', { ascending: true }).limit(200).then(r => r.data || []),
    admin().from('offers').select('*').eq('application_id', appId).then(r => r.data || []),
    admin().from('visa_cases').select('*').eq('user_id', uid).eq('country_code', o.country_code || '~').order('created_at', { ascending: false }).limit(3).then(r => r.data || []),
    admin().from('documents').select('id,name,doc_type,doc_status,expiry_date,attestation_status,generated,application_id,created_at').eq('user_id', uid).or('application_id.eq.' + appId + ',generated.eq.false').order('created_at', { ascending: false }).limit(60).then(r => r.data || []),
    admin().from('journey_tasks').select('id,title,owner,due_date,status,stage').eq('user_id', uid).eq('status', 'open').order('due_date', { ascending: true, nullsFirst: false }).limit(10).then(r => r.data || []).catch(() => []),
    admin().from('interview_preps').select('id,created_at,scheduled_at').eq('application_id', appId).then(r => r.data || []).catch(() => [])
  ]);
  const t = []; const ev = (at, kind, title, detail, colourKey, ref) => { if (at) t.push({ at, kind, title, detail: detail || '', colour: colourKey || 'blue', ref: ref || null }); };
  ev(a.created_at, 'created', 'Case opened', o.title ? o.title + ' · ' + (o.institution || '') : '', 'grey'); if (a.prepared_at) ev(a.prepared_at, 'prepared', 'Documents prepared', 'CV, cover letter and statements written and audited', 'blue'); if (a.sent_at) ev(a.sent_at, 'sent', 'Sent from your ForiForeign address', a.sent_to || '', 'blue');
  for (const m of msgs) ev(m.received_at, m.direction === 'in' ? 'reply' : 'mail_out', m.direction === 'in' ? (m.classification ? m.classification.replace(/_/g, ' ') : 'Reply') + ': ' + (m.subject || '') : 'You wrote: ' + (m.subject || ''), m.direction === 'in' ? 'from ' + (m.from_addr || '') + (m.needs_confirmation ? ' · needs your answer' : '') : 'to ' + (m.to_addr || ''), m.direction === 'in' ? (m.needs_confirmation ? 'amber' : /reject|refus|unsuccessful/.test(m.classification || '') ? 'red' : /offer|admission|accept|interview/.test(m.classification || '') ? 'green' : 'blue') : 'grey', m.id);
  for (const i of interviews) ev(i.created_at, 'interview', 'Interview pack prepared', i.scheduled_at ? 'interview on ' + String(i.scheduled_at).slice(0, 16).replace('T', ' ') : '', 'green', i.id);
  for (const of of offers) ev(of.created_at, 'offer', 'Offer recorded', (of.status || '') + (of.deadline ? ' · decide by ' + of.deadline : ''), colour(of.status), of.id);
  for (const v of visas) { ev(v.created_at, 'visa', 'Visa file opened', v.route_key ? v.route_key.replace(/_/g, ' ') : '', 'blue', v.id); if (v.appointment_at) ev(v.appointment_at, 'visa_appt', 'Visa appointment', v.appointment_place || '', 'blue', v.id); if (v.submitted_on) ev(v.submitted_on, 'visa_submitted', 'Visa application submitted', v.tracking_ref ? 'ref ' + v.tracking_ref : '', 'blue', v.id); if (v.decision_on) ev(v.decision_on, 'visa_decision', 'Visa ' + v.status, v.decision_text ? String(v.decision_text).slice(0, 120) : '', colour(v.status), v.id); if (v.expected_decision_to && !v.decision_on) ev(v.expected_decision_to, 'visa_expected', 'Decision expected by', 'check-ins scheduled; tap "any news?" when you hear', 'amber', v.id); }
  t.sort((x, y) => new Date(x.at) - new Date(y.at));
  const next = tasks[0] ? { text: tasks[0].title, owner: tasks[0].owner, due: tasks[0].due_date, stage: tasks[0].stage } : (a.status === 'draft' ? { text: 'Prepare and send this case', owner: 'you' } : a.status === 'sent' ? { text: 'Wait for the reply; it lands in your mailbox and is read for you', owner: 'platform' } : null);
  let req = null; try { const { data: c } = await admin().from('app_settings').select('value').eq('key', 'reqbrief:' + uid + ':' + a.opportunity_id).maybeSingle(); req = c && c.value; } catch (e) {}
  return { case: { id: a.id, ref: a.ref, status: a.status, colour: colour(a.status), title: o.title, institution: o.institution, country_code: o.country_code, kind: o.kind, category: o.category, url: o.url, deadline: o.deadline, preflight_at: a.preflight_at, success: a.success_estimate || null, created_at: a.created_at }, next, timeline: t, documents: docs.map(d => ({ id: d.id, name: d.name, type: d.doc_type, status: d.doc_status, colour: d.doc_status === 'read' ? 'green' : d.doc_status === 'needs_review' ? 'amber' : /expired|failed/.test(d.doc_status || '') ? 'red' : 'blue', expiry: d.expiry_date, attestation: d.attestation_status, generated: d.generated })), requirements: req ? { summary: req.summary, items: (req.items || []).slice(0, 10) } : null, offers, visa_files: visas.map(v => ({ id: v.id, ref: v.ref, status: v.status, colour: colour(v.status), route: v.route_key, steps: v.steps, expected: v.expected_decision_to || null })), messages_count: msgs.length, unread: msgs.filter(m => m.direction === 'in' && !m.read_at).length, colours: ST };
}
module.exports = { view, colour, ST };
