// lib/checkins.js — the visa-tracking backbone when nothing arrives in the mailbox: an expected-decision window from the
// route's processing-time rule, scheduled "any news?" check-ins (in-app + WhatsApp) at 50%, 100% and 120% of the window,
// a one-tap answer (granted / refused / still waiting / more documents asked), and the public reference-tracking link.
const { admin } = require('./supa');
function parseWindow(text) { const t = String(text || '').toLowerCase(); const w = t.match(/(\d+)\s*(?:to|-|–)\s*(\d+)\s*(week|month|day)s?/) || t.match(/(\d+)\s*(week|month|day)s?/); if (!w) return null; const mult = { day: 1, week: 7, month: 30 }; if (w.length === 4) return { from: Number(w[1]) * mult[w[3]], to: Number(w[2]) * mult[w[3]] }; return { from: Math.round(Number(w[1]) * mult[w[2]] * 0.6), to: Number(w[1]) * mult[w[2]] }; }
async function schedule(visaCaseId) {
  const { data: v } = await admin().from('visa_cases').select('*').eq('id', visaCaseId).maybeSingle(); if (!v || !v.submitted_on) return null;
  let win = null; try { const { data: rules } = await admin().from('visa_rules').select('text').eq('country_code', v.country_code).eq('route_key', v.route_key).in('rule_type', ['processing', 'timeline']).limit(10); for (const r of (rules || [])) { win = parseWindow(r.text); if (win) break; } } catch (e) {}
  if (!win) win = { from: 15, to: 60 }; const base = new Date(v.submitted_on).getTime(); const d = n => new Date(base + n * 86400000).toISOString().slice(0, 10);
  const checkins = [{ at: d(Math.round(win.to * 0.5)), label: 'halfway' }, { at: d(win.to), label: 'expected' }, { at: d(Math.round(win.to * 1.2)), label: 'overdue' }];
  await admin().from('visa_cases').update({ expected_decision_from: d(win.from), expected_decision_to: d(win.to), checkins, checkin_state: 'scheduled' }).eq('id', v.id); return { window_days: win, checkins };
}
/* Daily: send the check-in that is due today; stop when the file has a decision. */
async function sweep() { const today = new Date().toISOString().slice(0, 10); const { data: files } = await admin().from('visa_cases').select('id,user_id,country_code,checkins,status,tracking_ref,ref').in('status', ['submitted', 'decision_pending']).not('checkins', 'is', null).limit(500); let sent = 0; const N = require('./notify'); const VT = require('./visa_tracking');
  for (const f of (files || [])) { const due = (f.checkins || []).find(c => c.at === today && !c.sent); if (!due) continue; const tr = VT.trackingFor(f.country_code); const link = tr && tr.official ? tr.official.url : null; const body = (due.label === 'overdue' ? 'Your ' + f.country_code + ' decision is past the usual window. ' : due.label === 'expected' ? 'Your ' + f.country_code + ' decision is due around now. ' : 'Halfway through the usual ' + f.country_code + ' processing window. ') + 'Any news? Tap: granted, refused, more documents asked, or still waiting.' + (link ? ' Official tracking: ' + link : '') + (f.tracking_ref ? ' Your ref: ' + f.tracking_ref : ''); await N.push(f.user_id, 'visa', 'Any news on your ' + f.country_code + ' visa?', body, 'profile'); try { const { data: p } = await admin().from('profiles').select('phone,notify_whatsapp').eq('id', f.user_id).maybeSingle(); if (p && p.phone && p.notify_whatsapp !== false) await require('./whatsapp').send(p.phone, (await require('./whatsapp').brandPrefix(f.user_id)) + ': ' + body.slice(0, 900)); } catch (e) {} due.sent = today; await admin().from('visa_cases').update({ checkins: f.checkins }).eq('id', f.id); sent++; }
  return { sent }; }
module.exports = { parseWindow, schedule, sweep };
