// lib/checkins.js — the visa-tracking backbone when nothing arrives in the mailbox: an expected-decision window from the
// route's processing-time rule, scheduled "any news?" check-ins (in-app + WhatsApp) at 50%, 100% and 120% of the window,
// a one-tap answer (granted / refused / still waiting / more documents asked), and the public reference-tracking link.
const { admin } = require('./supa');
function parseWindow(text) { const t = String(text || '').toLowerCase(); const w = t.match(/(\d+)\s*(?:to|-|–)\s*(\d+)\s*(week|month|day)s?/) || t.match(/(\d+)\s*(week|month|day)s?/); if (!w) return null; const mult = { day: 1, week: 7, month: 30 }; if (w.length === 4) return { from: Number(w[1]) * mult[w[3]], to: Number(w[2]) * mult[w[3]] }; return { from: Math.round(Number(w[1]) * mult[w[2]] * 0.6), to: Number(w[1]) * mult[w[2]] }; }
async function schedule(visaCaseId) {
  const { data: v } = await admin().from('visa_cases').select('*').eq('id', visaCaseId).maybeSingle(); if (!v || !v.submitted_on) return null;
  let win = null; try { const { data: rules } = await admin().from('visa_rules').select('text').eq('country_code', v.country_code).eq('route_key', v.route_key).in('rule_type', ['processing', 'timeline']).limit(10); for (const r of (rules || [])) { win = parseWindow(r.text); if (win) break; } } catch (e) {}
  if (!win) win = { from: 15, to: 60 }; const base = new Date(v.submitted_on).getTime(); const d = n => new Date(base + n * 86400000).toISOString().slice(0, 10);
  const checkins = [{ at: d(Math.round(win.to * 0.5)), label: 'halfway' }, { at: d(win.to), label: 'expected' }, { at: d(Math.round(win.to * 1.2)), label: 'overdue' }];
  await admin().from('visa_cases').update({ expected_decision_from: d(win.from), expected_decision_to: d(win.to), checkins, checkin_state: 'scheduled' }).eq('id', v.id); return { window_days: win, checkins };
}
/* Daily: send the check-in that is due today; stop when the file has a decision. */
/* The consultancy sees what its client sees: owners, managers and the assigned consultant are told the same moment. */
async function tellOrg(userId, title, body) { const { data: cl } = await admin().from('clients').select('org_id,owner_user_id').eq('user_id', userId).limit(3); const N = require('./notify'); for (const c of (cl || [])) { const ids = new Set([c.owner_user_id].filter(Boolean)); const { data: mem } = await admin().from('org_members').select('user_id').eq('org_id', c.org_id).eq('status', 'active').in('role', ['owner', 'manager']).limit(20); for (const m of (mem || [])) ids.add(m.user_id); for (const uid of ids) await N.push(uid, 'visa', title, body, 'work', c.org_id); } }
/* SMART STATUS, in this order and never daily:
   1. a decision already read from the applicant's ForiForeign mailbox wins and ends the matter;
   2. a manual update by the applicant or their consultant wins next;
   3. otherwise, ONLY once the country's usual processing window has passed, one automated check runs on the applicant's
      connected portal (watch scope) — exactly once; if the portal cannot be read, nobody retries: the applicant and the
      consultancy are told to check and record it manually. */
async function smartStatus(files) { const now = new Date(); const N = require('./notify'); let checked = 0, told = 0; for (const f of files) { try { if (f.manual_status_at || f.auto_checked_at) continue; const { data: dec } = await admin().from('case_messages').select('id,classification,received_at').eq('user_id', f.user_id).in('classification', ['visa_decision', 'visa_granted', 'visa_refused', 'decision']).gte('received_at', f.submitted_on ? String(f.submitted_on) : '2000-01-01').limit(1); if (dec && dec.length) { await admin().from('visa_cases').update({ decision_from_mail_at: dec[0].received_at }).eq('id', f.id); continue; } const from = f.expected_decision_from ? new Date(f.expected_decision_from) : null; if (!from || now < from) continue; const { data: conns } = await admin().from('portal_connections').select('*').eq('user_id', f.user_id).eq('consent', true).in('status', ['active', 'connected']).limit(3); const conn = (conns || []).find(c => !f.country_code || String(c.portal_key || '').toLowerCase().startsWith(String(f.country_code).toLowerCase())) || (conns || [])[0]; let result = 'no_portal'; if (conn) { try { const B = require('./browserbot'); const r = await B.watch(conn.id).catch(e => ({ ok: false, error: String(e && e.message || e) })); result = r && r.ok ? ('read: ' + String(r.summary || r.status || '').slice(0, 200)) : ('blocked: ' + String((r && r.error) || 'could not read').slice(0, 150)); checked++; } catch (e) { result = 'blocked: ' + String(e.message).slice(0, 150); } } await admin().from('visa_cases').update({ auto_checked_at: now.toISOString(), auto_check_result: result }).eq('id', f.id); if (!/^read:/.test(result)) { told++; const body = result === 'no_portal' ? 'The usual processing time for ' + f.country_code + ' has passed. Please check the portal yourself and record the status in Visa desk → Update status; ForiForeign will not try automatically.' : 'The portal could not be read (' + result.replace(/^blocked: /, '') + '). Please check it yourself and record the status; ForiForeign will not try again.'; await N.push(f.user_id, 'visa', 'Please check your ' + f.country_code + ' visa status', body, 'profile'); try { await tellOrg(f.user_id, 'Client visa: please check manually', body); } catch (e) {} } } catch (e) {} } return { checked, told }; }
async function sweep() { const today = new Date().toISOString().slice(0, 10); const { data: files } = await admin().from('visa_cases').select('id,user_id,country_code,checkins,status,tracking_ref,ref,submitted_on,expected_decision_from,manual_status_at,auto_checked_at').in('status', ['submitted', 'decision_pending']).not('checkins', 'is', null).limit(500); let sent = 0; const N = require('./notify'); const VT = require('./visa_tracking'); try { await smartStatus(files || []); } catch (e) {}
  for (const f of (files || [])) { const due = (f.checkins || []).filter(c => c.at <= today && !c.sent).sort((a, b) => a.at < b.at ? -1 : 1)[0]; if (!due) continue; const tr = VT.trackingFor(f.country_code); const link = tr && tr.official ? tr.official.url : null; const body = (due.label === 'overdue' ? 'Your ' + f.country_code + ' decision is past the usual window. ' : due.label === 'expected' ? 'Your ' + f.country_code + ' decision is due around now. ' : 'Halfway through the usual ' + f.country_code + ' processing window. ') + 'Any news? Tap: granted, refused, more documents asked, or still waiting.' + (link ? ' Official tracking: ' + link : '') + (f.tracking_ref ? ' Your ref: ' + f.tracking_ref : ''); await N.push(f.user_id, 'visa', 'Any news on your ' + f.country_code + ' visa?', body, 'profile'); try { await tellOrg(f.user_id, 'Visa check-in due · ' + (f.ref || f.id.slice(0, 8)), 'A check-in is due on the client\'s visa file (' + f.country_code + '). Open the client → Visa to record the status.'); } catch (e) {} try { const { data: p } = await admin().from('profiles').select('phone,notify_whatsapp').eq('id', f.user_id).maybeSingle(); if (p && p.phone && p.notify_whatsapp !== false) await require('./whatsapp').send(p.phone, (await require('./whatsapp').brandPrefix(f.user_id)) + ': ' + body.slice(0, 900)); } catch (e) {} due.sent = today; await admin().from('visa_cases').update({ checkins: f.checkins }).eq('id', f.id); sent++; }
  return { sent }; }
module.exports = { smartStatus, parseWindow, schedule, sweep };
