// lib/costintel.js — the Cost Intelligence layer. Real numbers, not estimates where a number exists:
//   AI: every model call is already metered by the router into ai_cost_ledger (provider, model, tokens, USD).
//   Infra: monthly fixed costs you enter once (Railway, Supabase, Resend, domains, WhatsApp, Redis) in Settings → costs.
//   Gateway: percentage + fixed per transaction from Settings → costs.
//   Storage and mail: counted from the tables.
// It answers: what each capability costs, what each person/organisation cost this month, what each package and plan
// truly costs to deliver, the earnings, the margin, and the NEGOTIATION FLOOR: the lowest price that still keeps the target
// margin (a manager may discount to the floor; only the owner may go below; both are logged). No price on the platform can
// fall below the floor without the owner, which is the rule the sales side must follow.
const { admin } = require('./supa');
const PRICES = { // USD per 1M tokens, editable in Settings → costs.model_prices
  'claude-sonnet': { in: 3, out: 15 }, 'claude-haiku': { in: 0.8, out: 4 }, 'claude-opus': { in: 15, out: 75 }, 'gpt-4o': { in: 2.5, out: 10 }, 'gpt-4o-mini': { in: 0.15, out: 0.6 }, 'gemini-flash': { in: 0.1, out: 0.4 }, 'gemini-pro': { in: 1.25, out: 10 }, default: { in: 2, out: 8 } };
function priceFor(model, table) { const t = Object.assign({}, PRICES, table || {}); const m = String(model || '').toLowerCase(); for (const k of Object.keys(t)) if (k !== 'default' && m.includes(k.replace('claude-', '').replace('gemini-', ''))) return t[k]; return t.default; }
async function meter({ userId, orgId, purpose, provider, model, inputTokens, outputTokens, ms, ok, priceTable }) { try { const pr = priceFor(model, priceTable); const cost = ((inputTokens || 0) * pr.in + (outputTokens || 0) * pr.out) / 1e6; await admin().from('ai_usage').insert({ user_id: userId || null, org_id: orgId || null, purpose, provider, model, input_tokens: inputTokens || 0, output_tokens: outputTokens || 0, cost_usd: Math.round(cost * 1e6) / 1e6, ms: ms || null, ok: ok !== false }); return cost; } catch (e) { return 0; } }
async function report() {
  const cfg = await require('./settings').getConfig(); const C = cfg.costs || {}; const fixed = Object.assign({ railway: 20, supabase: 25, resend: 20, domains: 3, whatsapp: 0, redis: 0, other: 0 }, C.fixed_monthly_usd || {}); const gw = Object.assign({ pct: 5, fixed: 0.5 }, C.gateway || {}); const target = Number(C.target_margin_pct) || 40; const floorPct = Number(C.floor_margin_pct) || 25;
  const since = new Date(Date.now() - 30 * 86400000).toISOString();
  const [{ data: ai }, { data: pays }, { count: users }, { count: docs }, { count: mails }] = await Promise.all([admin().from('ai_cost_ledger').select('purpose,provider,model,cost_usd,est_cost_usd,input_tokens,output_tokens,user_id').gte('created_at', since), admin().from('payments').select('credits,addon_key,kind,user_id,created_at,confirmed_at').eq('status', 'confirmed').gte('confirmed_at', since), admin().from('profiles').select('id', { count: 'exact', head: true }), admin().from('documents').select('id', { count: 'exact', head: true }), admin().from('case_messages').select('id', { count: 'exact', head: true }).gte('received_at', since)]);
  const byPurpose = {}, byUser = {}, byOrg = {}; let aiTotal = 0; for (const r of (ai || [])) { const c = Number(r.cost_usd != null ? r.cost_usd : r.est_cost_usd) || (((r.input_tokens || 0) * priceFor(r.model, C.model_prices).in + (r.output_tokens || 0) * priceFor(r.model, C.model_prices).out) / 1e6); aiTotal += c; byPurpose[r.purpose] = (byPurpose[r.purpose] || 0) + c; if (r.user_id) byUser[r.user_id] = (byUser[r.user_id] || 0) + c; }
  const fixedTotal = Object.values(fixed).reduce((a, b) => a + (Number(b) || 0), 0); const storageUsd = ((docs || 0) * 0.4 / 1024) * 0.021; // ~0.4MB per document at $0.021/GB-month
  const tiers = ((cfg.packages || {}).tiers || []); const agency = ((cfg.agency || {}).tiers || (cfg.agency || {}).plans || []); const addons = cfg.addons || {};
  const sold = (pays || []); const casesSold = sold.reduce((a, p) => a + (Number(p.credits) || 0), 0); const revenue = sold.reduce((a, p) => { const t = tiers.find(x => Number(x.credits) === Number(p.credits)); if (t) return a + Number(t.promo_usd || t.usd); if (p.addon_key) return a + (Number(addons[p.addon_key + '_usd']) || 0); if (p.kind === 'agency_subscription') { const g = agency[1] || agency[0] || {}; return a + (Number(g.usd_month) || 0); } return a; }, 0);
  const perCaseAi = casesSold ? aiTotal / Math.max(casesSold, 1) : (byPurpose.case_writing || 0.6); const perUserFixed = fixedTotal / Math.max(users || 1, 1);
  const pkg = tiers.map(t => { const price = Number(t.promo_usd || t.usd) || 0; const cost = perCaseAi * Number(t.credits) + (byPurpose.search_verify ? Math.min(2, byPurpose.search_verify / Math.max(users || 1, 1)) : 0.7) + perUserFixed + storageUsd; const fee = price * gw.pct / 100 + gw.fixed; const margin = price - cost - fee; return { name: t.name, credits: t.credits, price, cost: r2(cost), gateway: r2(fee), margin: r2(margin), margin_pct: price ? Math.round(100 * margin / price) : null, floor_price: r2((cost + gw.fixed) / (1 - gw.pct / 100 - floorPct / 100)), target_price: r2((cost + gw.fixed) / (1 - gw.pct / 100 - target / 100)) }; });
  const plans = agency.map(t => { const price = Number(t.usd_month) || 0; const util = Number(C.agency_utilisation_pct) || 60; const cost = perCaseAi * Number(t.cases_month) * util / 100 + Number(t.searches_month || 0) * util / 100 * 0.12 + fixedTotal * 0.05; const fee = price * gw.pct / 100; const margin = price - cost - fee; return { name: t.name, price, cost: r2(cost), margin: r2(margin), margin_pct: price ? Math.round(100 * margin / price) : null, floor_price: r2(cost / (1 - gw.pct / 100 - floorPct / 100)), target_price: r2(cost / (1 - gw.pct / 100 - target / 100)), utilisation_pct: util }; });
  const topUsers = Object.entries(byUser).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([u, c]) => ({ user_id: u, cost: r2(c) })); const topOrgs = Object.entries(byOrg).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([o, c]) => ({ org_id: o, cost: r2(c) }));
  return { period_days: 30, ai: { total: r2(aiTotal), by_purpose: Object.fromEntries(Object.entries(byPurpose).map(([k, v]) => [k, r2(v)])), calls: (ai || []).length }, fixed_monthly: fixed, fixed_total: r2(fixedTotal), storage_usd: r2(storageUsd), mails_30d: mails || 0, users, revenue_30d: r2(revenue), cases_sold_30d: casesSold, total_cost_30d: r2(aiTotal + fixedTotal + storageUsd), net_30d: r2(revenue - aiTotal - fixedTotal - storageUsd), per_case_ai: r2(perCaseAi), packages: pkg, agency_plans: plans, negotiation: { target_margin_pct: target, floor_margin_pct: floorPct, rule: 'Managers may discount to the floor price; below the floor only the owner, with a reason, logged. Prices shown to buyers are list; discounts apply through referral credit, coupons or annual terms, never by editing an invoice.' }, top_users: topUsers, top_orgs: topOrgs };
}
const r2 = n => Math.round((Number(n) || 0) * 100) / 100;
module.exports = { meter, report, priceFor, PRICES };
