// lib/crypto.js — Day 10 · field-level encryption for the identifiers a breach would hurt most.
// AES-256-GCM with a key from FF_DATA_KEY (32 bytes, base64 or hex). Without the key the
// platform still works and /api/health reports "field encryption: off" so it is never silent.
const crypto = require('crypto');
function key() { const k = process.env.FF_DATA_KEY || ''; if (!k) return null; const b = /^[0-9a-f]{64}$/i.test(k) ? Buffer.from(k, 'hex') : Buffer.from(k, 'base64'); return b.length === 32 ? b : null; }
function enabled() { return !!key(); }
function encrypt(text) { const k = key(); if (!k || text == null || text === '') return null; const iv = crypto.randomBytes(12); const c = crypto.createCipheriv('aes-256-gcm', k, iv); const enc = Buffer.concat([c.update(String(text), 'utf8'), c.final()]); return 'v1.' + iv.toString('base64') + '.' + c.getAuthTag().toString('base64') + '.' + enc.toString('base64'); }
function decrypt(blob) { const k = key(); if (!k || !blob || typeof blob !== 'string' || !blob.startsWith('v1.')) return null; try { const [, iv, tag, enc] = blob.split('.'); const d = crypto.createDecipheriv('aes-256-gcm', k, Buffer.from(iv, 'base64')); d.setAuthTag(Buffer.from(tag, 'base64')); return Buffer.concat([d.update(Buffer.from(enc, 'base64')), d.final()]).toString('utf8'); } catch (e) { return null; } }
function mask(v) { const s = String(v || ''); if (s.length <= 4) return s ? '••••' : ''; return '•'.repeat(Math.max(0, s.length - 4)) + s.slice(-4); }
const SENSITIVE_FIELDS = ['passport_number', 'cnic'];
/* Re-encrypt every stored secret from the OLD key to the CURRENT key (FF_DATA_KEY). Run once after rotating the env var. */
async function reencryptAll(oldKeyStr) { const { admin } = require('./supa'); const crypto = require('crypto'); const k = String(oldKeyStr || ''); const oldKey = /^[0-9a-f]{64}$/i.test(k) ? Buffer.from(k, 'hex') : Buffer.from(k, 'base64'); if (oldKey.length !== 32) throw new Error('old key must be 32 bytes (hex or base64)'); const dec = blob => { try { const b = Buffer.from(String(blob), 'base64'); const iv = b.subarray(0, 12), tag = b.subarray(12, 28), body = b.subarray(28); const d = crypto.createDecipheriv('aes-256-gcm', oldKey, iv); d.setAuthTag(tag); return Buffer.concat([d.update(body), d.final()]).toString('utf8'); } catch (e) { return null; } }; const out = { portal_connections: 0, skipped: 0 }; const { data: rows } = await admin().from('portal_connections').select('id,secret_enc').not('secret_enc', 'is', null).limit(5000); for (const r of (rows || [])) { const plain = dec(r.secret_enc); if (plain == null) { out.skipped++; continue; } await admin().from('portal_connections').update({ secret_enc: encrypt(plain) }).eq('id', r.id); out.portal_connections++; } return out; }
module.exports = { reencryptAll, enabled, encrypt, decrypt, mask, SENSITIVE_FIELDS };
