// lib/dailybrief.js — the Daily Brief agent: every morning, yesterday in one page for the admin: clients and applicants,
// their replies, what the agents did and what came back, next plan, revenue, support, bugs and glitches, and the
// self-heal actions taken overnight. Stored, shown in Admin → Overview, emailed to the official address.
const { admin } = require('./supa'); const { callAI } = require('./router');
async function build(dateStr) {
  const day = dateStr || new Date(Date.now() - 86400000).toISOString().slice(0, 10); const from = day + 'T00:00:00Z', to = day + 'T23:59:59Z';
  const c = async (t, f) => { try { let q = admin().from(t).select('id', { count: 'exact', head: true }).gte(f || 'created_at', from).lte(f || 'created_at', to); const { count } = await q; return count || 0; } catch (e) { return 0; } };
  const [signups, apps, mailsIn, mailsOut, offers, visas, payments, tickets, leads, prospectsReplied, jobsDone, jobsDead, policy, notif, alerts] = await Promise.all([c('profiles'), c('applications'), admin().from('case_messages').select('id', { count: 'exact', head: true }).eq('direction', 'in').gte('received_at', from).lte('received_at', to).then(r => r.count || 0), admin().from('case_messages').select('id', { count: 'exact', head: true }).eq('direction', 'out').gte('received_at', from).lte('received_at', to).then(r => r.count || 0), c('offers'), admin().from('visa_cases').select('id', { count: 'exact', head: true }).gte('updated_at', from).lte('updated_at', to).then(r => r.count || 0), admin().from('payments').select('credits,amount_pkr,status,addon_key,kind').eq('status', 'confirmed').gte('confirmed_at', from).lte('confirmed_at', to).then(r => r.data || []), admin().from('support_tickets').select('id,category,priority,status,subject,auto_replied').gte('created_at', from).lte('created_at', to).then(r => r.data || []), c('leads'), admin().from('prospects').select('id,name,stage').gte('updated_at', from).lte('updated_at', to).then(r => r.data || []), admin().from('job_queue').select('id', { count: 'exact', head: true }).eq('status', 'done').gte('updated_at', from).lte('updated_at', to).then(r => r.count || 0), admin().from('job_queue').select('type,last_error').eq('status', 'dead').gte('updated_at', from).lte('updated_at', to).then(r => r.data || []), admin().from('policy_updates').select('country_code,severity,summary').gte('detected_at', from).lte('detected_at', to).then(r => r.data || []), admin().from('notifications').select('kind').gte('created_at', from).lte('created_at', to).then(r => r.data || []), admin().from('selfheal_log').select('kind,action,outcome').gte('created_at', from).lte('created_at', to).then(r => r.data || [])]);
  const cls = {}; try { const { data } = await admin().from('case_messages').select('classification').eq('direction', 'in').gte('received_at', from).lte('received_at', to); for (const r of (data || [])) cls[r.classification || 'unread'] = (cls[r.classification || 'unread'] || 0) + 1; } catch (e) {}
  const kinds = {}; for (const n of notif) kinds[n.kind] = (kinds[n.kind] || 0) + 1;
  const content = { day, people: { signups, applications_sent: apps, replies_received: mailsIn, replies_by_type: cls, mails_sent: mailsOut, offers_recorded: offers, visa_files_updated: visas, leads }, money: { payments: payments.length, cases_sold: payments.reduce((a, p) => a + (Number(p.credits) || 0), 0), addons: payments.filter(p => p.addon_key).length, agency_subscriptions: payments.filter(p => p.kind === 'agency_subscription').length }, agents: { jobs_done: jobsDone, jobs_dead: jobsDead.length, dead_types: [...new Set(jobsDead.map(j => j.type))], notifications: kinds, policy_changes: policy.length, policy: policy.slice(0, 5) }, support: { tickets: tickets.length, auto_replied: tickets.filter(t => t.auto_replied).length, urgent: tickets.filter(t => t.priority === 'urgent' || t.priority === 'high').map(t => t.subject).slice(0, 5) }, prospecting: { touched: prospectsReplied.length, interested: prospectsReplied.filter(p => p.stage === 'replied' || p.stage === 'trial').map(p => p.name).slice(0, 5) }, selfheal: alerts.slice(0, 10) };
  let summary = ''; try { summary = await callAI('high_value', `Write the admin's morning brief for ForiForeign for ${day} in 8-12 short lines, plain English, no long dashes, no stock phrases: what happened with applicants and clients, what the agents did and what came back, money, support, problems and what was healed, and a 3-line next plan with guidance the admin should give today. Data: ${JSON.stringify(content).slice(0, 6000)}`, { maxTokens: 600 }); summary = require('./partnerships').humanize(summary); } catch (e) { summary = 'Brief data collected; the narrative could not be written (AI unavailable).'; }
  await admin().from('daily_briefs').upsert({ brief_date: day, content, text_summary: summary }, { onConflict: 'brief_date' });
  try { const { data: admins } = await admin().from('profiles').select('id').in('role', ['admin', 'super_admin']); for (const a of (admins || [])) await require('./notify').push(a.id, 'brief', 'Morning brief ' + day, summary.slice(0, 900), 'adminx'); } catch (e) {}
  try { const M = require('./mailer'); if (M.enabled()) await M.send(process.env.MAIL_REPLY_TO || 'admin@foriforeign.com', 'ForiForeign morning brief ' + day, M.wrap('Morning brief ' + day, summary, 'adminx')); } catch (e) {}
  return { day, summary, content };
}
async function latest(n) { const { data } = await admin().from('daily_briefs').select('*').order('brief_date', { ascending: false }).limit(n || 7); return data || []; }
module.exports = { build, latest };
