// lib/economics.js — the Economics agent: what each capability costs us, what each package costs to deliver, the margin
// at today's price, and a suggested price. Unit costs are editable in Settings (cfg.unit_costs) so the numbers follow
// your real invoices, not my guesses.
const { admin } = require('./supa');
const DEFAULT_UNIT_USD = { discovery: 0.35, doc_read: 0.02, case_prep: 0.60, case_brain: 0.03, interview_prep: 0.25, refusal_analysis: 0.20, portal_watch: 0.002, mail_in: 0.001, mail_out: 0.001, infra_per_user_month: 0.05 };
async function unitCosts() { const cfg = await require('./settings').getConfig(); return Object.assign({}, DEFAULT_UNIT_USD, cfg.unit_costs || {}); }
function packageCost(u, tier) { const cases = Number(tier.credits) || 1, views = Number(tier.view) || 5; const searches = 4; return { discovery: searches * u.discovery, docs: 6 * u.doc_read, prep: cases * u.case_prep, brain: 8 * cases * u.case_brain, interview: Math.min(cases, 2) * u.interview_prep, infra: 3 * u.infra_per_user_month, total: searches * u.discovery + 6 * u.doc_read + cases * u.case_prep + 8 * cases * u.case_brain + Math.min(cases, 2) * u.interview_prep + 3 * u.infra_per_user_month }; }
async function report() {
  const u = await unitCosts(); const cfg = await require('./settings').getConfig(); const tiers = (cfg.packages && cfg.packages.tiers) || [];
  const since = new Date(Date.now() - 30 * 86400000).toISOString(); const { data: um } = await admin().from('usage_meter').select('capability').gte('created_at', since); const by = {}; for (const r of (um || [])) by[r.capability] = (by[r.capability] || 0) + 1;
  const spend30 = Object.entries(by).reduce((a, [k, n]) => a + n * (u[k] || 0), 0);
  const { data: pays } = await admin().from('payments').select('credits,amount_pkr,status,created_at').eq('status', 'confirmed').gte('created_at', since); const soldCases = (pays || []).reduce((a, p) => a + (Number(p.credits) || 0), 0);
  const packages = tiers.map(t => { const c = packageCost(u, t); const price = Number(t.promo_usd || t.usd) || 0; const fee = price * 0.05 + 0.5; const margin = price - c.total - fee; const suggested = Math.ceil((c.total + fee) / 0.35 / 5) * 5; return { name: t.name, credits: t.credits, price_usd: price, cost_usd: Math.round(c.total * 100) / 100, gateway_fee_usd: Math.round(fee * 100) / 100, margin_usd: Math.round(margin * 100) / 100, margin_pct: price ? Math.round(100 * margin / price) : null, suggested_min_price_usd: suggested, breakdown: c }; });
  const agency = ((cfg.agency && cfg.agency.tiers) || []).map(t => { const c = packageCost(u, { credits: t.cases_month, view: 20 }); const price = Number(t.usd_month) || 0; const margin = price - c.total - price * 0.05; return { name: t.name, price_usd: price, cost_usd: Math.round(c.total * 100) / 100, margin_usd: Math.round(margin * 100) / 100, margin_pct: price ? Math.round(100 * margin / price) : null, suggested_min_price_usd: Math.ceil((c.total * 1.05) / 0.4 / 10) * 10 }; });
  const fu = cfg.fair_use || {}; const freeCostPerUser = (Number(fu.free_lifetime_searches) || 10) * u.discovery * (1 / 3) + 3 * u.doc_read + u.infra_per_user_month;   // one pass per free search
  const { count: freeUsers30 } = await admin().from('profiles').select('id', { count: 'exact', head: true }).gte('created_at', since); const lowestMargin = packages.length ? Math.min(...packages.map(p => p.margin_usd)) : 10;
  const freeTier = { free_lifetime_searches: Number(fu.free_lifetime_searches) || 10, daily_free_searches: Number(fu.daily_searches) || 3, results_visible_free: Number(fu.free_results_visible) || 5, cost_per_free_user_usd: Math.round(freeCostPerUser * 100) / 100, new_accounts_30d: freeUsers30 || 0, free_cost_30d_usd: Math.round((freeUsers30 || 0) * freeCostPerUser * 100) / 100, breakeven_conversion_pct: lowestMargin > 0 ? Math.round(1000 * freeCostPerUser / lowestMargin) / 10 : null, note: 'Break-even: the share of free accounts that must buy the cheapest package for free searches to pay for themselves.' };
  const advice = [];
  if (freeTier.breakeven_conversion_pct != null && freeTier.breakeven_conversion_pct > 8) advice.push('Free tier costs $' + freeTier.cost_per_free_user_usd + ' per account; you need ' + freeTier.breakeven_conversion_pct + '% to convert. Lower free_lifetime_searches or raise the cheapest package.');
  for (const p of packages) { if (p.margin_pct != null && p.margin_pct < 35) advice.push(p.name + ': margin ' + p.margin_pct + '% is thin; raise to at least $' + p.suggested_min_price_usd + ' or cut discovery passes per search.'); }
  if ((by.discovery || 0) > (soldCases || 1) * 8) advice.push('Discovery runs (' + (by.discovery || 0) + ') are high relative to cases sold (' + soldCases + '); tighten the free-search allowance or push structured sources so fewer AI passes run.');
  if ((by.doc_read || 0) > 2000) advice.push('Document reads are high; batch reads and skip re-reading unchanged files.');
  if (!advice.length) advice.push('Margins are healthy at current unit costs; re-check after the first real invoices from the AI providers.');
  return { unit_costs_usd: u, usage_30d: by, ai_spend_30d_usd: Math.round(spend30 * 100) / 100, cases_sold_30d: soldCases, packages, agency, free_tier: freeTier, advice };
}
module.exports = { report, packageCost, DEFAULT_UNIT_USD };
