// lib/emigration.js — the ORIGIN side of a labour or work move: emigration clearance, protector, smart card, labour permit,
// insurance and pre-departure orientation, per origin country. Without these a worker can be stopped at the airport or lose
// legal protection abroad. Sourced; verify on the authority's page.
const E = {
  PK: { authority: 'Bureau of Emigration & Overseas Employment (BEOE) / Protector of Emigrants', url: 'https://beoe.gov.pk/', steps: ['Register on the BEOE/OEC system; get the employer or OEP job order verified', 'Protector of Emigrants clearance (protectorate stamp) before departure, with State Life insurance and OPF welfare fund', 'Pre-departure orientation (OPF)', 'Keep the contract copy attested by the Pakistan mission where the employer requires'], fees: 'Government fees only; a licensed OEP may charge the regulated service fee; no other fees', warning: 'Direct (individual) visas also need Protector registration; travelling without it risks offloading.' },
  IN: { authority: 'eMigrate (Ministry of External Affairs) / Protector of Emigrants', url: 'https://emigrate.gov.in/', steps: ['ECR passport holders need emigration clearance for the 18 ECR countries; employers must be registered on eMigrate', 'Use only registered Recruiting Agents (RA)', 'Pravasi Bharatiya Bima Yojana insurance', 'Pre-departure orientation'], fees: 'Regulated RA service charge; no other fees', warning: 'ECNR passport holders do not need clearance for ECR countries but should still use registered RAs.' },
  BD: { authority: 'Bureau of Manpower, Employment and Training (BMET) / BOESL', url: 'https://www.bmet.gov.bd/', steps: ['BMET registration and smart card (emigration clearance)', 'Recruiting agency must be licensed; BOESL for government-to-government (Korea EPS, some Gulf)', 'Wage Earners\' Welfare Board insurance', 'Pre-departure briefing'], fees: 'Government-set ceilings by destination; no other fees', warning: 'Smart card is checked at the airport.' },
  NP: { authority: 'Department of Foreign Employment (DoFE)', url: 'https://dofe.gov.np/', steps: ['Labour permit (shram swikriti) from DoFE', 'Licensed manpower agency or individual (direct) permit', 'Foreign employment insurance and welfare fund', 'Pre-departure orientation'], fees: 'Free-visa free-ticket rule for most Gulf and Malaysia; regulated agency fee otherwise', warning: 'Airport immigration checks the labour permit.' },
  PH: { authority: 'Department of Migrant Workers (DMW)', url: 'https://dmw.gov.ph/', steps: ['Job order verified by the Philippine labour office abroad', 'Licensed agency or direct hire approval', 'Overseas Employment Certificate (OEC)', 'PDOS pre-departure orientation; OWWA and PhilHealth'], fees: 'Placement fee capped at one month salary except where forbidden (domestic work, seafarers)', warning: 'No OEC, no exit.' },
  LK: { authority: 'Sri Lanka Bureau of Foreign Employment (SLBFE)', url: 'https://www.slbfe.lk/', steps: ['Register the job with SLBFE', 'Licensed agency', 'Insurance and orientation'], fees: 'Regulated', warning: 'Registration checked at the airport.' },
  ID: { authority: 'BP2MI', url: 'https://bp2mi.go.id/', steps: ['Registration with BP2MI', 'Licensed placement company (P3MI) or G2G', 'Insurance and orientation'], fees: 'Regulated; zero-fee for some sectors', warning: '' },
  ET: { authority: 'Ministry of Labour and Skills', url: 'https://www.mols.gov.et/', steps: ['Licensed agency under the overseas employment proclamation', 'Training and certification', 'Insurance'], fees: 'Regulated', warning: '' },
  KE: { authority: 'National Employment Authority', url: 'https://nea.go.ke/', steps: ['Registered private employment agency', 'Attestation of contract', 'Pre-departure training'], fees: 'Regulated', warning: '' },
  UZ: { authority: 'Agency for External Labour Migration', url: 'https://migration.uz/', steps: ['Registration', 'Government-to-government programmes (Korea EPS, Russia, Gulf)'], fees: 'Regulated', warning: '' },
  EG: { authority: 'Ministry of Manpower', url: 'https://www.manpower.gov.eg/', steps: ['Contract approval by the ministry', 'Licensed office'], fees: 'Regulated', warning: '' }
};
function rules(origin) { const e = E[String(origin || '').toUpperCase()]; return e || { authority: 'Your country\'s emigration or foreign-employment authority', url: null, steps: ['Check whether your country requires emigration clearance or a labour permit before departure', 'Use only licensed recruiters', 'Take out the insurance your authority requires'], fees: 'Regulated by your country', warning: '' }; }
module.exports = { rules, E };
