// lib/faq_seed.js — the first FAQ set that the responders answer from (admin edits and extends in Admin → Content).
const F = (id, audience, question, answer) => ({ id, audience, question, answer, source: 'seed' });
const FAQS = [
  F('11111111-1111-4111-8111-000000000001', 'applicant', 'Is searching free?', 'Yes. Searching, matching and previews are free: 10 full searches on a free account, 3 a day, with 5 previews each. You pay only when you choose positions and the platform prepares and sends the applications.'),
  F('11111111-1111-4111-8111-000000000002', 'applicant', 'Do I need to send original documents?', 'No. ForiForeign never asks for originals. Upload clear scans or photos of your attested copies. Only the university, employer or immigration authority you apply to may ask for originals, and they will tell you when.'),
  F('11111111-1111-4111-8111-000000000003', 'applicant', 'Does ForiForeign apply for the visa for me?', 'The platform runs the visa desk for you: it tells you the documents the route needs, pre-fills the forms, records the appointment and submission, tracks the status and reads the decision when it arrives in your mailbox. You submit in your own name, or a licensed registered agent does where the law requires one.'),
  F('11111111-1111-4111-8111-000000000004', 'applicant', 'What is my forimail address?', 'It is your own email address on the ForiForeign mail service. Use it on every application; every reply lands in your Mail tab and is read for you within a minute. You can copy mail to your personal address, pause reading, export or close it any time.'),
  F('11111111-1111-4111-8111-000000000005', 'applicant', 'Can I get a refund?', 'Unused case credits are refundable within 14 days by the original payment method. Prepared cases and add-ons already used are not refundable. Write to admin@foriforeign.com with your payment reference.'),
  F('11111111-1111-4111-8111-000000000006', 'applicant', 'Which countries and professions are covered?', '54 destinations in both study and work lanes, with sourced visa rules, employer and applicant permit tracks, licence rules for 39 profession groups, and attestation routes for applicants from any country.'),
  F('11111111-1111-4111-8111-000000000007', 'applicant', 'Is the information legal advice?', 'No. Every rule is drawn from an official source shown next to it and verified by our team; it is information, not advice. Where a licensed adviser is needed, the platform says so.'),
  F('11111111-1111-4111-8111-000000000008', 'agency', 'How do agency plans work?', 'Starter ($79), Professional ($179) and Business ($399) a month buy the platform, staff seats and branches. Applications and searches are not capped by ForiForeign: the consultancy connects its own AI account (Google Gemini and Anthropic) once, and its provider bills it directly for AI usage. Annual plans cost 10 months.'),
  F('11111111-1111-4111-8111-000000000009', 'agency', 'Can my consultants see each other\'s clients?', 'Only as you decide. Owners see everything, managers their branch and sub-branches, consultants their branch, sub-agents only their own clients and leads. This is enforced on the server, and you can run the isolation check yourself.'),
  F('11111111-1111-4111-8111-000000000010', 'partner', 'What does a university pay?', 'Nothing to open a workspace or to receive applications. A success fee applies only after a student enrols, under a signed MOU, typically 10 to 20 percent of first-year tuition or a fixed fee per enrolment.'),
  F('11111111-1111-4111-8111-000000000011', 'partner', 'Do partner openings rank higher?', 'No. Partner openings go through the same eligibility and scoring as every other position and are labelled Partner. Paid visibility exists only in a separate, labelled spotlight rail.'),
  F('11111111-1111-4111-8111-000000000012', 'all', 'How is my data protected?', 'Identifiers are encrypted, documents are stored privately, every consent is recorded with its wording and date, organisations cannot see each other, and you can export or delete your data from your profile.')
];
module.exports = { FAQS };
