// lib/language_guide.js — the language a route really needs, per destination and lane, with the test names, the level,
// where to book, and what the platform prepares. Labour and care routes carry their own tests (EPS-TOPIK, JLPT/JFT-Basic,
// German A2/B1 for care, English B1 for UK care). Sourced; verify at the test bodies' pages.
const G = {
  GB: { study: ['IELTS/SELT B2 for degree (institution decides); Student visa needs B2 at degree level, B1 below', 'https://www.gov.uk/student-visa/knowledge-of-english'], work: ['Skilled Worker: English B1 (SELT, degree taught in English, or majority-English country)', 'https://www.gov.uk/skilled-worker-visa/knowledge-of-english'], labour: ['Health and Care Worker: B1 (SELT); Seasonal Worker: no test', 'https://www.gov.uk/health-care-worker-visa/knowledge-of-english'] },
  DE: { study: ['German B2/C1 (TestDaF, DSH) for German-taught; English B2 for English-taught', 'https://www.daad.de/en/study-and-research-in-germany/plan-your-studies/requirements/'], work: ['Blue Card: none required; most employers expect B1+; recognised professions may need B2', 'https://www.make-it-in-germany.com/en/living-in-germany/german-language'], labour: ['Care and nursing: B1/B2 German (Goethe, telc, ÖSD); Chancenkarte points for A2+; trucking often A2', 'https://www.make-it-in-germany.com/en/working-in-germany/professions-in-demand/nursing'] },
  KR: { study: ['TOPIK 3+ for Korean-taught; English for international programmes', 'https://www.topik.go.kr/'], work: ['E-7: employer decides; TOPIK helps for points', 'https://www.hikorea.go.kr/'], labour: ['EPS: EPS-TOPIK (reading and listening) plus skills test; run by HRD Korea through the origin agency', 'https://www.eps.go.kr/'] },
  JP: { study: ['JLPT N2 for Japanese-taught; English programmes exist', 'https://www.jlpt.jp/'], work: ['Engineer/Specialist: employer decides; N3+ common', 'https://www.moj.go.jp/isa/'], labour: ['SSW: JLPT N4 or JFT-Basic (A2) plus the sector skills test; nursing care adds the nursing-care Japanese test', 'https://www.ssw.go.jp/en/'] },
  AE: { study: ['English (IELTS 5.5–6.5) for most programmes', 'https://u.ae/'], work: ['No visa language test; employer decides', 'https://www.mohre.gov.ae/'], labour: ['No test; basic English or Arabic helps; safety induction in the employer\'s language', 'https://www.mohre.gov.ae/'] },
  SA: { study: ['Arabic for most public universities; English for KAUST and some programmes', 'https://www.moe.gov.sa/'], work: ['No visa test; health roles need Prometric/DataFlow, not a language test', 'https://www.qiwa.sa/'], labour: ['No test; basic Arabic helps', 'https://www.qiwa.sa/'] },
  CA: { study: ['IELTS 6.0–6.5 or equivalent (institution); French for Quebec', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada.html'], work: ['Express Entry: CLB 7+ (IELTS/CELPIP/TEF); work permit itself: employer decides', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-requirements.html'], labour: ['TFWP: employer decides; French helps in Quebec', 'https://www.canada.ca/en/employment-social-development/services/foreign-workers.html'] },
  AU: { study: ['IELTS 6.0 (student visa) and institution requirements', 'https://immi.homeaffairs.gov.au/'], work: ['Skills in Demand: IELTS 5.0 overall (Core Skills)', 'https://immi.homeaffairs.gov.au/'], labour: ['Same as work; aged care under labour agreements may accept lower levels', 'https://immi.homeaffairs.gov.au/'] },
  NZ: { study: ['IELTS 5.5–6.5 by level', 'https://www.immigration.govt.nz/'], work: ['AEWV: employer decides; residence pathways need IELTS 6.5', 'https://www.immigration.govt.nz/'], labour: ['AEWV: no test for the visa; sector agreements vary', 'https://www.immigration.govt.nz/'] },
  IE: { study: ['IELTS 6.0–6.5', 'https://www.irishimmigration.ie/'], work: ['Employment permit: no test; employer decides', 'https://enterprise.gov.ie/'], labour: ['General Employment Permit: no test; care roles often require English at work', 'https://enterprise.gov.ie/'] },
  IT: { study: ['Italian B2 for Italian-taught; English programmes exist', 'https://www.universitaly.it/'], work: ['Blue Card: none; integration agreement A2 within 2 years', 'https://www.interno.gov.it/'], labour: ['Decreto Flussi: none for the visa; A2 later for residence', 'https://integrazionemigranti.gov.it/'] },
  PL: { study: ['Polish B1/B2 or English by programme', 'https://study.gov.pl/'], work: ['None for the permit', 'https://www.gov.pl/web/udsc-en'], labour: ['None; Polish B1 for long-term residence later', 'https://www.gov.pl/web/udsc-en'] },
  RO: { study: ['Romanian preparatory year or English programmes', 'https://www.mae.ro/'], work: ['None', 'https://igi.mai.gov.ro/en/'], labour: ['None', 'https://igi.mai.gov.ro/en/'] },
  MY: { study: ['English (IELTS 5.5–6.0 by programme)', 'https://www.studymalaysia.com/'], work: ['None', 'https://esd.imi.gov.my/'], labour: ['None', 'https://www.imi.gov.my/'] },
  SG: { study: ['English by institution', 'https://www.ica.gov.sg/'], work: ['None for EP/S Pass', 'https://www.mom.gov.sg/'], labour: ['Work Permit: none; construction safety course in English/mother tongue', 'https://www.mom.gov.sg/'] },
  FR: { study: ['French B2 (DELF/TCF) for French-taught', 'https://www.campusfrance.org/en'], work: ['Talent passport: none; A2 for long-term card later', 'https://france-visas.gouv.fr/'], labour: ['None for the visa', 'https://france-visas.gouv.fr/'] },
  NL: { study: ['IELTS 6.0–6.5', 'https://www.studyinnl.org/'], work: ['None for highly skilled migrant', 'https://ind.nl/'], labour: ['None', 'https://ind.nl/'] },
  US: { study: ['TOEFL/IELTS by institution', 'https://educationusa.state.gov/'], work: ['None for the visa; employer decides', 'https://www.uscis.gov/'], labour: ['H-2: none', 'https://www.uscis.gov/'] },
  TR: { study: ['Turkish B2 (TÖMER) or English programmes; Türkiye Bursları includes a Turkish year', 'https://www.turkiyeburslari.gov.tr/'], work: ['None', 'https://www.csgb.gov.tr/'], labour: ['None', 'https://www.csgb.gov.tr/'] }
};
function guide(cc, lane) { const c = G[String(cc || '').toUpperCase()]; const l = (lane === 'labour' || lane === 'care') ? 'labour' : lane === 'work' ? 'work' : 'study'; if (!c) return { text: 'Check the programme or employer requirement; the visa itself rarely tests language for this route. The platform prepares an English or destination-language CV and letters as the posting requires.', source_url: (require('./visa_portals').PORTALS[String(cc || '').toUpperCase()] || [''])[0] }; const [text, url] = c[l] || c.work; return { text, source_url: url, prepares: 'The platform writes your documents in the language the posting uses, flags the test you need and its booking page, and adds a language-practice plan to your journey when a test is required.' }; }
module.exports = { guide, G };
