// lib/mailer.js — Day 24 · transactional email for notifications, via Resend (RESEND_API_KEY) or any
// SMTP-compatible HTTP relay you configure later. No key: nothing is sent, nothing breaks.
/* TEST-ONLY provider simulation: FF_FAKE_MAIL=ok records sends in memory; FF_FAKE_MAIL=fail behaves like an outage. Never in production. */
const _fake = { mode: () => (process.env.NODE_ENV !== 'production' && process.env.FF_FAKE_MAIL) ? (global.__ffFakeMail || process.env.FF_FAKE_MAIL) : null, sent: [] };
function enabled() { const m = _fake.mode(); if (m) return true; return !!process.env.RESEND_API_KEY; }
async function send(to, subject, html, brand) {
  if (!enabled() || !to) return { sent: false, reason: 'mail off' };
  /* A consultancy's client receives mail in the consultancy's name with the consultancy's own reply-to; the platform's name never appears. */
  const dom = (process.env.APPLY_DOMAIN || 'forimail.com'); const from = brand && brand.name ? (brand.name.replace(/[<>"]/g, '') + ' <no-reply@' + dom + '>') : (process.env.MAIL_FROM || ('ForiForeign <no-reply@' + dom + '>')); const replyTo = brand && brand.reply_to ? brand.reply_to : (process.env.MAIL_REPLY_TO || 'admin@foriforeign.com');
  const ctl = new AbortController(); const tm = setTimeout(() => ctl.abort(), 10000);
  try {
    const r = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { authorization: 'Bearer ' + process.env.RESEND_API_KEY, 'content-type': 'application/json' }, body: JSON.stringify({ from, to: [to], reply_to: replyTo, subject: String(subject).slice(0, 200), html }), signal: ctl.signal });
    clearTimeout(tm); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error((d && d.message) || ('Resend ' + r.status)); return { sent: true, id: d.id };
  } catch (e) { clearTimeout(tm); return { sent: false, reason: String(e.message).slice(0, 120) }; }
}
/* Raw send for the application mailbox: from an address on our domain, with attachments, on the user's tap. */
async function sendRaw({ from, to, subject, html, text, replyTo, cc, attachments, headers }) {
  const fm = _fake.mode(); if (fm === 'fail') throw new Error('simulated provider outage'); if (fm === 'ok') { const id = 'fake-' + (_fake.sent.length + 1); _fake.sent.push({ id, from, to, subject, attachments: (attachments || []).length, headers }); return { sent: true, id }; }
  if (!enabled() || !to) return { sent: false, reason: 'mail off' };
  const ctl = new AbortController(); const tm = setTimeout(() => ctl.abort(), 20000);
  try {
    const r = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { authorization: 'Bearer ' + process.env.RESEND_API_KEY, 'content-type': 'application/json' }, body: JSON.stringify({ from, to: [to], cc: cc ? [cc] : undefined, reply_to: replyTo || undefined, subject: String(subject || '').slice(0, 200), html, text, attachments: attachments && attachments.length ? attachments : undefined, headers: headers || undefined }), signal: ctl.signal });
    clearTimeout(tm); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error((d && d.message) || ('Resend ' + r.status)); return { sent: true, id: d.id };
  } catch (e) { clearTimeout(tm); return { sent: false, reason: String(e.message).slice(0, 120) }; }
}
function wrap(title, body, link, brand) {
  const b = brand || null; const host = b && b.domain ? 'https://' + b.domain : 'https://foriforeign.com'; const url = link ? host + '/app?go=' + encodeURIComponent(link) : host + '/';
  if (b && b.name) return '<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#0E1F42;color:#EAF2FF;padding:24px;border-radius:12px"><div style="font:800 20px Georgia,serif;margin-bottom:12px;color:' + esc(b.color || '#00D4FF') + '">' + esc(b.name) + '</div><h2 style="font:700 18px Inter,Arial;margin:0 0 10px;color:#fff">' + esc(title) + '</h2><div style="font-size:14px;line-height:1.6;color:#D6E9FF;white-space:pre-wrap">' + esc(body) + '</div><p style="margin-top:18px"><a href="' + url + '" style="background:' + esc(b.color || '#F5B841') + ';color:#0E1F42;padding:10px 16px;border-radius:8px;text-decoration:none;font-weight:700">Open</a></p><p style="font-size:11px;color:#8FA9CE;margin-top:18px">Sent by ' + esc(b.name) + '. Turn email notifications off under Profile.</p></div>';
  return '<div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#0E1F42;color:#EAF2FF;padding:24px;border-radius:12px"><div style="font:800 20px Georgia,serif;margin-bottom:12px">Fori<span style="color:#00D4FF">Foreign</span></div><h2 style="margin:0 0 8px;font-size:17px">' + esc(title) + '</h2><p style="color:#B4CDF0;line-height:1.55">' + esc(body || '') + '</p><a href="' + url + '" style="display:inline-block;margin-top:12px;padding:10px 16px;background:#F5B841;color:#0E1F42;font-weight:800;border-radius:8px;text-decoration:none">Open ForiForeign</a><p style="color:#8FA9CE;font-size:11px;margin-top:20px">You receive this because notifications by email are on in your profile. Turn them off under Profile → Language and data.</p></div>';
}
function esc(s) { return String(s || '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])); }
async function brandFor(userId) { try { const { admin } = require('./supa'); const { data: cl } = await admin().from('clients').select('org_id').eq('user_id', userId).eq('status', 'active').limit(1); if (!cl || !cl[0]) return null; const { data: og } = await admin().from('organisations').select('name,kind,settings').eq('id', cl[0].org_id).maybeSingle(); if (!og || og.kind !== 'agency') return null; const { data: dm } = await admin().from('org_domains').select('domain').eq('org_id', cl[0].org_id).eq('status', 'active').limit(1); return { name: og.name, color: (og.settings || {}).brand_color || null, domain: dm && dm[0] ? dm[0].domain : null, reply_to: (og.settings || {}).contact_email || (og.settings || {}).email || null, phone: (og.settings || {}).phone || (og.settings || {}).whatsapp || null }; } catch (e) { return null; } }
/* DURABLE SEND (DISC-006). One idempotency key per message. Sent once, ever: a second call with the same key returns the first result.
   Provider off or failing → the message is queued in mail_outbox and retried with backoff by the outbox_flush job. */
async function sendDurable(msg) { const { admin } = require('./supa'); const crypto = require('crypto'); const key = msg.idempotencyKey || crypto.createHash('sha256').update([msg.userId || '', msg.applicationId || '', msg.to || '', msg.subject || '', String(msg.text || msg.html || '').slice(0, 4000)].join('|')).digest('hex');
  try { const { data: ex } = await admin().from('mail_outbox').select('id,status,provider_id').eq('idempotency_key', key).maybeSingle(); if (ex && ex.status === 'sent') return { sent: true, deduped: true, id: ex.provider_id, outbox_id: ex.id }; if (ex && ex.status === 'pending') return { sent: false, queued: true, outbox_id: ex.id, deduped: true }; } catch (e) {}
  const payload = { from: msg.from, to: msg.to, subject: msg.subject, html: msg.html, text: msg.text, replyTo: msg.replyTo, cc: msg.cc, headers: msg.headers, attachDocIds: msg.attachDocIds || [], case_message_id: msg.caseMessageId || null };
  let result = null, err = null; try { result = await sendRaw(Object.assign({}, payload, { attachments: msg.attachments || [] })); if (!result || !result.sent) err = (result && result.reason) || 'not sent'; } catch (e) { err = e.message; }
  if (!err) { try { await admin().from('mail_outbox').upsert({ idempotency_key: key, user_id: msg.userId || null, application_id: msg.applicationId || null, org_id: msg.orgId || null, kind: msg.kind || 'case', payload, status: 'sent', attempts: 1, provider_id: result.id || null, sent_at: new Date().toISOString() }, { onConflict: 'idempotency_key' }); } catch (e) {} return { sent: true, id: result.id, key }; }
  let outboxId = null; try { const { data: row } = await admin().from('mail_outbox').upsert({ idempotency_key: key, user_id: msg.userId || null, application_id: msg.applicationId || null, org_id: msg.orgId || null, kind: msg.kind || 'case', payload, status: 'pending', attempts: 1, last_error: String(err).slice(0, 300), next_attempt_at: new Date(Date.now() + 5 * 60000).toISOString() }, { onConflict: 'idempotency_key' }).select('id').single(); outboxId = row && row.id; } catch (e) {}
  return { sent: false, queued: !!outboxId, outbox_id: outboxId, reason: String(err), key }; }
/* Retry due messages. Backoff 5m, 15m, 45m, 2h, 6h, then every 12h; after 12 attempts → failed (the person is told). Attachments are re-read from the vault by id. */
async function flushOutbox(limit) { const { admin } = require('./supa'); const now = new Date().toISOString(); const { data: rows } = await admin().from('mail_outbox').select('*').eq('status', 'pending').lte('next_attempt_at', now).order('next_attempt_at').limit(limit || 50); let sent = 0, failed = 0, retried = 0; for (const r of (rows || [])) { const p = r.payload || {}; const attachments = []; try { const D = require('./docs'); for (const id of (p.attachDocIds || []).slice(0, 8)) { const { data: d } = await admin().from('documents').select('name,mime,storage_key,size_bytes').eq('id', id).maybeSingle(); if (!d || (d.size_bytes || 0) > 8 * 1024 * 1024) continue; const { data: f } = await admin().storage.from(D.BUCKET).download(d.storage_key); if (f) attachments.push({ filename: d.name, content: Buffer.from(await f.arrayBuffer()).toString('base64') }); } } catch (e) {}
    let ok = false, res = null, err = null; try { res = await sendRaw(Object.assign({}, p, { attachments })); ok = !!(res && res.sent); if (!ok) err = (res && res.reason) || 'not sent'; } catch (e) { err = e.message; }
    if (ok) { sent++; await admin().from('mail_outbox').update({ status: 'sent', provider_id: res.id || null, sent_at: new Date().toISOString(), attempts: (r.attempts || 0) + 1, last_error: null }).eq('id', r.id); if (p.case_message_id) { try { await admin().from('case_messages').update({ send_status: 'sent', provider_message_id: res.id || null }).eq('id', p.case_message_id); } catch (e) {} } continue; }
    const n = (r.attempts || 0) + 1; const mins = [5, 15, 45, 120, 360][n - 1] || 720; if (n >= 12) { failed++; await admin().from('mail_outbox').update({ status: 'failed', attempts: n, last_error: String(err).slice(0, 300) }).eq('id', r.id); if (p.case_message_id) { try { await admin().from('case_messages').update({ send_status: 'failed' }).eq('id', p.case_message_id); } catch (e) {} } try { if (r.user_id) await require('./notify').push(r.user_id, 'mail', 'A message could not be sent', 'We tried 12 times over two days. Open the case and press Send again, or copy the text and send it from your own email.', 'apps'); } catch (e) {} } else { retried++; await admin().from('mail_outbox').update({ attempts: n, last_error: String(err).slice(0, 300), next_attempt_at: new Date(Date.now() + mins * 60000).toISOString() }).eq('id', r.id); } }
  return { sent, retried, failed, due: (rows || []).length }; }
module.exports = { brandFor, enabled, send, sendRaw, wrap, sendDurable, flushOutbox, _fake };
