// lib/memdb.js — TEST-ONLY in-memory stand-in for the Supabase client (FF_MEMDB=1). Enough of the query builder to run the
// server's tenancy and authorisation code paths against seeded rows, so isolation can be PROVEN by tests instead of asserted.
// Refuses to load in production. Tokens are "test:<userId>:<email>".
if (process.env.NODE_ENV === 'production') throw new Error('memdb is test-only');
const crypto = require('crypto');
const T = {};          // table -> rows
const tbl = t => (T[t] = T[t] || []);
const uuid = () => crypto.randomUUID();
function parseOr(expr) { return String(expr).split(',').map(s => s.trim()).filter(Boolean).map(s => { const m = s.match(/^([a-z_]+)\.(eq|neq|in|is|ilike|gt|gte|lt|lte)\.(.*)$/); if (!m) return null; let v = m[3]; if (m[2] === 'in') v = v.replace(/^\(|\)$/g, '').split(',').map(x => x.trim().replace(/^"|"$/g, '')); return { col: m[1], op: m[2], v }; }).filter(Boolean); }
function test(row, f) { const x = row[f.col]; switch (f.op) { case 'eq': return String(x) === String(f.v); case 'neq': return String(x) !== String(f.v); case 'in': return (f.v || []).map(String).includes(String(x)); case 'is': return f.v === 'null' || f.v === null ? x == null : !!x === (f.v === 'true'); case 'not': return !(x == null); case 'ilike': { const re = new RegExp('^' + String(f.v).replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/%/g, '.*') + '$', 'i'); return re.test(String(x || '')); } case 'gt': return String(x) > String(f.v); case 'gte': return String(x) >= String(f.v); case 'lt': return String(x) < String(f.v); case 'lte': return String(x) <= String(f.v); case 'contains': return Array.isArray(x) && (f.v || []).every(v => x.includes(v)); case 'or': return f.v.some(g => test(row, g)); default: return true; } }
function splitCols(str) { const out = []; let depth = 0, cur = ''; for (const ch of String(str)) { if (ch === '(') depth++; if (ch === ')') depth--; if (ch === ',' && depth === 0) { out.push(cur.trim()); cur = ''; } else cur += ch; } if (cur.trim()) out.push(cur.trim()); return out; }
function pick(row, cols) { if (!cols || cols === '*') return Object.assign({}, row); const out = {}; for (const c of splitCols(cols)) { const m = c.match(/^([a-z_]+)\((.*)\)$/); if (m) { const rel = m[1]; const fk = row[rel === 'opportunities' ? 'opportunity_id' : rel.replace(/s$/, '') + '_id']; const r = tbl(rel).find(x => x.id === fk); out[rel] = r ? pick(r, m[2]) : null; } else if (c === '*') Object.assign(out, row); else out[c] = row[c]; } return out; }
class Q { constructor(t) { this.t = t; this.f = []; this.cols = '*'; this.o = null; this.lim = null; this.mode = 'select'; this.head = false; this.count = null; }
  select(c, opts) { this.cols = c || '*'; if (opts && opts.count) this.count = opts.count; if (opts && opts.head) this.head = true; if (this.mode === 'insert' || this.mode === 'update' || this.mode === 'upsert') this.retCols = c; return this; }
  eq(c, v) { this.f.push({ col: c, op: 'eq', v }); return this; } neq(c, v) { this.f.push({ col: c, op: 'neq', v }); return this; } in(c, v) { this.f.push({ col: c, op: 'in', v }); return this; } is(c, v) { this.f.push({ col: c, op: 'is', v }); return this; } not(c, op, v) { this.f.push({ col: c, op: 'not' }); return this; } ilike(c, v) { this.f.push({ col: c, op: 'ilike', v }); return this; } gt(c, v) { this.f.push({ col: c, op: 'gt', v }); return this; } gte(c, v) { this.f.push({ col: c, op: 'gte', v }); return this; } lt(c, v) { this.f.push({ col: c, op: 'lt', v }); return this; } lte(c, v) { this.f.push({ col: c, op: 'lte', v }); return this; } contains(c, v) { this.f.push({ col: c, op: 'contains', v }); return this; } or(expr) { this.f.push({ op: 'or', v: parseOr(expr) }); return this; } order(c, o) { this.o = { c, asc: !(o && o.ascending === false) }; return this; } limit(n) { this.lim = n; return this; } range(a, b) { this.lim = b - a + 1; return this; }
  maybeSingle() { this.single1 = 'maybe'; return this; } single() { this.single1 = 'one'; return this; }
  insert(rows) { this.mode = 'insert'; this.rows = Array.isArray(rows) ? rows : [rows]; return this; } upsert(rows, opts) { this.mode = 'upsert'; this.rows = Array.isArray(rows) ? rows : [rows]; this.conflict = (opts && opts.onConflict) || 'id'; return this; } update(p) { this.mode = 'update'; this.patch = p; return this; } delete() { this.mode = 'delete'; return this; }
  _run() { const rows = tbl(this.t); const match = r => this.f.every(f => test(r, f));
    if (this.mode === 'insert') { const out = this.rows.map(r => { const row = Object.assign({ id: uuid(), created_at: new Date().toISOString() }, r); rows.push(row); return row; }); return { data: this.single1 ? out[0] : out, error: null }; }
    if (this.mode === 'upsert') { const out = this.rows.map(r => { const k = this.conflict; const i = rows.findIndex(x => String(x[k]) === String(r[k])); if (i >= 0) { Object.assign(rows[i], r); return rows[i]; } const row = Object.assign({ id: uuid(), created_at: new Date().toISOString() }, r); rows.push(row); return row; }); return { data: this.single1 ? out[0] : out, error: null }; }
    if (this.mode === 'update') { const out = []; for (const r of rows) if (match(r)) { Object.assign(r, this.patch); out.push(r); } return { data: this.single1 ? (out[0] || null) : out, error: null, count: out.length }; }
    if (this.mode === 'delete') { const keep = rows.filter(r => !match(r)); const n = rows.length - keep.length; T[this.t] = keep; return { data: null, error: null, count: n }; }
    let out = rows.filter(match); if (this.o) out = out.slice().sort((a, b) => { const x = String(a[this.o.c] ?? ''), y = String(b[this.o.c] ?? ''); return this.o.asc ? x.localeCompare(y) : y.localeCompare(x); }); const total = out.length; if (this.lim != null) out = out.slice(0, this.lim); out = out.map(r => pick(r, this.cols));
    if (this.head) return { data: null, error: null, count: total }; if (this.single1 === 'one') return out.length ? { data: out[0], error: null } : { data: null, error: { message: 'no rows' } }; if (this.single1 === 'maybe') return { data: out[0] || null, error: null }; return { data: out, error: null, count: this.count ? total : null }; }
  then(res, rej) { try { return Promise.resolve(this._run()).then(res, rej); } catch (e) { if (process.env.FF_DEBUG_STACK === '1') console.error('[memdb] ' + this.t + ' ' + this.mode + ' :: ' + String(e.stack).split('\n').slice(0, 6).join(' | ')); return Promise.resolve({ data: null, error: { message: e.message } }).then(res, rej); } }
}
const _files = new Map();
const client_auth = { getUser: async token => { const m = String(token || '').match(/^test:([^:]+):(.+)$/); if (!m) return { data: { user: null }, error: { message: 'bad token' } }; return { data: { user: { id: m[1], email: m[2] } }, error: null }; }, admin: { createUser: async () => ({ data: { user: { id: uuid() } }, error: null }), deleteUser: async () => ({ error: null }) } };
const client_storage_from = () => ({ download: async key => { const b = _files.get(key); return b ? { data: { arrayBuffer: async () => b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) }, error: null } : { data: null, error: { message: 'not found' } }; }, upload: async (key, buf) => { _files.set(key, Buffer.isBuffer(buf) ? buf : Buffer.from(buf)); return { data: { path: key }, error: null }; }, createSignedUrl: async () => ({ data: { signedUrl: 'https://memdb.local/signed' }, error: null }), remove: async () => ({ error: null }), list: async () => ({ data: [], error: null }) });
const client = { from: t => new Q(t), rpc: async () => ({ data: null, error: { message: 'memdb: no rpc' } }), auth: client_auth, storage: { from: client_storage_from } };
module.exports = { client, T, tbl, seed: rows => { for (const [t, list] of Object.entries(rows)) for (const r of list) tbl(t).push(Object.assign({ id: uuid(), created_at: new Date().toISOString() }, r)); }, reset: () => { for (const k of Object.keys(T)) delete T[k]; } };
