// lib/occupations.js — Day 17 · occupation classification (ISCO-08 major/sub-major groups) from a
// job title or profession, used for shortage-list intelligence and cleaner work-lane matching.
const MAP = [
  [/pharmac/i, '2262', 'Pharmacists'], [/physician|doctor|mbbs|medical officer|surgeon|gp\b/i, '221', 'Medical doctors'], [/nurse|nursing/i, '2221', 'Nursing professionals'], [/dentist/i, '2261', 'Dentists'], [/physio/i, '2264', 'Physiotherapists'], [/lab(oratory)? (tech|scientist)|medical technologist|biomedical scientist/i, '3212', 'Medical and pathology laboratory technicians'],
  [/software|developer|programmer|full[- ]stack|backend|frontend/i, '2512', 'Software developers'], [/data (scientist|analyst|engineer)|machine learning|ai engineer/i, '2511', 'Systems analysts / data'], [/network|system admin|devops|cloud/i, '2522', 'Systems administrators'], [/cyber|security analyst/i, '2529', 'ICT security'],
  [/civil engineer/i, '2142', 'Civil engineers'], [/mechanical engineer/i, '2144', 'Mechanical engineers'], [/electrical engineer/i, '2151', 'Electrical engineers'], [/electronic|telecom/i, '2153', 'Telecommunications engineers'], [/chemical engineer/i, '2145', 'Chemical engineers'], [/engineer/i, '214', 'Engineering professionals'],
  [/accountant|audit|cpa|acca/i, '2411', 'Accountants'], [/finance|financial analyst|banker/i, '241', 'Finance professionals'], [/marketing|brand/i, '2431', 'Advertising and marketing professionals'], [/sales/i, '243', 'Sales and marketing professionals'], [/hr\b|human resource|recruit/i, '2423', 'Personnel and careers professionals'], [/manager|director|head of/i, '12', 'Administrative and commercial managers'],
  [/teacher|lecturer|professor|academic|researcher|postdoc|scientist/i, '23', 'Teaching / research professionals'], [/biotech|molecular|microbiolog|biolog/i, '2131', 'Biologists, botanists, zoologists'], [/chemist/i, '2113', 'Chemists'], [/architect/i, '2161', 'Building architects'], [/lawyer|advocate|legal/i, '261', 'Legal professionals'],
  [/chef|cook/i, '3434', 'Chefs'], [/driver/i, '832', 'Car, van and motorcycle drivers'], [/electrician/i, '741', 'Electrical equipment installers'], [/welder|plumber|mason|carpenter|technician/i, '7', 'Craft and related trades'], [/care (worker|assistant)|caregiver/i, '5322', 'Home-based personal care workers']
];
function classify(title) { const t = String(title || ''); for (const [re, code, name] of MAP) if (re.test(t)) return { isco: code, name }; return { isco: null, name: null }; }
module.exports = { classify, MAP };
