// lib/offer_verify.js — "Confirm before you apply (or pay)". For a job offer, an employer or a posting, the platform
// checks what can be checked: the employer's domain and site, registry membership (UK sponsor register, our institution
// graph, feeds), whether the posting sits on the employer's own domain, the origin-side licensed-recruiter rule, and the
// fraud patterns that cost workers money (fees demanded from the worker, free-mail contacts, "visa guaranteed", urgency,
// payment before contract, mismatched company names). Returns a risk score with reasons and what to do next.
const dns = require('dns').promises; const { admin } = require('./supa');
const FRAUD = [[/(processing|visa|registration|medical|training|security) fee|pay (a )?fee|deposit (is )?required|send (money|payment)|western union|moneygram|bank transfer (before|to secure)/i, 'asks the worker to pay a fee or deposit', 30], [/visa (is )?guaranteed|guaranteed (visa|job|selection)|100% visa|no interview required/i, 'promises a guaranteed visa or job', 25], [/urgent(ly)?|within 24 hours|limited slots|last chance|act now/i, 'pressure and urgency', 10], [/@(gmail|yahoo|hotmail|outlook|proton)\./i, 'free-mail address for an employer', 15], [/whatsapp only|contact on whatsapp|telegram/i, 'contact only through messaging apps', 10], [/lottery|you have been selected without applying|congratulations you (are|have been) selected/i, 'unsolicited selection', 25],
  [/send (your )?(original )?passport|courier (your )?passport|passport (by )?courier|deposit (your )?passport/i, 'asks for the original passport before any contract', 30],
  [/(gmail|yahoo|hotmail|outlook|protonmail)\.com/i, 'free-mail domain named in the offer', 15],
  [/no interview|without (an )?interview|direct (visa|selection|joining)|join(ing)? (in|within) \d+ days/i, 'no interview or unrealistic joining time', 20],
  [/(agent|consultant|sub-?agent) (fee|charges|commission) (payable|to be paid) by (the )?(worker|candidate)/i, 'recruitment fee charged to the worker', 30],
  [/free visa/i, 'advertises a free visa, a common lure in unlicensed recruitment', 10], [/work permit fee|labour card fee|iqama fee (to be paid by|payable by) (the )?(worker|employee|candidate)/i, 'shifts employer-side permit costs to the worker', 20], [/(salary|pay).{0,40}(usd|\$|€|£)\s?(1[0-9]|[2-9][0-9])[,.]?\d{3}\s?(per|\/)\s?(month|mo)\b.*(cleaner|helper|labou?r|driver|packer)/i, 'unrealistic salary for the role', 15]];
async function verify({ text, url, employer, email, cc }) {
  const reasons = []; let risk = 0; const t = String(text || '');
  for (const [re, why, w] of FRAUD) if (re.test(t + ' ' + (email || ''))) { reasons.push({ signal: why, weight: w }); risk += w; }
  let host = ''; try { host = new URL(url || '').hostname.replace(/^www\./, ''); } catch (e) {} const mailDom = String(email || '').split('@')[1] || '';
  let domainOk = null, reach = null, registry = null, onOwnDomain = null, sponsor = null;
  for (const d of [host, mailDom].filter(Boolean)) { try { await dns.resolve(d); domainOk = true; } catch (e) { if (domainOk === null) domainOk = false; } }
  if (host) { try { const ctl = new AbortController(); const tm = setTimeout(() => ctl.abort(), 10000); const r = await fetch('https://' + host, { signal: ctl.signal, redirect: 'follow', headers: { 'user-agent': 'ForiForeign offer check' } }); clearTimeout(tm); reach = r.ok; } catch (e) { reach = false; } }
  if (host || mailDom) { try { const { data } = await admin().from('institutions').select('name,verified,registry,careers_feed').or('domain.eq.' + (host || 'x') + ',domain.eq.' + (mailDom || 'x')).limit(1); registry = data && data[0] ? { name: data[0].name, verified: !!data[0].verified, registry: data[0].registry, feed: data[0].careers_feed } : null; } catch (e) {} }
  if (mailDom && host) onOwnDomain = mailDom === host || host.endsWith('.' + mailDom) || mailDom.endsWith('.' + host);
  if (String(cc || '').toUpperCase() === 'GB' && employer) { try { const S = require('./sponsors'); const r = await S.check(employer, 'GB').catch(() => null); sponsor = r ? !!r.found : null; } catch (e) {} }
  if (domainOk === false) { reasons.push({ signal: 'employer domain does not resolve', weight: 25 }); risk += 25; }
  if (mailDom && host && onOwnDomain === false && !/(gmail|yahoo|hotmail|outlook)\./.test(mailDom)) { reasons.push({ signal: 'contact email domain differs from the employer site', weight: 15 }); risk += 15; }
  if (registry && registry.verified) { reasons.push({ signal: 'employer verified in the registry graph (' + registry.name + ')', weight: -20 }); risk -= 20; }
  if (sponsor === true) { reasons.push({ signal: 'on the UK sponsor register', weight: -25 }); risk -= 25; } if (sponsor === false) { reasons.push({ signal: 'NOT on the UK sponsor register (cannot sponsor a Skilled Worker visa)', weight: 30 }); risk += 30; }
  risk = Math.max(0, Math.min(100, risk)); const level = risk >= 50 ? 'high' : risk >= 25 ? 'medium' : 'low';
  const origin = { PK: 'Check the employer/agent against the BEOE licence list (beoe.gov.pk) and file the offer with the Protector of Emigrants before paying anything.', IN: 'Use only eMigrate-registered recruiting agents (emigrate.gov.in); the employer must be registered on eMigrate for ECR countries.', BD: 'Use BMET/BOESL channels (bmet.gov.bd); verify the agency licence.', PH: 'Use DMW-licensed agencies (dmw.gov.ph); verify the job order.', NP: 'Use DoFE-licensed agencies; obtain the labour permit.', LK: 'Register the job with the SLBFE.' };
  return { risk, level, reasons, checks: { domain_resolves: domainOk, site_reachable: reach, in_registry: !!registry, registry, contact_on_own_domain: onOwnDomain, uk_sponsor_register: sponsor }, advice: [level === 'high' ? 'Do not pay anything and do not send your passport; treat this as a probable scam until the employer confirms through its official domain.' : level === 'medium' ? 'Confirm with the employer through the contact on its official website before paying or sending documents.' : 'No red flags found; still confirm the contract terms in writing and never pay recruitment fees where the law forbids them.', 'Real employers never ask the worker to pay for the visa, the work permit or a "processing fee" in the Gulf, the UK, Canada, the US, Korea (EPS) or Japan (SSW).'], origin_rule: origin };
}
module.exports = { verify, FRAUD };
