// lib/oppkey.js — ONE IDENTITY PER OPPORTUNITY (Phase 4, DISC-002). The same posting must not appear twice because of URL variants,
// tracking parameters, title punctuation, a different source, or a repeated import.
const crypto = require('crypto');
const TRACKING = /^(utm_|fbclid$|gclid$|msclkid$|mc_cid$|mc_eid$|ref$|source$|src$|campaign$|_hs|yclid$|igshid$|si$)/i;
function canonicalUrl(u) { try { const x = new URL(String(u || '').trim()); x.protocol = 'https:'; x.hostname = x.hostname.toLowerCase().replace(/^www\./, ''); x.hash = ''; x.username = ''; x.password = ''; if (x.port === '80' || x.port === '443') x.port = ''; const keep = []; for (const [k, v] of x.searchParams.entries()) if (!TRACKING.test(k)) keep.push([k, v]); keep.sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1])); x.search = keep.length ? '?' + keep.map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(v)).join('&') : ''; let path = x.pathname.replace(/\/{2,}/g, '/'); if (path.length > 1) path = path.replace(/\/+$/, ''); path = path.replace(/\/(index|default)\.(html?|php|aspx?)$/i, ''); x.pathname = path || '/'; return x.toString(); } catch (e) { return String(u || '').trim().toLowerCase(); } }
function normTitle(t) { return String(t || '').toLowerCase().replace(/[()\[\]]/g, ' ').replace(/\b(ref|reference|job id|vacancy|req|requisition)\b[:# ]*[a-z0-9-]+/g, ' ').replace(/[^a-z0-9]+/g, ' ').replace(/\b(the|a|an|of|for|and|at|in|to|with)\b/g, ' ').replace(/\s+/g, ' ').trim(); }
function normOrg(s) { return String(s || '').toLowerCase().replace(/\b(ltd|limited|plc|inc|llc|gmbh|the|university|of|hospital|nhs|trust|foundation)\b/g, ' ').replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim(); }
/* Identity = institution + title + country (+ level for study). Deadline and source are NOT part of it: a re-scrape with a new deadline updates the row instead of duplicating it. */
function fingerprintOf(it) { return crypto.createHash('sha1').update([normOrg(it.institution), normTitle(it.title), String(it.country_code || '').toUpperCase(), String(it.kind || '') === 'study' ? String(it.level || '') : ''].join('|')).digest('hex'); }
module.exports = { canonicalUrl, fingerprintOf, normTitle, normOrg };
