// lib/pathway.js — THE PATHWAY MANAGER. Free: discover pathways, a basic readiness band, stay connected, monthly pulse and policy
// alerts. Member: full score breakdown, gap analysis with how-to-close, document readiness against the PR checklist, a tailored
// action plan, weekly reassessment, priority alerts, application preparation when the time comes, human review on request.
// Never sold as an immigration service: it keeps the person's own pathway correct, current and moving, and connects a human
// when one is needed. Events are detected by comparing today's facts with the last snapshot; the person is told what changed
// and the best next move.
const { admin } = require('./supa');
const LEVEL = { matric: 1, intermediate: 2, diploma: 3, bachelors: 4, masters: 5, mphil: 5, phd: 6, postdoc: 6 };
function langLevelOf(tests) { const t = (Array.isArray(tests) ? tests : []).map(x => ({ test: String(x.test || '').toUpperCase(), score: parseFloat(x.score) })); const ielts = t.find(x => /IELTS/.test(x.test) && isFinite(x.score)); if (ielts) return ielts.score >= 7 ? 'C1' : ielts.score >= 5.5 ? 'B2' : ielts.score >= 4.5 ? 'B1' : 'A2'; const pte = t.find(x => /PTE/.test(x.test) && isFinite(x.score)); if (pte) return pte.score >= 76 ? 'C1' : pte.score >= 59 ? 'B2' : pte.score >= 43 ? 'B1' : 'A2'; if (t.some(x => /OET/.test(x.test))) return 'B2'; if (t.some(x => /TOPIK|JLPT|GOETHE|DELF|TELC|CELPIP|TOEFL|DUOLINGO/.test(x.test))) return 'B1'; return null; }
const NEED = { C1: 4, B2: 3, B1: 2, A2: 1, A1: 0 };
function needFrom(text) { const m = String(text || '').match(/\b(A1|A2|B1|B2|C1|C2)\b/i); if (m) return m[1].toUpperCase(); if (/ielts\s*6\.5|competent|7\b/i.test(text)) return 'B2'; if (/none/i.test(text)) return null; return 'B1'; }
/* Score 0–100 for a destination, from what the profile actually holds. Unknown facts count as gaps, never as passes. */
function score(profile, pathway, extras = {}) { const p = profile || {}; const w = pathway || {}; const parts = []; const gap = (key, title, how, effort, points, met) => parts.push({ key, title, how, effort, points, met });
  const lvl = LEVEL[String(p.degree_level || '').toLowerCase()] || 0; gap('education', 'Recognised qualification', lvl >= 4 ? 'Your ' + (p.degree || p.degree_level) + ' meets the usual bar' : 'Most routes expect at least a bachelor\'s; a diploma may fit labour and trade routes', lvl >= 4 ? 'done' : '2–4 years', 20, lvl >= 4);
  const yrs = Number(p.experience_years) || 0; gap('experience', 'Skilled work experience', yrs >= 3 ? yrs + ' years on record' : (yrs ? yrs + ' years; most points systems reward 3+' : 'No dated experience on your profile yet: add roles with start and end dates'), yrs >= 3 ? 'done' : (3 - yrs) + ' more years', 20, yrs >= 3);
  const have = langLevelOf(p.language_tests); const need = needFrom(w.language); const okLang = !need || (have && (NEED[have] || 0) >= (NEED[need] || 0)); gap('language', 'Language at the level the pathway needs' + (need ? ' (' + need + ')' : ''), okLang ? (need ? 'Your test meets ' + need : 'No language test required for residence') : (have ? 'You hold ' + have + '; the pathway asks ' + need + ': book the next test level' : 'No test on file: book ' + (/german/i.test(w.language || '') ? 'Goethe/telc' : /french/i.test(w.language || '') ? 'DELF/TCF' : 'IELTS or PTE') + ' and upload the result'), okLang ? 'done' : '2–6 months', 20, !!okLang);
  const age = p.date_of_birth ? Math.floor((Date.now() - new Date(p.date_of_birth)) / (365.25 * 86400000)) : null; gap('age', 'Age band for points', age == null ? 'Add your date of birth for an exact points read' : age <= 35 ? 'Full age points on most systems' : age <= 45 ? 'Reduced age points; experience and language matter more' : 'Age points low; employer-sponsored and residence-by-years routes fit better', age == null ? 'add' : 'n/a', 10, age != null && age <= 45);
  const st = extras.visa_status || null; gap('status', 'A visa or offer that leads to this route', st === 'granted' ? 'Visa granted: the residence clock can run' : extras.offer ? 'An offer on file: the visa step is next' : 'No offer or visa yet: the pathway begins with a job or a place', st === 'granted' ? 'done' : extras.offer ? 'next step' : 'search and apply', 20, st === 'granted' || !!extras.offer);
  const yrsPR = Number(w.years_to_pr) || 0; const days = extras.days_lived || 0; const resPct = yrsPR ? Math.min(1, days / (yrsPR * 365.25)) : (st === 'granted' ? 1 : 0); gap('residence', yrsPR ? 'Residence: ' + yrsPR + ' years' : 'Residence requirement', yrsPR ? (Math.round(resPct * 100) + '% of ' + yrsPR + ' years lived') : 'No fixed years on this route', yrsPR ? Math.max(0, Math.ceil(yrsPR - days / 365.25)) + ' more years' : 'n/a', 10, resPct >= 1);
  const total = Math.round(parts.reduce((a, x) => a + (x.met ? x.points : (x.key === 'residence' ? x.points * resPct : 0)), 0)); const band = total >= 90 ? 'Ready to plan' : total >= 70 ? 'Close' : total >= 40 ? 'Building' : 'Not yet'; const gaps = parts.filter(x => !x.met).sort((a, b) => b.points - a.points); return { score: total, band, parts, gaps }; }
/* Documents against the PR checklist held in the vault. */
async function documentReadiness(userId, cc) { const want = ['passport', 'degree', 'transcript', 'experience_letter', 'english_test', 'police_certificate', 'bank_statement', 'birth_certificate', 'marriage_certificate']; const { data: docs } = await admin().from('documents').select('doc_type,expires_on,extracted').eq('user_id', userId).limit(200); const have = new Set((docs || []).map(d => d.doc_type)); const soon = (docs || []).filter(d => d.expires_on && new Date(d.expires_on) < new Date(Date.now() + 180 * 86400000)).map(d => d.doc_type); return { ready: want.filter(w => have.has(w)), missing: want.filter(w => !have.has(w)), expiring: [...new Set(soon)] }; }
async function facts(userId) { const { data: p } = await admin().from('profiles').select('*').eq('id', userId).maybeSingle(); const cc = (p && (p.pathway_cc || (Array.isArray(p.target_countries) && p.target_countries[0]))) || null; const { data: w } = cc ? await admin().from('pr_pathways').select('*').eq('country_code', cc).maybeSingle() : { data: null }; const { data: vc } = await admin().from('visa_cases').select('status,country_code').eq('user_id', userId).order('updated_at', { ascending: false }).limit(1); const { count: offers } = await admin().from('offers').select('id', { count: 'exact', head: true }).eq('user_id', userId); const days = p && p.arrival_date ? Math.floor((Date.now() - new Date(p.arrival_date)) / 86400000) : 0; const docs = await documentReadiness(userId, cc); const s = score(p, w, { visa_status: vc && vc[0] ? vc[0].status : null, offer: (offers || 0) > 0, days_lived: days }); return { profile: p, cc, pathway: w, visa_status: vc && vc[0] ? vc[0].status : null, offers: offers || 0, days_lived: days, docs, score: s, snapshot: { cc, degree_level: p && p.degree_level, experience_years: Number(p && p.experience_years) || 0, lang: langLevelOf(p && p.language_tests), tests: (Array.isArray(p && p.language_tests) ? p.language_tests.length : 0), visa_status: vc && vc[0] ? vc[0].status : null, offers: offers || 0, docs_ready: docs.ready.length, expiring: docs.expiring, rule_changed_at: w && w.changed_at, score: s.score } }; }
/* Detect meaningful events since the last snapshot; write them; return them with the best next move. */
async function detect(userId, { notify = true } = {}) { const f = await facts(userId); const key = 'pr_snapshot:' + userId; const { data: prev } = await admin().from('app_settings').select('value').eq('key', key).maybeSingle(); const o = (prev && prev.value) || null; const n = f.snapshot; const ev = []; const push = (kind, title, detail, priority = 'normal') => ev.push({ kind, title, detail, priority });
  if (o) { if ((n.experience_years || 0) > (o.experience_years || 0) + 0.4) push('experience', 'New work experience on record', (o.experience_years || 0) + ' → ' + n.experience_years + ' years'); if (n.degree_level && n.degree_level !== o.degree_level && (LEVEL[n.degree_level] || 0) > (LEVEL[o.degree_level] || 0)) push('qualification', 'New qualification: ' + n.degree_level, 'Higher qualification changes your points and your routes'); if ((n.tests || 0) > (o.tests || 0) || (n.lang && n.lang !== o.lang && (NEED[n.lang] || 0) > (NEED[o.lang] || 0))) push('language', 'Language score improved', (o.lang || 'no test') + ' → ' + (n.lang || 'test added')); if (n.visa_status && n.visa_status !== o.visa_status) push('visa', 'Visa status changed: ' + n.visa_status, n.visa_status === 'granted' ? 'Your residence clock can start' : '', n.visa_status === 'granted' ? 'high' : 'normal'); if ((n.offers || 0) > (o.offers || 0)) push('eligibility', 'New offer on file', 'An offer opens the visa step of this pathway', 'high'); if ((n.expiring || []).some(x => !(o.expiring || []).includes(x))) push('document_expiry', 'A document expires within 6 months', (n.expiring || []).join(', '), 'high'); if (n.rule_changed_at && n.rule_changed_at !== o.rule_changed_at) push('rule_change', 'The official PR page for ' + n.cc + ' changed', 'The platform is re-verifying the pathway', 'high'); if ((n.score || 0) >= (o.score || 0) + 10) push('eligibility', 'Your readiness improved: ' + (o.score || 0) + ' → ' + n.score, f.score.band); if (n.cc && n.cc !== o.cc) push('eligibility', 'You are now tracking ' + n.cc, 'The pathway below is for ' + n.cc); }
  const top = f.score.gaps[0]; const next = top ? top.title + ' — ' + top.how : (f.pathway ? 'Keep the residence log and the absence rule; your next milestone is on the card' : 'Pick the destination you are aiming for');
  for (const e of ev) { await admin().from('pathway_events').insert({ user_id: userId, country_code: f.cc, kind: e.kind, title: e.title, detail: e.detail, score_before: o && o.score, score_after: n.score, next_move: next, priority: e.priority }).then(() => {}, () => {}); if (notify) { try { await require('./notify').push(userId, 'pathway', e.title, (e.detail ? e.detail + ' · ' : '') + 'Best next move: ' + next, 'profile'); } catch (x) {} } }
  await admin().from('app_settings').upsert({ key, value: n }); await admin().from('profiles').update({ pathway_last_check: new Date().toISOString() }).eq('id', userId).then(() => {}, () => {}); return { events: ev, next, facts: f }; }
/* Tailored action plan (member): ordered steps with effort, from the gaps and the documents. */
function plan(f) { const steps = []; for (const g of f.score.gaps) steps.push({ step: g.title, how: g.how, effort: g.effort, points: g.points }); for (const m of f.docs.missing.slice(0, 6)) steps.push({ step: 'Add document: ' + m.replace(/_/g, ' '), how: 'Upload to the vault; it is read and filed automatically', effort: 'minutes', points: 0 }); for (const x of f.docs.expiring) steps.push({ step: 'Renew: ' + x.replace(/_/g, ' '), how: 'Expires within 6 months; PR applications need validity', effort: '2–8 weeks', points: 0 }); if (f.pathway && f.pathway.absence_rule) steps.push({ step: 'Keep to the absence rule', how: f.pathway.absence_rule, effort: 'ongoing', points: 0 }); return steps.slice(0, 12); }
/* Sweeps: members weekly, everyone else monthly (a light pulse). */
async function sweep({ members }) { const since = new Date(Date.now() - (members ? 7 : 30) * 86400000).toISOString(); const { data: users } = await admin().from('profiles').select('id').eq('role', 'user').eq('pathway_connected', true).or('pathway_last_check.is.null,pathway_last_check.lt.' + since).limit(2000); let n = 0, ev = 0; for (const u of (users || [])) { let member = false; try { const { data: a } = await admin().from('user_addons').select('addon_key').eq('user_id', u.id).in('addon_key', ['pathway_month', 'pathway_year']).or('expires_at.is.null,expires_at.gte.' + new Date().toISOString()).limit(1); member = !!(a && a.length); } catch (e) {} if (members !== member) continue; try { const r = await detect(u.id); n++; ev += r.events.length; } catch (e) {} } return { checked: n, events: ev }; }
module.exports = { score, facts, detect, plan, documentReadiness, sweep, langLevelOf };
