// lib/professions.js — the profession registry seed: regulated professions and the licensing body per key
// destination, each with its official source. Seeded UNVERIFIED into the rules registry (rule_type 'licence',
// route_key '<cc>_licence_<profession>') and verified by the team. Used by the work lane to show licence reality.
const P = {
  pharmacist: { isco: '2262', GB: ['GPhC registration (Overseas Pharmacists Assessment Programme, OSPAP, then pre-registration)', 'https://www.pharmacyregulation.org/registration/pharmacists/overseas-pharmacists', 'GPhC'], IE: ['PSI registration (third-country route: qualification recognition + adaptation)', 'https://www.thepsi.ie/gns/registration.aspx', 'PSI'], AU: ['Pharmacy Board of Australia via AHPRA; APC skills assessment', 'https://www.pharmacyboard.gov.au/registration/overseas-pharmacists.aspx', 'Pharmacy Board of Australia'], CA: ['PEBC evaluating exam + qualifying exam, then provincial registration', 'https://www.pebc.ca/', 'PEBC'], AE: ['DHA (Dubai) / DOH (Abu Dhabi) / MOHAP licence via DataFlow + assessment', 'https://www.dha.gov.ae/', 'DHA'], SA: ['SCFHS classification (Mumaris Plus) via DataFlow + Prometric', 'https://scfhs.org.sa', 'SCFHS'], QA: ['DHP (MOPH) licence via DataFlow', 'https://dhp.moph.gov.qa', 'Qatar DHP'], DE: ['Approbation as Apotheker (state pharmacy authority) with German B2/C1', 'https://www.anerkennung-in-deutschland.de/en', 'Recognition in Germany'] },
  doctor: { isco: '221', GB: ['GMC registration (PLAB or acceptable postgraduate qualification) + English', 'https://www.gmc-uk.org/registration-and-licensing', 'GMC'], IE: ['Medical Council registration (PRES exams for non-EU)', 'https://www.medicalcouncil.ie/', 'Medical Council of Ireland'], AU: ['AHPRA / Medical Board (AMC standard or competent authority pathway)', 'https://www.medicalboard.gov.au/', 'Medical Board of Australia'], CA: ['MCC (MCCQE) then provincial college licensure', 'https://mcc.ca/', 'Medical Council of Canada'], AE: ['DHA/DOH/MOHAP licence via DataFlow + assessment', 'https://www.dha.gov.ae/', 'DHA'], SA: ['SCFHS classification + Prometric', 'https://scfhs.org.sa', 'SCFHS'], QA: ['DHP licence via DataFlow', 'https://dhp.moph.gov.qa', 'Qatar DHP'], DE: ['Approbation (Ärztekammer / state authority), Fachsprachprüfung C1', 'https://www.anerkennung-in-deutschland.de/en', 'Recognition in Germany'], NZ: ['Medical Council of New Zealand registration (NZREX or recognised qualifications)', 'https://www.mcnz.org.nz/', 'MCNZ'] },
  nurse: { isco: '2221', GB: ['NMC registration (CBT + OSCE, English)', 'https://www.nmc.org.uk/registration/joining-the-register/register-nurse-midwife/trained-outside-the-uk/', 'NMC'], IE: ['NMBI registration (adaptation/aptitude test)', 'https://www.nmbi.ie/Registration', 'NMBI'], AU: ['NMBA via AHPRA (OBA assessment)', 'https://www.nursingmidwiferyboard.gov.au/', 'NMBA'], CA: ['NNAS assessment then provincial college', 'https://www.nnas.ca/', 'NNAS'], AE: ['DHA/DOH/MOHAP via DataFlow + Prometric', 'https://www.dha.gov.ae/', 'DHA'], SA: ['SCFHS classification + Prometric', 'https://scfhs.org.sa', 'SCFHS'], QA: ['DHP licence via DataFlow', 'https://dhp.moph.gov.qa', 'Qatar DHP'], DE: ['Recognition by the state authority + B2 German', 'https://www.anerkennung-in-deutschland.de/en', 'Recognition in Germany'], NZ: ['Nursing Council of New Zealand (CAP course where required)', 'https://www.nursingcouncil.org.nz/', 'Nursing Council NZ'] },
  dentist: { isco: '2261', GB: ['GDC registration (ORE exam)', 'https://www.gdc-uk.org/registration', 'GDC'], AU: ['Dental Board via AHPRA (ADC assessment)', 'https://www.dentalboard.gov.au/', 'Dental Board of Australia'], CA: ['NDEB equivalency process', 'https://ndeb-bned.ca/', 'NDEB'], AE: ['DHA/DOH/MOHAP via DataFlow', 'https://www.dha.gov.ae/', 'DHA'], SA: ['SCFHS classification', 'https://scfhs.org.sa', 'SCFHS'] },
  physiotherapist: { isco: '2264', GB: ['HCPC registration (international route)', 'https://www.hcpc-uk.org/registration/getting-on-the-register/international-applications/', 'HCPC'], AU: ['Physiotherapy Board via AHPRA (APC assessment)', 'https://www.physiotherapyboard.gov.au/', 'Physiotherapy Board'], CA: ['CAPR credentialing + exam, then provincial college', 'https://alliancept.org/', 'CAPR'], AE: ['DHA/DOH/MOHAP via DataFlow', 'https://www.dha.gov.ae/', 'DHA'] },
  engineer: { isco: '214', GB: ['Not licensed; CEng via Engineering Council optional; visa route needs sponsor', 'https://www.engc.org.uk/', 'Engineering Council'], AU: ['Engineers Australia skills assessment for migration', 'https://www.engineersaustralia.org.au/', 'Engineers Australia'], CA: ['Provincial P.Eng licensure (Engineers Canada)', 'https://engineerscanada.ca/', 'Engineers Canada'], AE: ['Society of Engineers UAE membership for some roles', 'https://soe.ae/', 'Society of Engineers UAE'], SA: ['Saudi Council of Engineers registration', 'https://www.saudieng.sa/', 'Saudi Council of Engineers'], DE: ['Not licensed (except "Ingenieur" title rules); Blue Card needs degree recognition', 'https://www.anerkennung-in-deutschland.de/en', 'Recognition in Germany'] },
  teacher: { isco: '23', GB: ['QTS via apply-for-QTS (many countries eligible)', 'https://www.gov.uk/guidance/qualified-teacher-status-qts', 'GOV.UK - QTS'], AU: ['AITSL assessment + state registration', 'https://www.aitsl.edu.au/', 'AITSL'], AE: ['KHDA/ADEK/MOE teacher licence', 'https://www.moe.gov.ae/', 'UAE MOE'], IE: ['Teaching Council registration', 'https://www.teachingcouncil.ie/', 'Teaching Council'] },
  accountant: { isco: '2411', GB: ['Not licensed for employment; ACCA/ICAEW membership valued', 'https://www.accaglobal.com/', 'ACCA'], AU: ['CPA Australia / CA ANZ skills assessment for migration', 'https://www.cpaaustralia.com.au/', 'CPA Australia'], CA: ['CPA Canada provincial bodies for the designation', 'https://www.cpacanada.ca/', 'CPA Canada'] },
  software_developer: { isco: '2512', GB: ['Not licensed; Skilled Worker sponsorship', 'https://www.gov.uk/skilled-worker-visa', 'GOV.UK'], DE: ['Not licensed; Blue Card / IT specialist route (experience-based possible)', 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', 'Make it in Germany'], CA: ['Not licensed; Express Entry STEM category', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', 'IRCC'], AU: ['ACS skills assessment for migration', 'https://www.acs.org.au/', 'ACS'] },
  lawyer: { isco: '261', GB: ['SQE for solicitor qualification', 'https://www.sra.org.uk/become-solicitor/sqe/', 'SRA'], AU: ['State admitting authority assessment', 'https://www.lawcouncil.au/', 'Law Council'], CA: ['NCA assessment then provincial law society', 'https://nca.legal/', 'NCA'] },
  lab_technologist: { isco: '3212', GB: ['HCPC biomedical scientist registration', 'https://www.hcpc-uk.org/', 'HCPC'], AU: ['AIMS assessment', 'https://www.aims.org.au/', 'AIMS'], AE: ['DHA/DOH/MOHAP via DataFlow', 'https://www.dha.gov.ae/', 'DHA'], SA: ['SCFHS classification', 'https://scfhs.org.sa', 'SCFHS'] }
};
function rules() {
  const out = [];
  for (const [prof, m] of Object.entries(P)) for (const [cc, v] of Object.entries(m)) { if (cc === 'isco') continue; out.push({ country_code: cc, route_key: cc.toLowerCase() + '_licence_' + prof, route_name: 'Licence: ' + prof.replace(/_/g, ' ') + ' in ' + cc, lane: 'work', rule_type: 'licence', text: v[0], value: { profession: prof, isco: m.isco }, source_url: v[1], source_title: v[2] }); }
  return out;
}
module.exports = { P, rules };
