// lib/prospecting.js — the Marketing / Prospecting agent, lawful B2B outreach.
// Find → research (their own public pages) → propose (customised, on our letterhead, with a trial workspace) → send with a
// clear sender, an unsubscribe line and a daily cap → read replies → answer plain questions from the FAQ store → escalate
// interest to the admin for the MOU. Contacts come only from the organisation's own public pages (international office,
// admissions, HR); every email is the company writing to a company, never to a private person, and every opt-out is honoured.
const { admin } = require('./supa'); const { callAI } = require('./router'); const PDFDocument = require('pdfkit');
const J = async url => { const ctl = new AbortController(); const tm = setTimeout(() => ctl.abort(), 20000); try { const r = await fetch(url, { signal: ctl.signal, headers: { 'user-agent': 'Mozilla/5.0 ForiForeign partnerships (admin@foriforeign.com)' }, redirect: 'follow' }); clearTimeout(tm); if (!r.ok) throw new Error('HTTP ' + r.status); return await r.text(); } catch (e) { clearTimeout(tm); throw e; } };
const strip = h => String(h || '').replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();
const EMAIL_RE = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi;
const ROLE_HINT = e => /international|admission|apply|study|global|intl|recruit|partnership|agent/.test(e) ? 'international/admissions' : /hr|career|jobs|talent|recruit/.test(e) ? 'HR' : /info|contact|enquir|inquir|office/.test(e) ? 'general' : 'other';
/* Web discovery by city: consultancies, employers and institutions that are not yet in the graph, found through a
   grounded web search and stored with their website so research() can read their own pages. */
async function discover({ kind, country_code, city, limit }) {
  const what = kind === 'agency' ? 'study abroad / immigration consultancies and education agents' : kind === 'employer' ? 'employers and hospitals or companies that hire international staff' : 'universities and colleges that admit international students';
  let out = []; try { const txt = await callAI('search_verify', `List ${limit || 15} real ${what} in ${city ? city + ', ' : ''}${country_code || ''}. Only organisations with an official website. Answer ONLY JSON: [{"name":"","website":"https://...","city":"","note":"one line on what they do"}]`, { search: true, urls: true, maxTokens: 1800, json: true }); const m = String(txt).match(/\[[\s\S]*\]/); if (m) out = JSON.parse(m[0]); } catch (e) {}
  let n = 0; for (const o of out) { if (!o.name || !/^https?:\/\//.test(String(o.website || ''))) continue; const domain = String(o.website).replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0]; const { error } = await admin().from('prospects').upsert({ kind: kind || 'agency', name: String(o.name).slice(0, 200), country_code: String(country_code || '').toUpperCase() || null, city: o.city || city || null, website: o.website, domain, research: { note: o.note || '' } }, { onConflict: 'kind,name,country_code', ignoreDuplicates: true }); if (!error) n++; }
  return { discovered: n, candidates: out.length };
}
async function find({ kind, country_code, city, limit }) {
  // Institutions already in the graph are the first prospects; the acquisition engine keeps adding to them.
  let q = admin().from('institutions').select('id,name,country_code,domain,website,kind,city,contact_email').limit(limit || 25); if (country_code) q = q.eq('country_code', String(country_code).toUpperCase()); if (city) q = q.ilike('city', '%' + city + '%'); if (kind === 'university') q = q.in('kind', ['university', 'college']); if (kind === 'employer') q = q.in('kind', ['employer', 'recruiter', 'hospital']);
  const { data } = await q; let n = 0; for (const i of (data || [])) { const { error } = await admin().from('prospects').upsert({ kind: kind || 'university', name: i.name, country_code: i.country_code, city: i.city || city || null, website: i.website || (i.domain ? 'https://' + i.domain : null), domain: i.domain, contacts: i.contact_email ? [{ email: i.contact_email, role: 'listed', source_url: i.website }] : [] }, { onConflict: 'kind,name,country_code', ignoreDuplicates: true }); if (!error) n++; } return { prospects: n };
}
async function research(prospectId) {
  const { data: p } = await admin().from('prospects').select('*').eq('id', prospectId).maybeSingle(); if (!p || !p.website) return null;
  const base = p.website.replace(/\/$/, ''); const pages = ['', '/international', '/admissions', '/international-students', '/study', '/contact', '/about', '/partners', '/agents', '/careers']; const found = new Map(); let text = '';
  for (const path of pages) { try { const html = await J(base + path); const t = strip(html); text += ' ' + t.slice(0, 4000); for (const m of (html.match(EMAIL_RE) || [])) { const e = m.toLowerCase(); if (/\.(png|jpg|gif|svg)$/.test(e) || /example|sentry|wixpress|noreply|no-reply/.test(e)) continue; if (!found.has(e)) found.set(e, { email: e, role: ROLE_HINT(e), source_url: base + path }); } } catch (e) {} }
  const contacts = [...found.values()].sort((a, b) => (a.role === 'international/admissions' ? -1 : 1) - (b.role === 'international/admissions' ? -1 : 1)).slice(0, 6);
  let r = {}; try { const txt = await callAI('high_value', `From this organisation's own public pages, write a short factual research note for a partnership proposal. Answer ONLY JSON: {"what_they_do":"2 sentences","international_intake":"what they say about international students or hiring from abroad, or 'not stated'","programmes_or_roles":["up to 6"],"pain_points":["3 likely operational pain points a study/work-mobility platform could solve for THEM, grounded in what the pages say"],"tone":"formal|warm|plain"}\nORGANISATION: ${p.name} (${p.country_code || ''})\nPAGES: ${text.slice(0, 12000)}`, { maxTokens: 700, json: true }); const m = String(txt).match(/\{[\s\S]*\}/); if (m) r = JSON.parse(m[0]); } catch (e) {}
  await admin().from('prospects').update({ contacts: contacts.length ? contacts : p.contacts, research: r, stage: 'researched', updated_at: new Date().toISOString() }).eq('id', p.id); return { contacts: contacts.length, research: r };
}
/* Letterhead PDF with a designed signature block and stamp: the platform's own stationery, never anyone else's. */
function letterheadPdf({ title, body, to, ref, signer, company, address, email, stamp }) {
  return new Promise((resolve, reject) => { const doc = new PDFDocument({ margin: 64 }); const ch = []; doc.on('data', c => ch.push(c)); doc.on('end', () => resolve(Buffer.concat(ch))); doc.on('error', reject);
    doc.rect(0, 0, 612, 64).fill('#0E1F42'); doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(22).text('Fori', 64, 22, { continued: true }).fillColor('#00D4FF').text('Foreign'); doc.fillColor('#B4CDF0').font('Helvetica').fontSize(8.5).text(company + ' · ' + address + ' · ' + email + ' · foriforeign.com', 64, 50);
    doc.moveDown(3); doc.fillColor('#0E1F42').font('Helvetica').fontSize(9.5).text('Ref ' + ref + ' · ' + new Date().toISOString().slice(0, 10), 64, 92); if (to) doc.text('To: ' + to, 64, 106); doc.moveDown(1.2); doc.font('Helvetica-Bold').fontSize(14).fillColor('#0E1F42').text(title, 64); doc.moveDown(0.8); doc.font('Helvetica').fontSize(10.5).fillColor('#1a1a1a').text(body, { lineGap: 3, align: 'justify', width: 484 });
    const y = Math.min(doc.y + 40, 690); doc.font('Helvetica').fontSize(10).fillColor('#0E1F42').text('Sincerely,', 64, y); doc.font('Helvetica-Oblique').fontSize(17).fillColor('#1B2C55').text(signer.split(',')[0], 64, y + 18); doc.font('Helvetica-Bold').fontSize(10).text(signer, 64, y + 44); doc.font('Helvetica').fontSize(9).fillColor('#444').text(company, 64, y + 58);
    // Stamp: a round seal with the company name and the reference, in the house colours.
    doc.save(); doc.circle(470, y + 40, 40).lineWidth(2).strokeColor('#2563EB').stroke(); doc.circle(470, y + 40, 34).lineWidth(1).strokeColor('#2563EB').stroke(); doc.fillColor('#2563EB').font('Helvetica-Bold').fontSize(7).text('FORIFOREIGN (PRIVATE) LIMITED', 428, y + 26, { width: 84, align: 'center' }); doc.fontSize(6.5).text('PARTNERSHIPS · ISLAMABAD', 428, y + 40, { width: 84, align: 'center' }); doc.fontSize(6).text(stamp || ref, 428, y + 52, { width: 84, align: 'center' }); doc.restore();
    doc.fontSize(7.5).fillColor('#777').text('This document was generated and digitally recorded on the ForiForeign platform. Verify: foriforeign.com/api/documents/verify', 64, 740, { width: 484, align: 'center' }); doc.end(); });
}
async function isProtected(p) { try { const name = String(p.name || '').toLowerCase(); const dom = String(p.domain || '').toLowerCase(); const { data: orgs } = await admin().from('organisations').select('name,kind,pilot').limit(2000); if ((orgs || []).some(o => String(o.name || '').toLowerCase() === name && !(o.pilot && o.kind !== 'agency'))) return 'already a platform customer'; const { data: inst } = await admin().from('institutions').select('partner_org_id').eq('domain', dom || '~').not('partner_org_id', 'is', null).limit(1); if (inst && inst.length) return 'a partner of a platform customer'; const { data: decl } = await admin().from('app_settings').select('value').eq('key', 'protected_partners').maybeSingle(); const list = (decl && decl.value && decl.value.names) || []; if (list.some(n => String(n).toLowerCase() === name || (dom && String(n).toLowerCase() === dom))) return 'declared by a consultancy as its own partner'; } catch (e) {} return null; }
async function propose(prospectId, adminId) {
  const { data: p } = await admin().from('prospects').select('*').eq('id', prospectId).maybeSingle(); if (!p) throw new Error('Prospect not found');
  const why = await isProtected(p); if (why) { await admin().from('prospects').update({ stage: 'declined', notes: 'Not approached: ' + why, updated_at: new Date().toISOString() }).eq('id', p.id); throw new Error('Not approached: ' + why); }
  const cfg = await require('./settings').getConfig(); const legal = cfg.legal || {}; const R = p.research || {}; const contact = (p.contacts || [])[0]; const trialDays = Number((cfg.prospecting || {}).trial_days) || 15;
  // Trial workspace: a real partner organisation pre-created in pilot mode with an invite link for their focal person.
  // Trial sized to the organisation: 15 days, with search and case limits that protect cost yet let them feel the value.
  const sizeTxt = JSON.stringify(R).toLowerCase(); const size = /(\b[5-9]\d{3,}|\b\d{2,3},\d{3}) (students|staff|employees)|university of|national/i.test(sizeTxt) ? 'large' : /(\b[5-9]\d{2}|\b[1-4],?\d{3}) (students|staff|employees|clients)/i.test(sizeTxt) ? 'medium' : 'small';
  const TRIAL = { small: { cases: 10, searches_day: 15, searches_month: 120 }, medium: { cases: 25, searches_day: 40, searches_month: 350 }, large: { cases: 50, searches_day: 80, searches_month: 700 } }[size];
  let trialOrgId = p.trial_org_id; if (!trialOrgId) { const { data: org } = await admin().from('organisations').insert({ name: p.name, kind: p.kind === 'agency' ? 'agency' : p.kind === 'employer' ? 'employer' : 'institution', country_code: p.country_code || null, owner_id: adminId, plan: 'trial', pilot: true, pilot_started_at: new Date().toISOString(), pilot_notes: 'Prospecting trial ' + trialDays + ' days (' + size + ': ' + TRIAL.cases + ' cases, ' + TRIAL.searches_day + ' searches/day)' }).select('id').single().then(r => r, () => ({ data: null })); if (org) { trialOrgId = org.id; if (contact) await admin().from('org_invites').insert({ org_id: trialOrgId, email: contact.email, role: 'owner', invited_by: adminId }).then(() => {}, () => {}); await admin().from('org_subscriptions').insert({ org_id: trialOrgId, tier_key: 'trial', tier_name: 'Trial (' + size + ')', usd_month: 0, cases_month: TRIAL.cases, cases_used: 0, searches_day: TRIAL.searches_day, searches_month: TRIAL.searches_month, status: 'active', period_start: new Date().toISOString(), period_end: new Date(Date.now() + trialDays * 86400000).toISOString(), billing_period: 'month' }).then(() => {}, () => {}); } }
  await admin().from('prospects').update({ research: Object.assign({}, R, { size, trial: TRIAL }) }).eq('id', p.id);
  const trialUntil = new Date(Date.now() + trialDays * 86400000).toISOString().slice(0, 10);
  // ROI, computed here so the letter quotes numbers we can defend: intake from their pages if stated, otherwise a stated range.
  const intakeMatch = String(JSON.stringify(R)).match(/(\d{2,5})\s*(international students|international|students from abroad)/i); const intake = intakeMatch ? Number(intakeMatch[1]) : null; const pct = Number((cfg.agency || {}).commission_pct_agency || 15);
  const roi = p.kind === 'university' ? { basis: intake ? 'their stated international intake of ' + intake : 'a typical intake range of 200 to 800 international students a year', extra_applications_low: Math.round((intake || 200) * 0.15), extra_applications_high: Math.round((intake || 800) * 0.4), eligible_share: '70 to 85 percent of files complete and eligible on arrival', cost_before_enrolment: 0, fee_model: pct + ' percent of first-year tuition, only after enrolment', staff_time_saved: '20 to 40 minutes per application in document chasing and pre-screening' } : p.kind === 'agency' ? { basis: 'a consultancy handling 30 to 300 clients a month', cases_per_consultant_before: '8 to 15 a week', cases_per_consultant_after: '40 to 80 a week', plan_cost_per_application: '1.00 to 1.49 USD', typical_client_fee: '150 to 600 USD', fee_model: 'monthly plan; clients get every feature included' } : { basis: 'an employer hiring 5 to 50 international staff a year', candidates: 'prepared, sponsorship-aware, licence-checked candidates', cost: 'free to receive; optional per-hire or spotlight fees', fee_model: 'no fee to receive candidates' };
  await admin().from('prospects').update({ roi }).eq('id', p.id);
  const brief = `Write a partnership proposal letter (350-450 words) from ForiForeign (Private) Limited to ${p.name}${p.country_code ? ' (' + p.country_code + ')' : ''}, addressed to ${contact ? contact.role : 'the international office'}. Use these facts about them: ${JSON.stringify(R).slice(0, 1500)}. What ForiForeign is: a platform where applicants from any country upload a CV, are matched to verified opportunities in 54 countries, and send complete, eligible applications in their own name; institutions receive prepared files, see identity only with the applicant's consent, and pay nothing until a student enrols. Offer: a ${trialDays}-day trial workspace already created for them (no fee, no card) with ${TRIAL.cases} prepared applications and ${TRIAL.searches_day} searches a day, sized for an organisation of their scale, a named focal person on each side, an 8-week pilot measured on applications received, eligible share, offers made and time to decision; then a success fee only on enrolment (${(cfg.agency || {}).commission_pct_agency || 15}% of first-year tuition, or a fixed fee per enrolment). Quantify the return for them in one paragraph using EXACTLY these figures (they were computed from their pages or from stated ranges; keep the wording 'range' where a range is given): ${JSON.stringify(roi)}. Make the benefit vivid and concrete without claiming anything outside these figures. Ask for a 30-minute call. Plain professional English, short paragraphs, specific, no long dashes, no stock phrases, no bullet lists, no exaggeration that cannot be backed. Sign as ${(cfg.prospecting || {}).signer || 'Dr Waseem Khalid, Director, Partnerships'}. Return only the letter text.`;
  let guidance = ''; try { const { data: g } = await admin().from('admin_guidance').select('text,applies_to').eq('active', true).or('expires_at.is.null,expires_at.gte.' + new Date().toISOString()).limit(10); guidance = (g || []).filter(x => (x.applies_to || []).some(a => ['all', 'prospecting'].includes(a))).map(x => x.text).join(' | '); } catch (e) {}
  let text = await callAI('case_writing', brief + (guidance ? '\nStanding guidance from the admin: ' + guidance : ''), { maxTokens: 1400 }); text = require('./partnerships').humanize(text);
  // Self-review: a second pass scores the letter and revises it once when it falls short. Quality is not optional.
  try { const rv = await callAI('high_value', `Score this partnership letter for a busy university or agency decision-maker. Answer ONLY JSON: {"clarity":0-10,"persuasion":0-10,"specificity":0-10,"honesty":0-10,"weakest":"one line","revise":true|false}. Revise=true if any score is below 8.\nLETTER: ${text.slice(0, 6000)}`, { maxTokens: 200, json: true }); const m = String(rv).match(/\{[\s\S]*\}/); const sc = m ? JSON.parse(m[0]) : null; if (sc && sc.revise) { const t2 = await callAI('case_writing', `Revise this letter so every quality is 8 or higher. Weakest point: ${sc.weakest}. Keep every fact exactly; keep the ROI figures exactly; same length; same recipient. Return only the revised letter.\nLETTER: ${text}`, { maxTokens: 1400 }); if (t2 && t2.length > 400) text = require('./partnerships').humanize(t2); } } catch (e) {}
  const ref = 'FF-' + p.id.slice(0, 6).toUpperCase(); const { data: doc } = await admin().from('official_documents').insert({ kind: 'partnership_proposal', title: 'Partnership proposal ' + p.name, counterparty_name: p.name, counterparty_email: contact ? contact.email : null, counterparty_focal: contact ? contact.role : null, our_focal: (cfg.prospecting || {}).signer || 'Dr Waseem Khalid, Director, Partnerships', body_text: text, variant: 'prospecting', status: 'approved', approved_by: adminId, approved_at: new Date().toISOString(), created_by: adminId, notes: 'Trial workspace ' + (trialOrgId || '-') + ' until ' + trialUntil, counterparty_org_id: trialOrgId || null }).select('id').single();
  await admin().from('prospects').update({ proposal_doc_id: doc && doc.id, trial_org_id: trialOrgId || null, trial_until: trialUntil, stage: 'proposed', updated_at: new Date().toISOString() }).eq('id', p.id);
  return { document_id: doc && doc.id, trial_org_id: trialOrgId, trial_until: trialUntil, contact: contact && contact.email };
}
async function send(prospectId, adminId) {
  const { data: p } = await admin().from('prospects').select('*').eq('id', prospectId).maybeSingle(); if (!p || !p.proposal_doc_id) throw new Error('Propose first');
  const { data: supAll } = await admin().from('suppression_list').select('email'); const blocked = new Set((supAll || []).map(x => x.email));
  const targets = (p.contacts || []).filter(c => c.email && !blocked.has(c.email)).slice(0, 3); const contact = targets[0]; if (!contact) throw new Error('No contactable address: none found on their public pages, or all opted out.');
  const cfg = await require('./settings').getConfig(); const capCfg = Number((cfg.prospecting || {}).daily_cap) || 40; const { data: first } = await admin().from('prospects').select('last_contact_at').not('last_contact_at', 'is', null).order('last_contact_at', { ascending: true }).limit(1); const warmDays = first && first[0] ? (Date.now() - new Date(first[0].last_contact_at).getTime()) / 86400000 : 0; const cap = Math.min(capCfg, Math.round(10 + (capCfg - 10) * Math.min(1, warmDays / 14))); const { count } = await admin().from('prospects').select('id', { count: 'exact', head: true }).gte('last_contact_at', new Date(Date.now() - 86400000).toISOString()); if ((count || 0) >= cap) throw new Error('Daily outreach cap reached (' + cap + ', warming up to ' + capCfg + '); tomorrow.');
  const PART = require('./partnerships'); const signed = await PART.sign(p.proposal_doc_id, adminId, (cfg.prospecting || {}).signer || 'Dr Waseem Khalid'); const legal = cfg.legal || {};
  const pdf = await letterheadPdf({ title: signed.title, body: signed.body_text, to: p.name, ref: 'FF-' + p.id.slice(0, 6).toUpperCase(), signer: (cfg.prospecting || {}).signer || 'Dr Waseem Khalid, Director, Partnerships', company: legal.company_name || 'ForiForeign (Private) Limited', address: legal.address || 'Islamabad, Pakistan', email: 'partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com'), stamp: signed.sha256 ? 'SHA ' + signed.sha256.slice(0, 10) : null });
  const M = require('./mailer'); if (!M.enabled()) throw new Error('Mail is not configured');
  const trialLine = p.trial_org_id ? `A ${(p.research && p.research.trial) ? p.research.trial.cases + '-application' : ''} trial workspace is ready for you until ${p.trial_until}: sign in at https://foriforeign.com with this address and it opens; no card, no fee.` : '';
  const intro = PART.humanize(`Dear ${contact.role === 'international/admissions' ? 'International Office' : 'Colleague'},\n\nI am writing from ForiForeign (Private) Limited about ${p.name}. The attached letter sets out a partnership in which you receive complete, eligible applications from applicants who consent to share their files, and pay only when a student enrols. ${trialLine}\n\nIf a 30-minute call suits you, reply with a time. If this is not relevant to your office, reply with the word "unsubscribe" and we will not write again.\n\nKind regards,\n${(cfg.prospecting || {}).signer || 'Dr Waseem Khalid'}\nForiForeign (Private) Limited, ${legal.address || 'Islamabad, Pakistan'}\nadmin@foriforeign.com`);
  const r = await M.sendRaw({ from: 'ForiForeign Partnerships <partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com') + '>', to: contact.email, cc: targets.slice(1).map(t => t.email).join(',') || undefined, subject: 'Partnership proposal for ' + p.name + ' (trial workspace included)', html: '<pre style="font-family:Arial,sans-serif;white-space:pre-wrap">' + intro.replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c])) + '</pre>', text: intro, replyTo: 'partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com'), attachments: [{ filename: 'ForiForeign_Proposal_' + p.name.replace(/[^a-z0-9]+/gi, '_') + '.pdf', content: pdf.toString('base64') }] });
  if (!r.sent) throw new Error('Send failed: ' + r.reason);
  await admin().from('official_documents').update({ status: 'sent', sent_at: new Date().toISOString() }).eq('id', p.proposal_doc_id); await admin().from('prospects').update({ last_contact_at: new Date().toISOString(), next_followup_at: new Date(Date.now() + 5 * 86400000).toISOString(), sent_to: targets.map(t => t.email), updated_at: new Date().toISOString() }).eq('id', p.id); await admin().from('audit_log').insert({ actor: adminId, event: 'PROSPECT_PROPOSAL_SENT', detail: p.name + ' -> ' + contact.email }).then(() => {}, () => {}); return { sent: true, to: contact.email };
}
/* Replies to partnerships@ land in the mailbox intake; this understands them, answers plain questions from the FAQ store, and escalates interest. */
async function handleReply({ from, subject, body }) {
  const email = String(from || '').toLowerCase().match(EMAIL_RE); const addr = email ? email[0] : ''; if (!addr) return { ignored: true };
  if (/unsubscribe|remove me|stop/i.test(String(subject) + ' ' + String(body).slice(0, 300))) { await admin().from('suppression_list').upsert({ email: addr, reason: 'reply' }); const { data: ps } = await admin().from('prospects').select('id,contacts'); for (const p of (ps || [])) if ((p.contacts || []).some(c => c.email === addr)) await admin().from('prospects').update({ stage: 'unsubscribed', updated_at: new Date().toISOString() }).eq('id', p.id); return { unsubscribed: addr }; }
  const dom = addr.split('@')[1]; const { data: ps } = await admin().from('prospects').select('*'); const p = (ps || []).find(x => (x.contacts || []).some(c => c.email === addr) || (x.domain && dom && (dom === x.domain || dom.endsWith('.' + x.domain)))); if (!p) return { ignored: 'unknown sender' };
  const { data: faqs } = await admin().from('faqs').select('question,answer').in('audience', ['partner', 'all']).limit(60);
  let v = { intent: 'other', reply: null, escalate: true };
  try { const txt = await callAI('high_value', `You handle replies to ForiForeign partnership proposals. Classify and, when the question is answered by the FAQ, draft the reply. Answer ONLY JSON: {"intent":"interested|question|not_now|declined|unsubscribe|other","reply":"a complete reply in plain English (no long dashes, no stock phrases) ONLY if intent is question and the FAQ answers it; otherwise null","escalate":true/false}\nFAQ: ${JSON.stringify(faqs || []).slice(0, 6000)}\nFROM: ${p.name}\nSUBJECT: ${subject}\nBODY: ${String(body).slice(0, 4000)}\nNever promise terms, prices or exclusivity; anything about money or contracts escalates.`, { maxTokens: 600, json: true }); const m = String(txt).match(/\{[\s\S]*\}/); if (m) v = Object.assign(v, JSON.parse(m[0])); } catch (e) {}
  const stage = v.intent === 'interested' ? 'replied' : v.intent === 'declined' ? 'declined' : v.intent === 'not_now' ? 'replied' : 'replied'; await admin().from('prospects').update({ stage, notes: ((p.notes || '') + '\n' + new Date().toISOString().slice(0, 10) + ' ' + v.intent + ': ' + String(body).slice(0, 300)).slice(-4000), next_followup_at: v.intent === 'not_now' ? new Date(Date.now() + 45 * 86400000).toISOString() : null, updated_at: new Date().toISOString() }).eq('id', p.id);
  if (v.reply && v.intent === 'question') { try { const M = require('./mailer'); await M.sendRaw({ from: 'ForiForeign Partnerships <partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com') + '>', to: addr, subject: 'Re: ' + subject, html: '<pre style="font-family:Arial,sans-serif;white-space:pre-wrap">' + require('./partnerships').humanize(v.reply).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c])) + '</pre>', text: v.reply, replyTo: 'partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com') }); } catch (e) {} }
  if (v.escalate !== false || v.intent === 'interested') { try { const { data: admins } = await admin().from('profiles').select('id').in('role', ['admin', 'super_admin']); for (const a of (admins || [])) await require('./notify').push(a.id, 'prospect', p.name + ': ' + v.intent, String(body).slice(0, 200), 'adminx'); } catch (e) {} }
  return { intent: v.intent, replied: !!v.reply, prospect_id: p.id };
}
/* Autopilot: when Settings → prospecting.auto is true, every day the agent discovers in the configured targets, researches,
   drafts and sends within the cap, sends one follow-up to silent prospects, and reports in the daily brief. */
async function autopilot(adminId) {
  const cfg = await require('./settings').getConfig(); const P = cfg.prospecting || {}; if (!P.auto) return { off: true };
  const Q = require('./queue'); const targets = Array.isArray(P.targets) && P.targets.length ? P.targets : [{ kind: 'university', country_code: 'GB' }, { kind: 'agency', country_code: 'PK', city: 'Lahore' }]; let found = 0;
  for (const t of targets.slice(0, 6)) { try { const d = await discover(Object.assign({ limit: 10 }, t)); found += d.discovered; const f = await find(Object.assign({ limit: 10 }, t)); found += f.prospects; } catch (e) {} }
  const { data: fresh } = await admin().from('prospects').select('id').eq('stage', 'found').limit(40); for (const p of (fresh || [])) await Q.enqueue('prospect_research', { prospectId: p.id }, { maxAttempts: 1 });
  const { data: ready } = await admin().from('prospects').select('id,contacts').eq('stage', 'researched').limit(30); let drafted = 0; for (const p of (ready || [])) if ((p.contacts || []).length) { await Q.enqueue('prospect_propose', { prospectId: p.id, adminId }, { maxAttempts: 1 }); drafted++; }
  const cap = Number(P.daily_cap) || 40; const { count } = await admin().from('prospects').select('id', { count: 'exact', head: true }).gte('last_contact_at', new Date(Date.now() - 86400000).toISOString()); const room = Math.max(0, cap - (count || 0));
  const { data: proposed } = await admin().from('prospects').select('id').eq('stage', 'proposed').is('last_contact_at', null).limit(room); let sent = 0; for (const p of (proposed || [])) { await Q.enqueue('prospect_send', { prospectId: p.id, adminId }, { maxAttempts: 1 }); sent++; }
  return { found, research_queued: (fresh || []).length, drafted, send_queued: sent, cap };
}
async function followups() { const { data } = await admin().from('prospects').select('*').eq('stage', 'proposed').lte('next_followup_at', new Date().toISOString()).lt('followups', 2).not('last_contact_at', 'is', null).limit(20); let n = 0; const M = require('./mailer'); const cfg = await require('./settings').getConfig();
  for (const p of (data || [])) { try { const to = (p.sent_to || [])[0]; if (to && M.enabled()) { const txt = require('./partnerships').humanize(`Dear colleague,\n\nA short follow-up on the partnership proposal I sent for ${p.name} on ${String(p.last_contact_at).slice(0, 10)}. The trial workspace remains open until ${p.trial_until || 'the end of the pilot period'}, at no cost. If a 30-minute call would help, reply with a time; if this is not for your office, reply "unsubscribe".\n\nKind regards,\n${(cfg.prospecting || {}).signer || 'Dr Waseem Khalid'}\nForiForeign (Private) Limited`); await M.sendRaw({ from: 'ForiForeign Partnerships <partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com') + '>', to, subject: 'Re: Partnership proposal for ' + p.name, html: '<pre style="font-family:Arial,sans-serif;white-space:pre-wrap">' + txt.replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c])) + '</pre>', text: txt, replyTo: 'partnerships@' + (process.env.APPLY_DOMAIN || 'forimail.com') }); } await admin().from('prospects').update({ followups: p.followups + 1, next_followup_at: new Date(Date.now() + 7 * 86400000).toISOString(), updated_at: new Date().toISOString() }).eq('id', p.id); n++; } catch (e) {} } return { followups_sent: n }; }
module.exports = { find, discover, research, propose, send, handleReply, followups, autopilot, letterheadPdf, isProtected };
