// lib/refs.js — reference numbers on everything that leaves the platform or must be traced: cases (FF-C-2026-000123),
// official documents (FF-D-…), proposals/MOUs (FF-M-…), visa files (FF-V-…), tickets (FF-T-…), payments (FF-P-…).
// A reference is printed on every letter and PDF, shown in the app, and searchable in one place (Admin → Search).
const { admin } = require('./supa');
const PREFIX = { application: 'C', official_document: 'D', mou: 'M', visa_case: 'V', support_ticket: 'T', payment: 'P', prospect: 'X' };
async function next(kind) { const p = PREFIX[kind] || 'R'; const y = new Date().getFullYear(); const key = 'refseq:' + p + ':' + y; let n = 1; try { const { data } = await admin().from('app_settings').select('value').eq('key', key).maybeSingle(); n = ((data && data.value && data.value.n) || 0) + 1; await admin().from('app_settings').upsert({ key, value: { n } }); } catch (e) { n = Date.now() % 1000000; } return 'FF-' + p + '-' + y + '-' + String(n).padStart(6, '0'); }
async function assign(table, id, kind) { try { const { data } = await admin().from(table).select('ref').eq('id', id).maybeSingle(); if (data && data.ref) return data.ref; const ref = await next(kind); await admin().from(table).update({ ref }).eq('id', id); return ref; } catch (e) { return null; } }
/* One search across the platform: refs, names, emails, titles. Scoped by role: platform admin sees all; others see their own. */
async function search(q, scope) { const s = String(q || '').trim().slice(0, 80); if (!s) return { hits: [] }; const like = '%' + s.replace(/[%,]/g, ' ') + '%'; const hits = []; const push = (kind, rows, fmt) => { for (const r of (rows || [])) hits.push(Object.assign({ kind }, fmt(r))); };
  const refMatch = /^FF-([A-Z])-\d{4}-\d{6}$/i.test(s);
  if (scope.admin) {
    const [a, d, v, t, p, u, x] = await Promise.all([admin().from('applications').select('id,ref,status,institution,created_at,user_id').or('ref.ilike.' + like + ',institution.ilike.' + like).limit(10).then(r => r.data), admin().from('official_documents').select('id,ref,title,status,counterparty_name,created_at').or('ref.ilike.' + like + ',title.ilike.' + like + ',counterparty_name.ilike.' + like).limit(10).then(r => r.data), admin().from('visa_cases').select('id,ref,country_code,status,user_id,created_at').or('ref.ilike.' + like + ',country_code.ilike.' + like).limit(10).then(r => r.data), admin().from('support_tickets').select('id,ref,subject,status,created_at').or('ref.ilike.' + like + ',subject.ilike.' + like).limit(10).then(r => r.data), admin().from('payments').select('id,ref,credits,status,created_at,user_id').or('ref.ilike.' + like + ',reference.ilike.' + like).limit(10).then(r => r.data), admin().from('profiles').select('id,full_name,email,apply_email,role,created_at').or('full_name.ilike.' + like + ',email.ilike.' + like + ',apply_email.ilike.' + like).limit(10).then(r => r.data), admin().from('prospects').select('id,name,stage,country_code').ilike('name', like).limit(10).then(r => r.data)]);
    push('case', a, r => ({ id: r.id, ref: r.ref, title: r.institution, status: r.status, when: r.created_at, link: 'adminx' })); push('document', d, r => ({ id: r.id, ref: r.ref, title: r.title + ' · ' + (r.counterparty_name || ''), status: r.status, when: r.created_at, link: 'adminx' })); push('visa', v, r => ({ id: r.id, ref: r.ref, title: 'Visa file ' + r.country_code, status: r.status, when: r.created_at, link: 'adminx' })); push('ticket', t, r => ({ id: r.id, ref: r.ref, title: r.subject, status: r.status, when: r.created_at, link: 'adminx' })); push('payment', p, r => ({ id: r.id, ref: r.ref, title: (r.credits || 0) + ' credits', status: r.status, when: r.created_at, link: 'adminx' })); push('person', u, r => ({ id: r.id, title: (r.full_name || '') + ' · ' + (r.email || '') + ' · ' + (r.apply_email || ''), status: r.role, when: r.created_at, link: 'adminx' })); push('prospect', x, r => ({ id: r.id, title: r.name + ' · ' + (r.country_code || ''), status: r.stage, link: 'adminx' }));
  } else { const uid = scope.userId; const [a, v, t] = await Promise.all([admin().from('applications').select('id,ref,status,institution,created_at').eq('user_id', uid).or('ref.ilike.' + like + ',institution.ilike.' + like).limit(10).then(r => r.data), admin().from('visa_cases').select('id,ref,country_code,status,created_at').eq('user_id', uid).or('ref.ilike.' + like + ',country_code.ilike.' + like).limit(10).then(r => r.data), admin().from('support_tickets').select('id,ref,subject,status,created_at').eq('user_id', uid).or('ref.ilike.' + like + ',subject.ilike.' + like).limit(10).then(r => r.data)]); push('case', a, r => ({ id: r.id, ref: r.ref, title: r.institution, status: r.status, when: r.created_at, link: 'apps' })); push('visa', v, r => ({ id: r.id, ref: r.ref, title: 'Visa file ' + r.country_code, status: r.status, when: r.created_at, link: 'profile' })); push('ticket', t, r => ({ id: r.id, ref: r.ref, title: r.subject, status: r.status, when: r.created_at, link: 'home' })); }
  return { q: s, ref_lookup: refMatch, hits: hits.slice(0, 40) };
}
module.exports = { next, assign, search, PREFIX };
