// lib/requirements.js — "What this needs from you": for one opportunity and one person, read the posting's own
// requirements, add the destination's rules (visa route, licence for the profession, work rights), the origin's
// attestation route, and the person's vault, and return a checklist of concrete items with status and source. Cached per
// opportunity × person for 7 days; recomputed when the rules change (Policy Watch) or the vault changes.
const { admin } = require('./supa'); const { callAI } = require('./router');
async function brief(userId, oppId) {
  let cacheKey = 'reqbrief:' + userId + ':' + oppId; try { const { data: c } = await admin().from('app_settings').select('value').eq('key', cacheKey).maybeSingle(); if (c && c.value && c.value.at && Date.now() - new Date(c.value.at).getTime() < 7 * 86400000) return c.value; } catch (e) {}
  const [{ data: o }, { data: p }] = await Promise.all([admin().from('opportunities').select('id,title,institution,country_code,kind,level,description,requirements,url,deadline,visa_sponsorship,req_field,req_degree,req_experience_years,req_language').eq('id', oppId).maybeSingle(), admin().from('profiles').select('full_name,origin_country,field,profession,degree,total_experience_years,mobility').eq('id', userId).maybeSingle()]);
  if (!o) throw new Error('Opportunity not found'); const cc = o.country_code; cacheKey = 'reqbrief:' + cc + ':' + userId + ':' + oppId; const lane = o.kind === 'work' ? 'work' : 'study';
  const { data: rules } = await admin().from('visa_rules').select('rule_type,text,source_url,source_title,status,value,route_name').eq('country_code', cc).neq('status', 'superseded').limit(80);
  const R = rules || []; const prof = (p && (p.profession || p.field) || '').toLowerCase(); const licence = R.filter(r => r.rule_type === 'licence' && String((r.value || {}).profession || '').replace(/_/g, ' ').includes(prof.split(' ')[0] || '~')).slice(0, 2);
  const route = R.filter(r => (lane === 'work' ? /work|skilled|employ|permit|blue|482|h1b/i.test(r.route_name || '') : /student|study|d-2|f-1|x1/i.test(r.route_name || '')) && ['eligibility', 'financial', 'language', 'work_rights', 'fee', 'dependants'].includes(r.rule_type)).slice(0, 8);
  let attest = null; try { attest = require('./attestation').rulesFor((p && p.origin_country) || 'PK', cc)[0]; } catch (e) {}
  let vault = []; try { vault = await require('./vault').list(userId); } catch (e) {}
  const have = (vault || []).map(v => ({ type: v.doc_type || v.kind, status: v.doc_status, expiry: v.expiry_date, attestation: v.attestation_status }));
  let v = { items: [], summary: '' };
  try { const txt = await callAI('high_value', `Build the requirements checklist for THIS person applying to THIS opportunity. Answer ONLY JSON: {"summary":"2 sentences: overall readiness and the one thing to do first","items":[{"item":"concrete requirement","source":"posting|destination rule|origin attestation|licence|profile","status":"met|missing|unclear|expiring","action":"what the person does now, one line","source_url":"url or null"}]}. Rules: use ONLY the facts given; never invent thresholds; if the posting states a figure quote it; mark 'unclear' when the source does not say. Max 14 items, most important first.\nOPPORTUNITY: ${JSON.stringify({ title: o.title, institution: o.institution, country: cc, kind: o.kind, level: o.level, deadline: o.deadline, sponsorship: o.visa_sponsorship, req: o.requirements, req_field: o.req_field, req_degree: o.req_degree, req_experience_years: o.req_experience_years, req_language: o.req_language, url: o.url, description: String(o.description || '').slice(0, 3500) })}\nDESTINATION RULES: ${JSON.stringify(route.map(r => ({ type: r.rule_type, text: r.text, source: r.source_url, status: r.status })))}\nLICENCE RULES: ${JSON.stringify(licence.map(r => ({ text: r.text, source: r.source_url })))}\nORIGIN ATTESTATION: ${JSON.stringify(attest ? { route: (attest.value || {}).route, text: attest.text, source: attest.source_url } : null)}\nPERSON: ${JSON.stringify({ origin: p && p.origin_country, field: p && p.field, profession: p && p.profession, degree: p && p.degree, experience_years: p && p.total_experience_years })}\nVAULT: ${JSON.stringify(have).slice(0, 2000)}`, { maxTokens: 1400, json: true, userId }); const m = String(txt).match(/\{[\s\S]*\}/); if (m) v = Object.assign(v, JSON.parse(m[0])); } catch (e) { v.summary = 'Checklist unavailable right now; the destination rules and the posting are listed for you to read.'; }
  const out = { at: new Date().toISOString(), opportunity_id: oppId, summary: require('./partnerships').humanize(v.summary || ''), items: (v.items || []).slice(0, 14), rules_status: { verified: route.filter(r => r.status === 'verified').length, to_verify: route.filter(r => r.status !== 'verified').length }, attestation: attest ? { route: (attest.value || {}).route, source_url: attest.source_url } : null };
  try { await admin().from('app_settings').upsert({ key: cacheKey, value: out }); } catch (e) {} return out;
}
module.exports = { brief };
