// lib/scholarships_seed.js — the major scholarship programmes open to international applicants, one registry with official
// pages, levels, funding and the usual application window. Ingested as verified-source opportunities that recur every
// year; the freshness sweep and Policy Watch keep the pages current. Deadlines are windows, not dates: the exact date is
// read from the page at verification and shown with its source.
const S = (cc, name, url, levels, funding, window, note) => ({ cc, name, url, levels, funding, window, note });
const SCHOLARSHIPS = [
  S('GB', 'Chevening Scholarships', 'https://www.chevening.org/scholarships/', ['masters'], 'fully', 'Aug–Nov', 'One-year master\'s; leadership; 160+ countries; return home 2 years'),
  S('GB', 'Commonwealth Scholarships (CSC)', 'https://cscuk.fcdo.gov.uk/scholarships/', ['masters', 'phd'], 'fully', 'Sep–Dec', 'Commonwealth citizens; development themes'),
  S('GB', 'Gates Cambridge Scholarship', 'https://www.gatescambridge.org/', ['masters', 'phd'], 'fully', 'Sep–Jan', 'Non-UK citizens; Cambridge'),
  S('GB', 'Rhodes Scholarship', 'https://www.rhodeshouse.ox.ac.uk/scholarships/', ['masters', 'phd'], 'fully', 'Jun–Oct', 'Oxford; by constituency incl. Pakistan, India, Bangladesh, Gulf'),
  S('GB', 'Clarendon Fund (Oxford)', 'https://www.ox.ac.uk/clarendon', ['masters', 'phd'], 'fully', 'Dec–Jan', 'Automatic consideration with Oxford application'),
  S('GB', 'GREAT Scholarships', 'https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships', ['masters'], 'partial', 'Jan–May', 'Country-specific incl. Pakistan, India, Bangladesh'),
  S('GB', 'Imperial President\'s PhD Scholarships', 'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/scholarships/presidents-phd-scholarships/', ['phd'], 'fully', 'Nov–Mar', ''),
  S('DE', 'DAAD scholarships (all programmes)', 'https://www.daad.de/en/study-and-research-in-germany/scholarships/', ['masters', 'phd', 'postdoc'], 'fully', 'Varies by programme', 'Development-related master\'s (EPOS), research grants, postdoc'),
  S('DE', 'Deutschlandstipendium', 'https://www.deutschlandstipendium.de/', ['bachelors', 'masters'], 'partial', 'Varies by university', 'Merit; open to internationals at participating universities'),
  S('DE', 'Heinrich Böll Foundation scholarships', 'https://www.boell.de/en/scholarships', ['masters', 'phd'], 'fully', 'Mar & Sep', ''),
  S('DE', 'Konrad Adenauer Foundation (KAS) scholarships', 'https://www.kas.de/en/web/begabtenfoerderung-und-kultur/scholarships', ['masters', 'phd'], 'fully', 'Jul', ''),
  S('DE', 'Friedrich Ebert Foundation scholarships', 'https://www.fes.de/en/scholarships', ['bachelors', 'masters', 'phd'], 'fully', 'Rolling', ''),
  S('DE', 'Max Planck / Helmholtz doctoral positions', 'https://www.mpg.de/careers', ['phd', 'postdoc'], 'fully', 'Rolling', 'Paid positions, not scholarships'),
  S('EU', 'Erasmus Mundus Joint Masters', 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en', ['masters'], 'fully', 'Oct–Feb', 'Study in 2+ European countries; open worldwide'),
  S('EU', 'Marie Skłodowska-Curie Actions (doctoral networks, postdoctoral fellowships)', 'https://marie-sklodowska-curie-actions.ec.europa.eu/', ['phd', 'postdoc'], 'fully', 'Varies', 'Any nationality'),
  S('NL', 'Holland Scholarship', 'https://www.studyinnl.org/finances/holland-scholarship', ['bachelors', 'masters'], 'partial', 'Feb–May', 'Non-EEA students'),
  S('NL', 'Orange Knowledge / OKP successor programmes', 'https://www.nuffic.nl/en/subjects/orange-knowledge-programme', ['masters'], 'fully', 'Varies', 'Selected countries incl. Pakistan, Bangladesh'),
  S('NL', 'Leiden Excellence Scholarship', 'https://www.universiteitleiden.nl/en/scholarships/sea/leiden-university-excellence-scholarship-programme', ['masters'], 'partial', 'Oct–Feb', ''),
  S('SE', 'Swedish Institute Scholarships for Global Professionals', 'https://si.se/en/apply/scholarships/', ['masters'], 'fully', 'Nov–Feb', 'Selected countries incl. Pakistan, Bangladesh'),
  S('FI', 'Finland Scholarship / university scholarships', 'https://www.studyinfinland.fi/scholarships', ['masters', 'phd'], 'fully', 'Jan', 'Tuition waiver + relocation grant'),
  S('DK', 'Danish Government Scholarships for non-EU students', 'https://studyindenmark.dk/study-options/tuition-fees-scholarships', ['masters'], 'partial', 'Varies', ''),
  S('NO', 'Norwegian research fellowships (paid PhD positions)', 'https://www.jobbnorge.no/en', ['phd', 'postdoc'], 'fully', 'Rolling', 'Salaried positions'),
  S('FR', 'Eiffel Excellence Scholarship', 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence', ['masters', 'phd'], 'fully', 'Oct–Jan', 'Nominated by French institutions'),
  S('FR', 'France Excellence / embassy scholarships', 'https://www.campusfrance.org/en/scholarships', ['masters', 'phd'], 'fully', 'Varies by country', ''),
  S('CH', 'Swiss Government Excellence Scholarships', 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html', ['phd', 'postdoc'], 'fully', 'Aug–Dec', ''),
  S('CH', 'ETH Excellence Scholarship', 'https://ethz.ch/en/studies/financial/scholarships/excellencescholarship.html', ['masters'], 'fully', 'Nov–Dec', ''),
  S('IT', 'Italian Government scholarships for foreign students', 'https://studyinitaly.esteri.it/en/call-for-procedure', ['masters', 'phd'], 'fully', 'Mar–May', ''),
  S('IT', 'Politecnico di Milano merit scholarships', 'https://www.polimi.it/en/international-prospective-students/tuition-fees-and-scholarships', ['masters'], 'partial', 'Varies', ''),
  S('ES', 'Spanish Government / MAEC-AECID', 'https://www.aecid.es/', ['masters', 'phd'], 'fully', 'Varies', ''),
  S('BE', 'ARES scholarships / VLIR-UOS', 'https://www.vliruos.be/en/scholarships', ['masters'], 'fully', 'Varies', 'Selected countries'),
  S('AT', 'Austrian OeAD / Ernst Mach grants', 'https://grants.at/en/', ['masters', 'phd', 'postdoc'], 'fully', 'Varies', ''),
  S('HU', 'Stipendium Hungaricum', 'https://stipendiumhungaricum.hu/', ['bachelors', 'masters', 'phd'], 'fully', 'Nov–Jan', 'Partner countries incl. Pakistan, India, Bangladesh'),
  S('PL', 'Banach / Łukasiewicz scholarships (NAWA)', 'https://nawa.gov.pl/en/students', ['masters', 'phd'], 'fully', 'Varies', ''),
  S('CZ', 'Czech Government scholarships for developing countries', 'https://www.mzv.cz/jnp/en/information_for_aliens/scholarships/', ['bachelors', 'masters', 'phd'], 'fully', 'Sep', ''),
  S('TR', 'Türkiye Bursları', 'https://www.turkiyeburslari.gov.tr/', ['bachelors', 'masters', 'phd'], 'fully', 'Jan–Feb', 'Worldwide'),
  S('US', 'Fulbright Foreign Student Program', 'https://foreign.fulbrightonline.org/', ['masters', 'phd'], 'fully', 'Varies by country (Pakistan: May)', 'By country commission'),
  S('US', 'Knight-Hennessy Scholars (Stanford)', 'https://knight-hennessy.stanford.edu/', ['masters', 'phd'], 'fully', 'Oct', ''),
  S('US', 'Schwarzman-like and university fellowships: Yale, Harvard, MIT graduate funding', 'https://gsas.harvard.edu/financial-support', ['phd'], 'fully', 'Dec', 'PhD admission is fully funded at most US research universities'),
  S('US', 'Humphrey Fellowship', 'https://www.humphreyfellowship.org/', ['professional'], 'fully', 'Varies', 'Mid-career professionals'),
  S('CA', 'Vanier Canada Graduate Scholarships', 'https://vanier.gc.ca/', ['phd'], 'fully', 'Nov', 'Nominated by Canadian universities'),
  S('CA', 'Banting Postdoctoral Fellowships', 'https://banting.fellowships-bourses.gc.ca/', ['postdoc'], 'fully', 'Sep', ''),
  S('CA', 'Lester B. Pearson International (Toronto)', 'https://future.utoronto.ca/pearson/', ['bachelors'], 'fully', 'Nov–Jan', ''),
  S('CA', 'Study in Canada Scholarships (SICS)', 'https://www.educanada.ca/scholarships-bourses/can/sics-eeci.aspx', ['exchange'], 'fully', 'Mar', 'Selected countries'),
  S('AU', 'Australia Awards Scholarships', 'https://www.dfat.gov.au/people-to-people/australia-awards', ['masters', 'phd'], 'fully', 'Feb–Apr', 'Selected countries incl. Pakistan, Bangladesh'),
  S('AU', 'Research Training Program (RTP) international', 'https://www.education.gov.au/research-block-grants/research-training-program', ['phd', 'masters'], 'fully', 'Varies by university', ''),
  S('AU', 'Destination Australia', 'https://www.education.gov.au/destination-australia', ['bachelors', 'masters'], 'partial', 'Varies', 'Regional campuses'),
  S('NZ', 'New Zealand Scholarships (Manaaki)', 'https://www.nzscholarships.govt.nz/', ['masters', 'phd'], 'fully', 'Feb–Mar', 'Selected countries'),
  S('NZ', 'University of Auckland International Doctoral scholarships', 'https://www.auckland.ac.nz/en/study/scholarships-and-awards.html', ['phd'], 'fully', 'Rolling', 'Domestic fees for international PhD'),
  S('JP', 'MEXT Scholarship', 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html', ['bachelors', 'masters', 'phd'], 'fully', 'Apr–May (embassy)', 'Worldwide'),
  S('JP', 'JSPS postdoctoral fellowships', 'https://www.jsps.go.jp/english/e-fellow/', ['postdoc'], 'fully', 'Varies', ''),
  S('KR', 'Global Korea Scholarship (GKS)', 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do', ['bachelors', 'masters', 'phd'], 'fully', 'Feb–Mar (graduate)', 'Worldwide'),
  S('CN', 'Chinese Government Scholarship (CSC)', 'https://www.campuschina.org/', ['bachelors', 'masters', 'phd'], 'fully', 'Jan–Apr', 'Worldwide; bilateral and university programmes'),
  S('HK', 'Hong Kong PhD Fellowship Scheme', 'https://cerg1.ugc.edu.hk/hkpfs/', ['phd'], 'fully', 'Sep–Dec', 'Worldwide'),
  S('TW', 'Taiwan Scholarship / MOE', 'https://www.studyintaiwan.org/scholarship', ['bachelors', 'masters', 'phd'], 'fully', 'Feb–Mar', ''),
  S('SG', 'SINGA (A*STAR)', 'https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa', ['phd'], 'fully', 'Jun & Dec', 'Worldwide'),
  S('SG', 'NUS / NTU research scholarships', 'https://www.nus.edu.sg/admissions/graduate-studies/scholarships', ['phd'], 'fully', 'Varies', ''),
  S('MY', 'Malaysia International Scholarship (MIS)', 'https://biasiswa.mohe.gov.my/INTER/', ['masters', 'phd'], 'fully', 'Varies', ''),
  S('TH', 'Thailand / AIT scholarships', 'https://ait.ac.th/admissions/scholarships/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('SA', 'KAUST Fellowship', 'https://admissions.kaust.edu.sa/', ['masters', 'phd'], 'fully', 'Rolling', 'Full funding for all admitted'),
  S('SA', 'Saudi Government scholarships for internationals (universities)', 'https://www.moe.gov.sa/en/education/highereducation/Pages/scholarships.aspx', ['bachelors', 'masters', 'phd'], 'fully', 'Varies', ''),
  S('QA', 'Hamad Bin Khalifa University scholarships', 'https://www.hbku.edu.qa/en/admissions/financial-aid', ['masters', 'phd'], 'fully', 'Varies', ''),
  S('QA', 'Qatar University international scholarships', 'https://www.qu.edu.qa/students/scholarships', ['bachelors', 'masters'], 'fully', 'Varies', ''),
  S('AE', 'Khalifa University graduate scholarships', 'https://www.ku.ac.ae/scholarships', ['masters', 'phd'], 'fully', 'Varies', ''),
  S('AE', 'UAEU / Zayed University scholarships', 'https://www.uaeu.ac.ae/en/admission/scholarships/', ['bachelors', 'masters', 'phd'], 'partial', 'Varies', ''),
  S('OM', 'Sultan Qaboos University international scholarships', 'https://www.squ.edu.om/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('KZ', 'Nazarbayev University scholarships', 'https://nu.edu.kz/admissions', ['bachelors', 'masters', 'phd'], 'fully', 'Varies', ''),
  S('AZ', 'ADA University scholarships', 'https://www.ada.edu.az/en/admissions', ['bachelors', 'masters'], 'partial', 'Varies', ''),
  S('GE', 'Georgia state scholarships for internationals', 'https://mes.gov.ge/', ['bachelors', 'masters'], 'partial', 'Varies', ''),
  S('IE', 'Government of Ireland International Education Scholarships', 'https://hea.ie/policy/internationalisation/government-of-ireland-international-education-scholarships/', ['bachelors', 'masters', 'phd'], 'fully', 'Feb–Mar', ''),
  S('IE', 'Irish Research Council postgraduate scholarships', 'https://research.ie/', ['phd', 'postdoc'], 'fully', 'Oct', ''),
  S('PT', 'FCT PhD studentships', 'https://www.fct.pt/en/', ['phd'], 'fully', 'Varies', ''),
  S('RO', 'Romanian Government scholarships for foreigners', 'https://www.mae.ro/en/node/10251', ['bachelors', 'masters', 'phd'], 'fully', 'Mar', ''),
  S('BG', 'Bulgarian Government scholarships', 'https://www.mon.bg/', ['bachelors', 'masters'], 'partial', 'Varies', ''),
  S('EE', 'Estonian Government scholarships (EDU)', 'https://haridus.ee/', ['masters', 'phd'], 'fully', 'Varies', ''),
  S('LV', 'Latvian state scholarships', 'https://www.viaa.gov.lv/en/scholarships', ['bachelors', 'masters', 'phd'], 'partial', 'Apr', ''),
  S('LT', 'Lithuanian state scholarships', 'https://studyin.lt/scholarships/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('SK', 'Slovak National Scholarship Programme', 'https://www.scholarships.sk/en/', ['masters', 'phd', 'postdoc'], 'fully', 'Apr & Oct', ''),
  S('SI', 'Slovenian scholarships (CMEPIUS)', 'https://www.cmepius.si/en/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('HR', 'Croatian Government scholarships', 'https://mzo.gov.hr/', ['bachelors', 'masters'], 'partial', 'Varies', ''),
  S('GR', 'IKY scholarships', 'https://www.iky.gr/en/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('CY', 'Cyprus State Scholarship Foundation', 'https://www.ikyk.org.cy/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('MT', 'Malta Government scholarship schemes', 'https://education.gov.mt/', ['masters', 'phd'], 'partial', 'Varies', ''),
  S('LU', 'University of Luxembourg doctoral positions', 'https://www.uni.lu/', ['phd'], 'fully', 'Rolling', 'Salaried'),
  S('BN', 'Brunei Government Scholarship', 'https://www.mfa.gov.bn/', ['bachelors', 'masters'], 'fully', 'Jan–Feb', ''),
  S('UZ', 'El-Yurt Umidi / university scholarships', 'https://edu.uz/', ['masters'], 'partial', 'Varies', '')
];
module.exports = { SCHOLARSHIPS };
