// lib/selfheal.js — the Self-heal + 24/7 Support responder.
// Self-heal: hourly, it looks at dead jobs, stuck locks, repeated errors and unreachable sources, applies the SAFE
// remedies (re-queue with backoff, clear stale locks, pause a source that fails five times, disable a broken webhook),
// diagnoses the rest with the model using the logs, and writes a ticket with the diagnosis for a human. It never edits
// code or the database schema: those need a person.
// Support responder: every new ticket and every applicant/agency question is answered from the FAQ store and the
// applicant's own case facts when the model is confident and the category is a how-to; money, legal, complaints and
// low-confidence cases get a drafted reply for the admin instead.
const { admin } = require('./supa'); const { callAI } = require('./router');
async function log(kind, detail, action, outcome) { try { await admin().from('selfheal_log').insert({ kind, detail: String(detail || '').slice(0, 500), action, outcome }); } catch (e) {} }
async function heal() {
  const out = { requeued: 0, unlocked: 0, sources_paused: 0, webhooks_paused: 0, diagnosed: 0 };
  // 1. Dead jobs that failed on transient errors get one more life with a delay; permanent ones are diagnosed.
  try { const { data: dead } = await admin().from('job_queue').select('id,type,last_error,attempts,payload').eq('status', 'dead').limit(50); for (const j of (dead || [])) { const transient = /timeout|ECONN|429|503|502|fetch failed|network|rate/i.test(String(j.last_error || '')); if (transient && (j.attempts || 0) < 6) { await admin().from('job_queue').update({ status: 'queued', run_after: new Date(Date.now() + 15 * 60000).toISOString(), last_error: null }).eq('id', j.id); out.requeued++; await log('dead_job', j.type + ': ' + j.last_error, 'requeued +15min', 'ok'); } else { out.diagnosed++; let diag = ''; try { diag = await callAI('high_value', `A background job failed permanently. Diagnose in 3 plain lines: likely cause, whether it needs a code/config/data fix, and the exact next step for the engineer. Job type: ${j.type}. Error: ${String(j.last_error).slice(0, 600)}. Payload keys: ${Object.keys(j.payload || {}).join(',')}`, { maxTokens: 200 }); } catch (e) { diag = 'diagnosis unavailable'; } await admin().from('job_queue').update({ status: 'failed', last_error: (j.last_error || '') + ' | diagnosed' }).eq('id', j.id); await admin().from('support_tickets').insert({ user_id: null, subject: '[self-heal] ' + j.type + ' failed permanently', message: 'Error: ' + String(j.last_error).slice(0, 400) + '\n\nDiagnosis: ' + diag, status: 'open', category: 'bug', priority: 'high' }).then(() => {}, () => {}); await log('dead_job', j.type, 'diagnosed + ticket', 'needs human'); } } } catch (e) {}
  // 2. Stale locks: jobs "running" for more than 30 minutes are released.
  try { const cut = new Date(Date.now() - 30 * 60000).toISOString(); const { data: stuck } = await admin().from('job_queue').select('id').eq('status', 'running').lt('locked_at', cut); if (stuck && stuck.length) { await admin().from('job_queue').update({ status: 'queued', locked_at: null, locked_by: null }).in('id', stuck.map(s => s.id)); out.unlocked = stuck.length; await log('stuck_lock', stuck.length + ' jobs', 'released', 'ok'); } } catch (e) {}
  // 3. Sources failing five runs in a row are paused with a ticket; webhooks with five failed deliveries are paused.
  try { const { data: srcs } = await admin().from('sources').select('id,kind,key,last_error').eq('enabled', true).not('last_error', 'is', null); for (const s of (srcs || [])) { const { count } = await admin().from('job_queue').select('id', { count: 'exact', head: true }).eq('type', 'acq_run').in('status', ['dead', 'failed']).ilike('last_error', '%' + String(s.last_error || 'x').slice(0, 30) + '%'); if ((count || 0) >= 5) { await admin().from('sources').update({ enabled: false }).eq('id', s.id); out.sources_paused++; await log('source', s.kind + ':' + s.key, 'paused after repeated failures', 'needs human'); } } } catch (e) {}
  try { const { data: hooks } = await admin().from('org_webhooks').select('id,url').eq('status', 'active'); for (const h of (hooks || [])) { const { count } = await admin().from('webhook_deliveries').select('id', { count: 'exact', head: true }).eq('webhook_id', h.id).eq('status', 'failed').gte('created_at', new Date(Date.now() - 86400000).toISOString()); if ((count || 0) >= 5) { await admin().from('org_webhooks').update({ status: 'paused' }).eq('id', h.id); out.webhooks_paused++; await log('webhook', h.url, 'paused after 5 failures in 24h', 'owner notified'); } } } catch (e) {}
  return out;
}
/* Support responder: answer when it is safe, draft when it is not. */
async function respond(ticketId) {
  const { data: t } = await admin().from('support_tickets').select('*').eq('id', ticketId).maybeSingle(); if (!t || t.reply) return null;
  const { data: faqs } = await admin().from('faqs').select('question,answer,audience').limit(80); let facts = {};
  if (t.user_id) { try { const { data: p } = await admin().from('profiles').select('full_name,origin_country,journey_stage,next_action,apply_email').eq('id', t.user_id).maybeSingle(); let bal = null; try { const { data: led } = await admin().from('credit_ledger').select('delta').eq('user_id', t.user_id); bal = (led || []).reduce((a, r) => a + (Number(r.delta) || 0), 0); } catch (e) {} facts = { name: p && p.full_name, stage: p && p.journey_stage, next: p && p.next_action, mailbox: p && p.apply_email, credits: bal }; } catch (e) {} }
  let v = { confidence: 0, reply: null, category: t.category || 'other' }; let guidance = []; try { const { data: g } = await admin().from('admin_guidance').select('text,applies_to').eq('active', true).or('expires_at.is.null,expires_at.gte.' + new Date().toISOString()).limit(10); guidance = (g || []).filter(x => (x.applies_to || []).some(a => ['all', 'support'].includes(a))).map(x => x.text); } catch (e) {}
  try { const txt = await callAI('high_value', `You are ForiForeign Support.${guidance.length ? ' Standing guidance from the admin: ' + guidance.join(' | ') : ''} Answer ONLY JSON: {"category":"payment|bug|visa|partnership|account|complaint|howto|other","confidence":0.0-1.0,"reply":"a complete, kind, specific reply in plain English (no long dashes, no stock phrases), signed 'ForiForeign Support, admin@foriforeign.com'"}. Use the FAQ and the person's own facts. Confidence must be below 0.6 if the question involves money, refunds, legal matters, a complaint, a bug, or anything the FAQ does not cover.\nFAQ: ${JSON.stringify(faqs || []).slice(0, 7000)}\nPERSON: ${JSON.stringify(facts)}\nSUBJECT: ${t.subject}\nMESSAGE: ${String(t.message || '').slice(0, 3000)}`, { maxTokens: 600, json: true }); const m = String(txt).match(/\{[\s\S]*\}/); if (m) v = Object.assign(v, JSON.parse(m[0])); } catch (e) {}
  const safe = ['howto', 'account', 'visa', 'partnership'].includes(v.category) && Number(v.confidence) >= 0.8 && v.reply;
  const reply = v.reply ? require('./partnerships').humanize(v.reply) : null;
  if (safe) { await admin().from('support_tickets').update({ reply, status: 'answered', auto_replied: true, category: v.category, suggested_reply: reply }).eq('id', t.id); try { const { data: p } = t.user_id ? await admin().from('profiles').select('email').eq('id', t.user_id).maybeSingle() : { data: null }; const to = (p && p.email) || t.email; const M = require('./mailer'); if (to && M.enabled()) await M.send(to, 'Re: ' + (t.subject || 'your question'), M.wrap('Reply from ForiForeign Support', reply, 'home')); if (t.user_id) await require('./notify').push(t.user_id, 'support', 'Your question was answered', reply.slice(0, 300), 'home'); } catch (e) {} await log('support', t.subject, 'auto-replied (' + v.category + ', ' + v.confidence + ')', 'ok'); return { auto: true }; }
  await admin().from('support_tickets').update({ suggested_reply: reply, category: v.category || t.category }).eq('id', t.id); return { auto: false, drafted: !!reply };
}
module.exports = { heal, respond, log };
