// lib/seo.js — built-in SEO: indexable landing pages for every destination × lane (rendered from the sourced rules,
// boards and universities, no database needed), audience pages, structured data, sitemap and robots. Every page carries
// real content a search engine can rank, honest titles, canonical links and a clear next action.
const { PORTALS } = require('./visa_portals'); const { W } = require('./world'); const BOARDS = require('./boards'); const U = require('./universities_seed').U;
const esc = s => String(s || '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const name = cc => (W[cc] && W[cc][0]) || cc;
let RULES = null; function rules() { if (!RULES) RULES = [].concat(require('./visa_seed').seed, require('./visa_seed2').seed, require('./visa_seed3').seed, require('./visa_seed4').seed, require('./visa_seed5').seed, require('./visa_seed6').seed); return RULES; }
function shell(title, desc, canonical, body, ld) { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="ForiForeign"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary"><script type="application/ld+json">${JSON.stringify(ld)}</script><style>body{font-family:Inter,system-ui,sans-serif;background:#070F22;color:#D6E9FF;margin:0;line-height:1.6}.wrap{max-width:880px;margin:0 auto;padding:28px 20px}h1{color:#fff;font-size:30px;letter-spacing:-.02em;margin:0 0 6px}h2{color:#fff;font-size:18px;margin:26px 0 8px}a{color:#7EE6FF}.sub{color:#8FA9CE}.cta{display:inline-block;background:#F5B841;color:#0E1F42;font-weight:700;padding:10px 18px;border-radius:10px;text-decoration:none;margin-top:14px}.card{border:1px solid rgba(140,178,255,.2);border-radius:14px;padding:14px;margin:10px 0}.chip{display:inline-block;border:1px solid rgba(140,178,255,.3);border-radius:999px;padding:2px 9px;font-size:12px;margin:2px 4px 2px 0}nav a{margin-right:14px}</style></head><body><div class="wrap"><nav><a href="/">ForiForeign</a><a href="/pricing.html">Pricing</a><a href="/partners.html">Partners</a><a href="/help.html">Help</a></nav>${body}<p class="sub" style="margin-top:30px;font-size:12px">ForiForeign (Private) Limited · admin@foriforeign.com · Information drawn from official sources shown on each rule; not legal advice.</p></div></body></html>`; }
function countryPage(cc, lane) {
  cc = String(cc || '').toUpperCase(); if (!PORTALS[cc]) return null; lane = lane === 'work' ? 'work' : 'study'; const N = name(cc); const R = rules().filter(r => r.country_code === cc && (lane === 'work' ? r.lane === 'work' : r.lane !== 'work'));
  const routes = [...new Set(R.filter(r => r.rule_type !== 'licence').map(r => r.route_name))].slice(0, 6); const elig = R.filter(r => r.rule_type === 'eligibility').slice(0, 3); const pr = R.find(r => r.rule_type === 'pr_path'); const wr = R.find(r => r.rule_type === 'work_rights'); const lic = R.filter(r => r.rule_type === 'licence').slice(0, 6); const tracks = R.filter(r => r.value && r.value.track);
  const boards = BOARDS.links({ cc, text: lane === 'work' ? 'jobs' : 'scholarships', lane, country: N }).slice(0, 8); const unis = (U[cc] || []).slice(0, 8).map(x => x.split('|'));
  const title = lane === 'work' ? `Work in ${N}: work visas, labour and skilled permits, licences and jobs for international applicants` : `Study in ${N}: student visa, scholarships, universities and post-study work`;
  const desc = lane === 'work' ? `How to get a job and a work permit in ${N} from any country: routes, employer and applicant steps, licence rules for regulated professions, PR path, and where the jobs are. Sourced from official pages.` : `How to study in ${N} from any country: student visa route, funds and language, work rights while studying, post-study options and PR, top universities and scholarship portals. Sourced from official pages.`;
  const body = `<h1>${esc(title)}</h1><p class="sub">Updated from official sources and watched nightly. Upload your CV to see which of these routes you are eligible for today.</p><a class="cta" href="/?go=${lane}&cc=${cc}">See my eligibility for ${esc(N)} (free)</a>
  <h2>Routes</h2>${routes.map(r => `<span class="chip">${esc(r)}</span>`).join('') || '<p class="sub">Official entry point: <a href="' + esc(PORTALS[cc][0]) + '">' + esc(PORTALS[cc][1]) + '</a></p>'}
  ${elig.map(e => `<div class="card"><b>${esc(e.route_name)}</b><p>${esc(e.text)}</p><p class="sub">Source: <a href="${esc(e.source_url)}" rel="nofollow">${esc(e.source_title || e.source_url)}</a></p></div>`).join('')}
  ${tracks.length ? `<h2>Who does what</h2>${tracks.slice(0, 2).map(t => `<div class="card"><b>${esc(t.value.track === 'employer' ? 'Employer' : 'Applicant')} steps</b><p>${esc((t.value.steps || []).join(' → '))}</p></div>`).join('')}` : ''}
  ${lane === 'work' ? (() => { const lab = R.filter(r => r.rule_type === 'eligibility' && r.value && r.value.labour); return lab.length ? `<h2>Labour, trades and care routes in ${esc(N)}</h2>${lab.map(l => `<div class="card"><b>${esc(l.route_name)}</b><p>${esc(l.text)}</p><p class="sub">${(l.value.categories || []).map(c => `<span class="chip">${esc(c)}</span>`).join('')} Source: <a href="${esc(l.source_url)}" rel="nofollow">${esc(l.source_title || l.source_url)}</a></p></div>`).join('')}<p class="sub">Rule of the road: real employers and government schemes never charge the worker for the visa or the permit; use only licensed recruiters of your country.</p>` : ''; })() : ''}
  ${wr ? `<h2>Working while studying</h2><p>${esc(wr.text)}</p>` : ''}${pr ? `<h2>After that: staying on</h2><p>${esc(pr.text)}</p>` : ''}
  ${lic.length ? `<h2>Regulated professions in ${esc(N)}</h2>${lic.map(l => `<div class="card"><b>${esc((l.value || {}).profession || '').replace(/_/g, ' ')}</b><p>${esc(l.text)}</p><p class="sub">Source: <a href="${esc(l.source_url)}" rel="nofollow">${esc(l.source_title || l.source_url)}</a></p></div>`).join('')}` : ''}
  ${unis.length && lane === 'study' ? `<h2>Universities in ${esc(N)}</h2><p>${unis.map(([n, d]) => `<a href="https://www.${esc(d)}" rel="nofollow">${esc(n)}</a>`).join(' · ')}</p>` : ''}
  <h2>Where the ${lane === 'work' ? 'jobs' : 'scholarships'} are listed</h2><p>${boards.map(b => `<a href="${esc(b.url)}" rel="nofollow">${esc(b.name)}</a>`).join(' · ')}</p>
  <h2>How ForiForeign helps</h2><p>Upload your CV, see verified matches with a real score, and let the platform prepare the complete application which you send from your own address. Replies are read for you; the offer, the visa desk, arrival and residence follow in the same place. Search is free; you pay only when the platform does work for you.</p><a class="cta" href="/?go=${lane}&cc=${cc}">Start free</a>
  <p class="sub" style="margin-top:20px">Other destinations: ${Object.keys(PORTALS).filter(c => c !== cc).slice(0, 53).map(c => `<a href="/${lane}-in/${c.toLowerCase()}">${esc(name(c))}</a>`).join(' · ')}</p>`;
  const ld = { '@context': 'https://schema.org', '@type': 'Article', headline: title, description: desc, author: { '@type': 'Organization', name: 'ForiForeign' }, publisher: { '@type': 'Organization', name: 'ForiForeign (Private) Limited' }, mainEntityOfPage: `https://foriforeign.com/${lane}-in/${cc.toLowerCase()}`, dateModified: new Date().toISOString().slice(0, 10) };
  return shell(title, desc, `https://foriforeign.com/${lane}-in/${cc.toLowerCase()}`, body, ld);
}
function audiencePage(kind) {
  const P = { consultancies: { title: 'ForiForeign for consultancies: enter a client once, the platform does the rest', desc: 'Agency plans of 100, 500 and 1,000 applications a month with branch and sub-branch control, quota allocation, isolation, licences and a plan pool. From $149 a month.', body: '<h1>Enter a client once. The platform does the rest.</h1><p>Consultancies in Pakistan, India, Bangladesh and beyond run their whole desk on ForiForeign: the client is entered once, the platform searches, verifies, prepares, sends from the client\'s own address, reads every reply and tracks offers and visas. Managers see their branches; sub-agents see only their clients; owners see everything. Plans: Starter 100 ($149), Growth 500 ($599), Scale 1000 ($999) per month; annual costs 10 months.</p><a class="cta" href="/?go=work">Open a workspace</a>' }, universities: { title: 'ForiForeign for universities: complete, eligible applications, paid only on enrolment', desc: 'A free partner workspace, consent-gated applicant files, pilot metrics, and a success fee only after enrolment. No ranking advantage; applicants apply in their own name.', body: '<h1>Complete, eligible applications. Paid only when they enrol.</h1><p>Applicants from any country send complete files prepared on the platform in their own name. You see identity only with the applicant\'s consent, decide as you always do, and pay a success fee only after enrolment under a signed MOU. A free 15-day trial workspace shows the flow with real applicants.</p><a class="cta" href="/partners.html">Partner with us</a>' }, employers: { title: 'ForiForeign for employers: prepared, sponsorship-aware international candidates, free', desc: 'Receive verified, licence-checked candidates through your own careers page; no fee to receive. Optional spotlight and per-hire fees.', body: '<h1>Prepared, sponsorship-aware candidates. Free to receive.</h1><p>Candidates reach you through your own careers page or ATS, with documents read, licences checked and visa routes understood. Nothing to install and nothing to pay to receive applications. Optional paid visibility and per-hire fees when you want more.</p><a class="cta" href="/partners.html">Talk to us</a>' } }[kind]; if (!P) return null;
  return shell(P.title, P.desc, 'https://foriforeign.com/for-' + kind, P.body, { '@context': 'https://schema.org', '@type': 'WebPage', name: P.title, description: P.desc });
}
function sitemap(extra) { const urls = [...(Array.isArray(extra) ? extra : []), 'https://foriforeign.com/', 'https://foriforeign.com/pricing.html', 'https://foriforeign.com/partners.html', 'https://foriforeign.com/help.html', 'https://foriforeign.com/legal.html', 'https://foriforeign.com/trust.html', 'https://foriforeign.com/crm.html', 'https://foriforeign.com/for-consultancies', 'https://foriforeign.com/for-universities', 'https://foriforeign.com/for-employers']; for (const cc of Object.keys(PORTALS)) { urls.push('https://foriforeign.com/study-in/' + cc.toLowerCase()); urls.push('https://foriforeign.com/work-in/' + cc.toLowerCase()); } return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + urls.map(u => '<url><loc>' + u + '</loc><changefreq>weekly</changefreq></url>').join('') + '</urlset>'; }
const ORG_LD = { '@context': 'https://schema.org', '@type': 'Organization', name: 'ForiForeign', url: 'https://foriforeign.com', email: 'admin@foriforeign.com', description: 'Study and work abroad platform: from CV to visa to residence, 54 destinations, any origin.', sameAs: [] };
/* PROGRAMMATIC PAGES (R11900): one page per country × profession for the work lane and per country × field for study, built from the same sourced
   rules, the pay parser, the language guide, the origin clearance and the PR pathway. FAQ JSON-LD on every page so answer engines quote us. */
const PROFS = ['nurse', 'doctor', 'pharmacist', 'dentist', 'physiotherapist', 'care worker', 'engineer', 'software developer', 'data analyst', 'accountant', 'teacher', 'lecturer', 'researcher', 'architect', 'electrician', 'plumber', 'welder', 'mechanic', 'driver', 'chef', 'hospitality', 'construction worker', 'warehouse worker', 'security guard', 'agriculture worker', 'lab technologist', 'radiographer', 'midwife', 'paramedic', 'social worker', 'marketing', 'sales', 'hr', 'designer', 'pilot', 'seafarer', 'veterinarian', 'biotechnologist', 'chemist', 'it support'];
const FIELDS = ['pharmacy', 'medicine', 'nursing', 'engineering', 'computer science', 'data science', 'business', 'mba', 'economics', 'law', 'biotechnology', 'public health', 'psychology', 'education', 'architecture', 'environmental science', 'agriculture', 'mathematics', 'physics', 'chemistry', 'artificial intelligence', 'cybersecurity', 'finance', 'international relations', 'design'];
function slug(x) { return String(x).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function professionPage(cc, prof, lane) { cc = String(cc || '').toUpperCase(); if (!PORTALS[cc]) return null; const list = lane === 'work' ? PROFS : FIELDS; const p = list.find(x => slug(x) === slug(prof)); if (!p) return null; const N = name(cc); const R = rules().filter(r => r.country_code === cc && (lane === 'work' ? r.lane === 'work' : r.lane !== 'work')); const routes = [...new Set(R.filter(r => r.rule_type !== 'licence').map(r => r.route_name))].slice(0, 4); const elig = R.filter(r => r.rule_type === 'eligibility').slice(0, 2); const lic = R.filter(r => r.rule_type === 'licence' && new RegExp(p.split(' ')[0], 'i').test(r.text || '')).slice(0, 3); const pr = R.find(r => r.rule_type === 'pr_path'); let lang = null; try { lang = require('./language_guide').guide(cc, lane === 'work' ? 'work' : 'study'); } catch (e) {} let clear = null; try { clear = require('./emigration').rules('PK'); } catch (e) {} let pay = null; try { pay = require('./payscale').parseSalary('', cc); } catch (e) {}
  const title = lane === 'work' ? (p[0].toUpperCase() + p.slice(1) + ' jobs in ' + N + ' for Pakistani and South Asian applicants · visa route, licence, pay, PR') : (p[0].toUpperCase() + p.slice(1) + ' in ' + N + ' · admission, scholarships, visa, post-study work'); const desc = lane === 'work' ? ('How a ' + p + ' from Pakistan, India or Bangladesh gets a job in ' + N + ': the visa route, the licence or registration, the language test, the emigration clearance and the path to PR. Verified on official pages.') : ('How to study ' + p + ' in ' + N + ': routes, eligibility, language, scholarships and the way to work and residence after the degree.');
  const faqs = [[lane === 'work' ? 'Which visa does a ' + p + ' use for ' + N + '?' : 'Which visa does a student of ' + p + ' use for ' + N + '?', routes.length ? routes.join('; ') : 'See the sourced routes on the ' + N + ' page.'], ['Is a licence or registration needed?', lic.length ? lic.map(l => l.text).join(' ') : (lane === 'work' ? 'Regulated professions need registration with the national authority; unregulated roles need the employer\'s sponsorship only.' : 'Admission is by the institution; professional registration comes after the degree.')], ['What language test is asked?', lang && lang.text ? lang.text : 'Depends on the route; the platform shows the exact level per posting.'], ['What is the path to permanent residence?', pr ? pr.text : 'See the PR pathway on the platform, kept current nightly.'], ['Do I need emigration clearance from Pakistan?', clear && clear.authority ? (clear.authority + ' clearance applies to labour and some skilled contracts.') : 'For labour contracts, yes; the platform tells you when.']];
  const ld = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) };
  const body = '<main style="max-width:900px;margin:0 auto;padding:30px 20px"><p style="font:700 12px Inter;letter-spacing:.08em;text-transform:uppercase;color:#1683FF">' + (lane === 'work' ? 'Work abroad' : 'Study abroad') + ' · ' + N + '</p><h1 style="font:700 40px/1.1 Fraunces,serif;color:#0B1B3A;margin:6px 0 10px">' + title.split(' · ')[0] + '</h1><p style="color:#3B4B6B;font-size:17px">' + desc + '</p>' + (routes.length ? '<h2>Routes</h2><ul>' + routes.map(r => '<li>' + r + '</li>').join('') + '</ul>' : '') + (elig.length ? '<h2>Eligibility, from the official page</h2>' + elig.map(e => '<p>' + e.text + (e.source_url ? ' <a href="' + e.source_url + '" rel="nofollow noopener">source</a>' : '') + '</p>').join('') : '') + '<h2>Questions people ask</h2>' + faqs.map(([q, a]) => '<h3>' + q + '</h3><p>' + a + '</p>').join('') + '<div style="margin:28px 0;padding:22px;border:1px solid #E3E9F6;border-top:3px solid #C9A227;border-radius:16px;background:#fff"><b style="font-size:18px;color:#0B1B3A">See real, verified ' + (lane === 'work' ? p + ' openings in ' + N : p + ' places in ' + N) + ' matched to your CV</b><p style="color:#3B4B6B">Upload your CV once; every posting is verified on its official page; applications go from your own ForiForeign address; the visa desk and the PR pathway follow.</p><a href="/app#signup?intent=' + encodeURIComponent(lane + ':' + cc + ':' + slug(p)) + '" style="display:inline-block;background:#1683FF;color:#fff;font:700 15px Inter;padding:12px 20px;border-radius:12px;text-decoration:none">Start free</a></div><p style="color:#6B7A99;font-size:12.5px">Information, not legal advice. Every rule links to its official source and is re-read nightly.</p></main>';
  return shell(title, desc, 'https://foriforeign.com/' + (lane === 'work' ? 'work-in' : 'study-in') + '/' + cc.toLowerCase() + '/' + slug(p), body, [ld, ORG_LD]); }
function programmaticUrls() { const out = []; for (const cc of Object.keys(PORTALS)) { for (const p of PROFS) out.push('https://foriforeign.com/work-in/' + cc.toLowerCase() + '/' + slug(p)); for (const f of FIELDS) out.push('https://foriforeign.com/study-in/' + cc.toLowerCase() + '/' + slug(f)); } return out; }
/* Public job page with JobPosting JSON-LD (Google for Jobs). Facts come from the verified posting; the value we sell (preparation, sending, reading) stays behind sign-up. */
function jobPage(o) { if (!o || o.kind !== 'work') return null; const N = name(o.country_code); const title = String(o.title || '') + ' · ' + String(o.institution || '') + ' · ' + N; const desc = String(o.description || '').replace(/\s+/g, ' ').slice(0, 300); const ld = { '@context': 'https://schema.org', '@type': 'JobPosting', title: o.title, description: desc || o.title, datePosted: String(o.verified_at || o.created_at || '').slice(0, 10), validThrough: o.deadline || undefined, hiringOrganization: { '@type': 'Organization', name: o.institution || 'Employer', sameAs: o.url || undefined }, jobLocation: { '@type': 'Place', address: { '@type': 'PostalAddress', addressLocality: o.city || undefined, addressCountry: o.country_code } }, employmentType: /part/i.test(o.contract_type || '') ? 'PART_TIME' : 'FULL_TIME', directApply: false, identifier: { '@type': 'PropertyValue', name: 'ForiForeign', value: o.id } };
  const body = '<main style="max-width:900px;margin:0 auto;padding:30px 20px"><p style="font:700 12px Inter;letter-spacing:.08em;text-transform:uppercase;color:#1683FF">Verified opening · ' + N + '</p><h1 style="font:700 36px/1.1 Fraunces,serif;color:#0B1B3A;margin:6px 0 10px">' + String(o.title || '') + '</h1><p style="color:#3B4B6B;font-size:16px">' + String(o.institution || '') + (o.city ? ' · ' + o.city : '') + (o.salary_note ? ' · ' + o.salary_note : '') + (o.deadline ? ' · deadline ' + o.deadline : '') + '</p>' + (desc ? '<p>' + desc + '…</p>' : '') + '<div style="margin:24px 0;padding:22px;border:1px solid #E3E9F6;border-top:3px solid #C9A227;border-radius:16px;background:#fff"><b style="font-size:18px;color:#0B1B3A">Apply with a prepared case, from your own address</b><p style="color:#3B4B6B">Your CV is matched and the application is prepared with you; replies are read into your file; the visa desk follows. Verified on the official page on ' + String(o.verified_at || '').slice(0, 10) + '.</p><a href="/app#signup?intent=work:' + String(o.country_code || '').toUpperCase() + ':' + encodeURIComponent(String(o.id)) + '" style="display:inline-block;background:#1683FF;color:#fff;font:700 15px Inter;padding:12px 20px;border-radius:12px;text-decoration:none">Start free and apply</a></div></main>';
  return shell(title, desc || title, 'https://foriforeign.com/jobs/' + o.id, body, [ld, ORG_LD]); }
module.exports = { countryPage, audiencePage, sitemap, ORG_LD, professionPage, programmaticUrls, jobPage, PROFS, FIELDS, slug };
