// lib/simulation.js — THE DUMMY CASE. A real case takes months; this runs the whole journey in minutes, in continuity, with no
// waiting, so every step, agent, table, extension and screen can be checked and every error found before a real person hits it.
// Modes: 'fast' (no model calls, no outbound mail; canned content) and 'full' (model calls on; mail to the sink address only).
// Everything it creates is tagged SIM- and can be purged in one call. It never touches real users, real partners or real invoices.
const { admin } = require('./supa');
const TAG = 'SIM-'; const SINK = process.env.SIM_MAIL_SINK || null;
async function run(mode, adminId) {
  const t0 = Date.now(); const steps = []; const S = {}; const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
  const step = async (name, fn) => { const a = Date.now(); try { const detail = await fn(); steps.push({ name, ok: true, ms: Date.now() - a, detail: detail == null ? '' : String(typeof detail === 'object' ? JSON.stringify(detail).slice(0, 300) : detail) }); } catch (e) { steps.push({ name, ok: false, ms: Date.now() - a, detail: String(e && e.message || e).slice(0, 300) }); } };
  const full = mode === 'full';
  // ---------- 0. Platform ----------
  await step('Health: database reachable', async () => { const { error } = await admin().from('profiles').select('id', { count: 'exact', head: true }); if (error) throw new Error(error.message); return 'ok'; });
  await step('Bulkhead: lanes open', async () => { const Q = require('./queue'); const st = Q.laneStatus(); return 'tripped ' + st.tripped.length + ', max/lane ' + st.max_running; });
  // ---------- 1. People ----------
  await step('Create SIM applicant (auth user + profile + mailbox)', async () => { const email = 'sim-applicant-' + stamp + '@foriforeign.com'; const { data, error } = await admin().auth.admin.createUser({ email, password: 'Sim-' + stamp + '-Pass!1', email_confirm: true, user_metadata: { full_name: TAG + 'Applicant ' + stamp, origin_country: 'PK', sim: true } }); if (error) throw new Error(error.message); S.userId = data.user.id; await admin().from('profiles').upsert({ id: S.userId, email, full_name: TAG + 'Applicant ' + stamp, role: 'user', origin_country: 'PK', field: 'Pharmacy', degree: 'Pharm-D', headline: TAG + 'Clinical pharmacist, 4 years hospital experience', timezone: 'Asia/Karachi' }); const CB = require('./casebrain'); const ae = await CB.provisionApplyEmail(S.userId); S.applyEmail = typeof ae === 'string' ? ae : (ae && ae.apply_email) || null; return S.userId.slice(0, 8) + ' · ' + (S.applyEmail || 'no mailbox'); });
  await step('Create SIM consultancy owner', async () => { const email = 'sim-owner-' + stamp + '@foriforeign.com'; const { data, error } = await admin().auth.admin.createUser({ email, password: 'Sim-' + stamp + '-Pass!2', email_confirm: true, user_metadata: { full_name: TAG + 'Owner ' + stamp, sim: true } }); if (error) throw new Error(error.message); S.ownerId = data.user.id; await admin().from('profiles').upsert({ id: S.ownerId, email, full_name: TAG + 'Owner ' + stamp, role: 'user', origin_country: 'PK' }); return S.ownerId.slice(0, 8); });
  // ---------- 2. Institution and opportunity ----------
  await step('Create SIM institution (not yet a partner)', async () => { const { data, error } = await admin().from('institutions').insert({ country_code: 'GB', name: TAG + 'University of Testshire ' + stamp, domain: 'testshire-' + stamp + '.example', kind: 'university', verified: true, source: 'sim', industry: 'works:12000 cited:250000 h:120' }).select('id,name').single(); if (error) throw new Error(error.message); S.instId = data.id; S.instName = data.name; return data.name; });
  await step('Reputation ranking reads real columns', async () => { const P = require('./partners_engine'); const { data: i } = await admin().from('institutions').select('id,name,domain,website,kind,verified,industry,reputation_meta').eq('id', S.instId).maybeSingle(); const rep = P.reputationOf(i); await admin().from('institutions').update({ reputation: rep }).eq('id', S.instId); if (!(rep > 40)) throw new Error('reputation ' + rep); return 'reputation ' + rep; });
  await step('Ingest SIM opportunity through the real ingest path', async () => { const { ingestOpps } = require('./engine'); const n = await ingestOpps([{ title: TAG + 'Clinical Pharmacist, Band 6', institution: S.instName, country_code: 'GB', kind: 'work', level: 'masters', funding: '', funding_type: 'salary', deadline: new Date(Date.now() + 60 * 86400000).toISOString().slice(0, 10), url: 'https://testshire-' + stamp + '.example/jobs/1', description: 'Clinical pharmacist role with visa sponsorship available. Requires Pharm-D and 2 years hospital experience. IELTS 7.', contact_emails: [S.applyEmail || 'sim@foriforeign.com'], apply_via: 'email', remote: 'false', salary_note: '45,000 GBP/yr', visa_sponsorship: 'true', extra: { source_key: 'sim' } }], 'work', null); const { data } = await admin().from('opportunities').select('id,status,category,eligibility_flag').eq('institution', S.instName).order('created_at', { ascending: false }).limit(1); if (!data || !data[0]) throw new Error('not ingested (' + n + ')'); S.oppId = data[0].id; await admin().from('opportunities').update({ status: 'verified', verified_at: new Date().toISOString() }).eq('id', S.oppId); return 'opp ' + S.oppId.slice(0, 8) + ' category ' + data[0].category + ' flag ' + (data[0].eligibility_flag || 'none'); });
  // ---------- 3. Discovery and match ----------
  await step('Match: applicant vs opportunity', async () => { const M = require('./match'); const r = await M.matchOpportunity(S.userId, S.oppId); S.match = r; return r.status + ' ' + r.pct + '%'; });
  await step('Quality score on the card', async () => { const DQ = require('./discovery_quality'); const { data: o } = await admin().from('opportunities').select('*').eq('id', S.oppId).maybeSingle(); const q = DQ.score(o); return q.label + ' ' + q.quality; });
  await step('Requirements brief (opportunity × person)', async () => { const R = require('./requirements'); const b = await R.brief(S.userId, S.oppId); return (b.items || []).length + ' items · ' + String(b.summary || '').slice(0, 80); });
  await step('Explore returns the SIM posting', async () => { const E = require('./explore'); const r = await E.explore({ kind: 'work', cc: 'GB', text: 'Testshire', page: 1, per: 30 }); if (!(r.rows || []).some(x => x.id === S.oppId)) throw new Error('not in explore'); return r.total + ' rows'; });
  // ---------- 4. Case ----------
  await step('Open a case with a reference', async () => { const REFS = require('./refs'); const { data, error } = await admin().from('applications').insert({ user_id: S.userId, opportunity_id: S.oppId, case_no: TAG + stamp, stage: 'preparing', status: 'draft', credits_consumed: 0 }).select('id').single(); if (error) throw new Error(error.message); S.appId = data.id; S.ref = await REFS.assign('applications', S.appId, 'application'); return S.ref || S.appId.slice(0, 8); });
  await step(full ? 'Prepare documents (model on)' : 'Prepare documents (canned; model off)', async () => { if (full) { const { prepareApplication } = require('./engine'); await prepareApplication(S.appId); } else { for (const [t, name] of [['cover_letter', 'Cover letter'], ['cv', 'CV']]) await admin().from('documents').insert({ user_id: S.userId, application_id: S.appId, name: TAG + name + '.txt', kind: 'generated', doc_type: t, generated: true, doc_status: 'read', extracted: { fields: {} } }); await admin().from('applications').update({ status: 'draft', prepared_at: new Date().toISOString() }).eq('id', S.appId); } const { count } = await admin().from('documents').select('id', { count: 'exact', head: true }).eq('application_id', S.appId); if (!count) throw new Error('no documents'); return count + ' documents'; });
  await step('Estimated chance + preflight inputs', async () => { const SU = require('./success'); const r = await SU.estimate(S.userId, S.oppId, S.appId); const OV = require('./offer_verify'); const v = await OV.verify({ text: 'Clinical pharmacist role with visa sponsorship available', employer: S.instName, cc: 'GB' }); return r.band + ' ' + r.range.join('-') + '% · fraud ' + v.level; });
  await step('Send (simulated; no mail leaves the platform)', async () => { await admin().from('applications').update({ status: 'sent', stage: 'sent', sent_at: new Date().toISOString(), sent_to: 'sim@testshire.example', channel_kind: 'direct' }).eq('id', S.appId); await admin().from('case_messages').insert({ user_id: S.userId, application_id: S.appId, direction: 'out', channel: 'email', to_addr: 'sim@testshire.example', from_addr: S.applyEmail || 'sim@forimail.com', subject: 'Application, Clinical Pharmacist, ' + TAG + stamp, triage: 'application', received_at: new Date().toISOString() }); return 'sent'; });
  await step('Referral recorded for a non-partner (expect none yet)', async () => { const P = require('./partners_engine'); const r = await P.recordReferral(S.appId); if (r) throw new Error('referral created before MOU'); return 'correctly none'; });
  // ---------- 5. Partnership on autopilot ----------
  await step('Prospect + negotiation within bounds (rules layer)', async () => { const P = require('./partners_engine'); const ev = P.evaluateTerms({ fee_pct: 15, payment_days: 30, exclusivity: false }); if (!ev.ok) throw new Error(ev.issues.join(',')); const esc = P.evaluateTerms({ fee_pct: 6, exclusivity: true }); if (!esc.escalate) throw new Error('escalation missing'); return 'agree at 15%/30d; escalate on 6%+exclusivity'; });
  await step(full ? 'MOU drafted by the model' : 'MOU inserted (canned)', async () => { if (full) { const PART = require('./partnerships'); const d = await PART.draft({ kind: 'mou', counterparty_name: S.instName, counterparty_email: 'partnerships@testshire-' + stamp + '.example', country_code: 'GB', share_pct: 15, notes: 'SIM', createdBy: adminId }); S.docId = d.id; } else { const { data, error } = await admin().from('official_documents').insert({ kind: 'mou', title: 'MOU ' + S.instName, counterparty_name: S.instName, counterparty_email: 'partnerships@testshire-' + stamp + '.example', body_text: 'SIM MOU body with share-securing clauses.', status: 'draft', share_pct: 15, country_code: 'GB', terms: { fee_pct: 15, payment_days: 30, trial_days: 15 } }).select('id').single(); if (error) throw new Error(error.message); S.docId = data.id; } return S.docId.slice(0, 8); });
  await step('Countersign → onboard → partner priority on', async () => { await admin().from('official_documents').update({ status: 'countersigned', countersigned_at: new Date().toISOString(), valid_from: new Date().toISOString().slice(0, 10), valid_until: new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10) }).eq('id', S.docId); const P = require('./partners_engine'); const r = await P.onboard(S.docId); if (!r || !r.institution_id) throw new Error('not onboarded: ' + JSON.stringify(r)); const { data: i } = await admin().from('institutions').select('partner_tier,partner_terms').eq('id', S.instId).maybeSingle(); const { data: o } = await admin().from('opportunities').select('is_partner').eq('id', S.oppId).maybeSingle(); if (!i || i.partner_tier !== 'mou') throw new Error('tier ' + (i && i.partner_tier)); if (!(i.partner_terms && i.partner_terms.fee_pct === 15)) throw new Error('terms not stored'); if (!o || !o.is_partner) throw new Error('posting not flagged'); return 'partner mou, 15%, posting flagged'; });
  await step('Partner-first among eligible (explore order + match boost)', async () => { const E = require('./explore'); const r = await E.explore({ kind: 'work', cc: 'GB', page: 1, per: 30 }); const idx = (r.rows || []).findIndex(x => x.id === S.oppId); const M = require('./match'); const m = await M.matchOpportunity(S.userId, S.oppId); return 'position ' + (idx + 1) + ' · partner flag ' + m.partner + ' · ' + m.pct + '%'; });
  await step('Referral now recorded (partner)', async () => { const P = require('./partners_engine'); const id = await P.recordReferral(S.appId); if (!id) throw new Error('no referral'); S.refId = id; return id.slice(0, 8); });
  // ---------- 6. Replies, offer, visa, arrival ----------
  await step('Reply intake: interview invitation → referral reply', async () => { await admin().from('case_messages').insert({ user_id: S.userId, application_id: S.appId, direction: 'in', channel: 'email', from_addr: 'hr@testshire-' + stamp + '.example', to_addr: S.applyEmail || 'sim@forimail.com', subject: 'Interview invitation', triage: 'application', classification: 'interview_invite', confidence: 0.95, needs_confirmation: false, received_at: new Date().toISOString() }); const P = require('./partners_engine'); await P.updateReferralStage(S.appId, 'reply'); return 'ok'; });
  await step('Offer recorded → referral offer', async () => { await admin().from('offers').insert({ user_id: S.userId, application_id: S.appId, status: 'received', deadline: new Date(Date.now() + 21 * 86400000).toISOString().slice(0, 10), conditions: { sim: true } }).then(r => { if (r.error) throw new Error(r.error.message); }); await admin().from('applications').update({ status: 'offer', stage: 'offer' }).eq('id', S.appId); const P = require('./partners_engine'); await P.updateReferralStage(S.appId, 'offer'); return 'ok'; });
  await step('Visa desk: file → submitted → check-ins scheduled', async () => { const { data, error } = await admin().from('visa_cases').insert({ user_id: S.userId, country_code: 'GB', route_key: 'gb_skilled_worker', status: 'preparing', steps: {} }).select('id').single(); if (error) throw new Error(error.message); S.visaId = data.id; await admin().from('visa_cases').update({ status: 'submitted', submitted_on: new Date().toISOString().slice(0, 10), tracking_ref: 'GWF' + stamp.slice(-6) }).eq('id', S.visaId); const C = require('./checkins'); const r = await C.schedule(S.visaId); if (!r || !r.checkins || r.checkins.length !== 3) throw new Error('no check-ins'); return 'window ' + JSON.stringify(r.window_days) + ' · 3 check-ins'; });
  await step('Visa granted → arrival plan', async () => { await admin().from('visa_cases').update({ status: 'granted', decision_on: new Date().toISOString().slice(0, 10) }).eq('id', S.visaId); const J = require('./journey'); const r = await J.plan(S.userId, 'GB', 'work'); const { count } = await admin().from('journey_tasks').select('id', { count: 'exact', head: true }).eq('user_id', S.userId); return (count || 0) + ' journey tasks'; });
  await step('Case view assembles the whole story', async () => { const CV = require('./caseview'); const v = await CV.view(S.userId, S.appId, { staff: true }); if (!(v.timeline || []).length) throw new Error('empty timeline'); return v.timeline.length + ' timeline events · ' + v.documents.length + ' documents · ' + v.visa_files.length + ' visa files'; });
  // ---------- 7. Admission evidence → share → invoice → clearance ----------
  await step('Fee receipt in the vault → enrolled → invoice', async () => { const { data: d, error } = await admin().from('documents').insert({ user_id: S.userId, application_id: S.appId, name: TAG + 'fee-receipt.pdf', kind: 'upload', doc_type: 'fee_receipt', generated: false, doc_status: 'read', extracted: { fields: { institution: S.instName, admission_number: 'ADM-' + stamp.slice(-5), amount_usd: 3000, tuition_usd: 12000, date: new Date().toISOString().slice(0, 10) } }, confidence: 0.9 }).select('id').single(); if (error) throw new Error(error.message); const P = require('./partners_engine'); const rec = await P.evidenceFromDocument(d.id); if (!rec) throw new Error('evidence not linked'); const { data: r } = await admin().from('partner_referrals').select('stage,share_usd,invoice_id,admission_number').eq('id', S.refId).maybeSingle(); if (!r || r.stage !== 'enrolled') throw new Error('stage ' + (r && r.stage)); if (!r.invoice_id) throw new Error('no invoice'); S.invId = r.invoice_id; return 'enrolled · adm ' + r.admission_number + ' · share $' + r.share_usd; });
  await step('Invoice cleared by payment reference', async () => { const P = require('./partners_engine'); await P.clear(S.invId, 'SIM-WIRE-' + stamp.slice(-4)); const { data: inv } = await admin().from('partner_invoices').select('status,ref,amount_usd').eq('id', S.invId).maybeSingle(); if (!inv || inv.status !== 'paid') throw new Error('status ' + (inv && inv.status)); return inv.ref + ' paid $' + inv.amount_usd; });
  await step('Dispute with evidence pack, then resolved', async () => { const P = require('./partners_engine'); const d = await P.openDispute({ institution_id: S.instId, invoice_id: S.invId, referral_id: S.refId, raised_by: 'platform', reason: 'SIM dispute' }); if (!d || !d.evidence || !d.evidence.referral) throw new Error('no evidence pack'); await P.resolveDispute(d.id, 'SIM resolved', 'paid'); return d.ref; });
  // ---------- 8. Consultancy ----------
  await step('Consultancy: create, refuse reserved name, add client, quota, protected partner', async () => { const O = require('./orgs'); let refused = false; try { await O.createOrg(S.ownerId, { name: 'Fori Foreign Sim Agency', kind: 'agency', country_code: 'PK' }); } catch (e) { refused = /reserved/.test(e.message); } if (!refused) throw new Error('reserved name accepted'); const org = await O.createOrg(S.ownerId, { name: TAG + 'Consultancy ' + stamp, kind: 'agency', country_code: 'PK' }); S.orgId = org.id || (org.org && org.org.id); const cl = await O.createClient(S.orgId, S.ownerId, { full_name: TAG + 'Client ' + stamp, email: 'sim-client-' + stamp + '@foriforeign.com', phone: '+923001234567', lane: 'study', stage: 'lead' }); S.clientId = cl && (cl.id || (cl.client && cl.client.id)); await admin().from('app_settings').upsert({ key: 'protected_partners:' + S.orgId, value: { names: ['SIM Protected University'] } }); return 'org ' + String(S.orgId).slice(0, 8) + ' · client ' + String(S.clientId || '').slice(0, 8); });
  await step('Consultancy: platform outreach refuses a protected partner', async () => { const P = require('./prospecting'); const why = await P.isProtected({ name: 'SIM Protected University', domain: '' }); if (!why) throw new Error('not protected'); return why; });
  await step('Consultancy: admin masking without a grant', async () => { const { data: o } = await admin().from('organisations').select('settings').eq('id', S.orgId).maybeSingle(); const grant = o && o.settings && o.settings.support_access_until && new Date(o.settings.support_access_until) > new Date(); return grant ? 'grant active (unexpected)' : 'masked'; });
  // ---------- 9. Content, language, SEO, notifications, agents ----------
  await step('SEO: destination pages and sitemap', async () => { const SEO = require('./seo'); const h = SEO.countryPage('GB', 'work'); const sm = SEO.sitemap([]); if (h.length < 2000) throw new Error('page too short'); if (!sm.includes('/work-in/gb')) throw new Error('sitemap missing'); return h.length + ' chars · sitemap ' + (sm.match(/<loc>/g) || []).length + ' urls'; });
  await step('Language and origin guides', async () => { const LG = require('./language_guide'); const EM = require('./emigration'); const W = require('./world'); return LG.guide('KR', 'labour').text.slice(0, 40) + ' · ' + EM.rules('PK').authority.slice(0, 30) + ' · ' + W.origin('BD').timezone; });
  await step('Labour lane: routes and classification', async () => { const L = require('./labour'); const s6 = require('./visa_seed6').seed; return s6.length + ' labour rules · ' + L.classify({ title: 'HGV Driver' }) + '/' + L.classify({ title: 'Senior Care Assistant' }); });
  await step('Notification → SSE fan-out path', async () => { const N = require('./notify'); await N.push(S.userId, 'sim', TAG + 'notification', 'The dummy case reached the end.', 'apps'); const { count } = await admin().from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', S.userId); return (count || 0) + ' notifications'; });
  await step('Self-heal sweep (no model)', async () => { const SH = require('./selfheal'); const r = await SH.heal(); return JSON.stringify(r).slice(0, 120); });
  await step('Audit chain seal + verify', async () => { const CH = require('./auditchain'); await admin().from('audit_log').insert({ actor: adminId || null, event: 'SIM_RUN', detail: stamp }); const s = await CH.seal(200); const v = await CH.verify(1); if (!v.ok) throw new Error('chain broken at ' + v.broken_at); return 'sealed ' + s.sealed + ' · verified ' + v.checked; });
  await step(full ? 'Daily brief built (model on)' : 'Daily brief function present (model off)', async () => { const DB = require('./dailybrief'); if (full) { const b = await DB.build(); return String(b && (b.narrative || b.summary) || '').slice(0, 80); } return typeof DB.build; });
  await step('Cost intelligence report', async () => { const CI = require('./costintel'); const r = await CI.report(); return 'ai $' + r.ai.total + ' · packages ' + r.packages.length; });
  const passed = steps.filter(s => s.ok).length; const report = { mode, stamp, started: new Date(t0).toISOString(), ms: Date.now() - t0, passed, failed: steps.length - passed, steps, ids: S };
  try { await admin().from('app_settings').upsert({ key: 'simulation:latest', value: report }); } catch (e) {}
  return report;
}
/* Purge everything the dummy run created (by tag), including the auth users. */
async function purge() {
  const out = {}; let ids = [];
  try { const { data: users } = await admin().from('profiles').select('id').like('full_name', TAG + '%'); ids = (users || []).map(u => u.id); } catch (e) {}
  const idList = ids.length ? ids : ['00000000-0000-0000-0000-000000000000'];
  for (const t of ['journey_tasks', 'notifications', 'case_messages', 'documents', 'offers', 'visa_cases', 'admission_records', 'partner_referrals', 'applications', 'consent_ledger', 'clients']) { try { const { count } = await admin().from(t).delete({ count: 'exact' }).in('user_id', idList); out[t] = count || 0; } catch (e) {} }
  try { const { data: inst } = await admin().from('institutions').select('id').like('name', TAG + '%'); const iids = (inst || []).map(i => i.id); if (iids.length) { for (const t of ['partner_invoices', 'partner_disputes', 'partner_liaison_log', 'partner_referrals']) { try { await admin().from(t).delete().in('institution_id', iids); } catch (e) {} } await admin().from('opportunities').delete().like('institution', TAG + '%'); await admin().from('institutions').delete().in('id', iids); } } catch (e) {}
  try { await admin().from('official_documents').delete().like('counterparty_name', TAG + '%'); } catch (e) {}
  try { const { data: orgs } = await admin().from('organisations').select('id').like('name', TAG + '%'); const oids = (orgs || []).map(o => o.id); if (oids.length) { for (const t of ['org_members', 'clients', 'org_subscriptions', 'quota_allocations', 'org_audit']) { try { await admin().from(t).delete().in('org_id', oids); } catch (e) {} } await admin().from('organisations').delete().in('id', oids); for (const o of oids) { try { await admin().from('app_settings').delete().eq('key', 'protected_partners:' + o); } catch (e) {} } } } catch (e) {}
  for (const id of ids) { try { await admin().from('profiles').delete().eq('id', id); } catch (e) {} try { await admin().auth.admin.deleteUser(id); } catch (e) {} }
  out.users = ids.length; return out;
}
module.exports = { run, purge, TAG };
