// lib/style.js — the house style every writer follows. Injected by the router into every 'case_writing' call so
// cover letters, statements, emails, proposals and MOUs share one voice: specific, human, the right length, no AI marks.
const LENGTH = { cover_letter: '280 to 380 words', motivation_letter: '350 to 450 words', sop: '600 to 800 words', personal_statement: '500 to 700 words', research_statement: '900 to 1200 words', email: '120 to 180 words', proposal: '350 to 450 words', mou: '900 to 1400 words', reply: '80 to 160 words', cv_summary: '60 to 90 words' };
const CONVENTIONS = { GB: 'British spelling; formal but plain; address the named person if known; no photo mention; dates day-month-year.', US: 'American spelling; direct; results first; dates month-day-year.', DE: 'For German positions: formal register (Sie), structured Anschreiben, mention start availability, no exaggeration; German spelling if writing in German.', AU: 'Australian spelling; plain, practical; address selection criteria if the posting lists them.', CA: 'Canadian spelling; bilingual courtesy where Quebec; mention work authorisation status plainly.', AE: 'Formal, respectful salutation; mention attested credentials and licensing readiness for regulated roles.', SA: 'Formal; mention attestation and SCFHS/DataFlow readiness for health roles.', QA: 'Formal; mention DHP/DataFlow readiness for health roles.', FR: 'Formal register; lettre de motivation structure if in French; mention language level.', NL: 'Direct, concise, informal-professional; results and fit.', SE: 'Plain, concise, modest tone; skills and contribution.', JP: 'Highly formal; humility; mention Japanese level; no self-praise.', SG: 'Concise, results-oriented; mention pass eligibility plainly.' };
function houseStyle(opts) {
  const o = opts || {}; const kind = o.kind || ''; const cc = String(o.cc || '').toUpperCase(); const len = LENGTH[kind] ? 'Length: ' + LENGTH[kind] + '.' : 'Length: as long as the content needs and no longer.';
  return ['HOUSE STYLE (follow exactly):', 'Write as one careful person, not a brochure or a machine. Plain professional English, varied sentence length, short paragraphs.', 'No long dashes (no em or en dashes), no bullet lists inside letters, no headings inside letters, no exclamation marks, no rhetorical questions, no quotation marks around ordinary words.', 'Banned words and phrases: delve, leverage, robust, seamless, synergy, holistic, cutting-edge, unlock, empower, game-changing, paradigm, navigate, in today\'s fast-paced, it is worth noting, furthermore, moreover, additionally, in conclusion, passionate about, I am writing to express, dynamic, innovative solutions, testament to.', 'Specificity: every claim about the applicant must rest on a fact from their CV or profile (a degree, a project, a number, a place, a date); cite at least three such facts; never invent a fact, a result, a grade, a publication, a name or a number; if a needed fact is missing write [add: what is missing] and nothing else in its place.', 'Fit: name the two or three requirements of THIS posting that the applicant meets and show how; say plainly what they will do in the first months if the posting implies it.', 'Honesty: no exaggeration, no claims about the institution that are not on its own page, no promises on behalf of the applicant.', len, cc && CONVENTIONS[cc] ? 'Destination conventions: ' + CONVENTIONS[cc] : '', 'Return only the document text.'].filter(Boolean).join('\n');
}
module.exports = { houseStyle, LENGTH, CONVENTIONS };
