// lib/success.js — an honest success estimate per case: not a promise, a calibrated view of the odds with the drivers
// that move them. Inputs: match score, quality/verification of the posting, eligibility flags, destination rules verified,
// documents ready, deadline distance, language proof, licence readiness, and the platform's own outcome history for the
// same destination and lane once it exists. Output: a band (low / fair / good / strong), a percentage range, and the
// three actions that would raise it. Shown before Send and on the case.
const { admin } = require('./supa');
async function estimate(userId, oppId, appId) {
  const [{ data: o }, { data: p }, { data: sc }] = await Promise.all([admin().from('opportunities').select('*').eq('id', oppId).maybeSingle(), admin().from('profiles').select('origin_country,profession,field,degree,total_experience_years,mobility').eq('id', userId).maybeSingle(), admin().from('opportunity_scores').select('score,eligible,reasons').eq('user_id', userId).eq('opportunity_id', oppId).maybeSingle()]);
  if (!o) throw new Error('Opportunity not found'); const drivers = []; let pts = 35;
  const match = sc ? Number(sc.score) || 0 : 50; pts += (match - 50) * 0.5; drivers.push({ driver: 'Profile match', value: match + '/100', effect: match >= 70 ? '+' : match < 40 ? '-' : '0' });
  const q = require('./discovery_quality').score(o); pts += (q.quality - 50) * 0.2; drivers.push({ driver: 'Posting confidence', value: q.label, effect: q.quality >= 75 ? '+' : q.quality < 50 ? '-' : '0' });
  if (o.eligibility_flag) { pts -= o.eligibility_flag === 'citizens_only' ? 40 : 20; drivers.push({ driver: 'Posting restriction', value: o.eligibility_flag.replace(/_/g, ' '), effect: '-' }); }
  if (o.visa_sponsorship === true) { pts += 8; drivers.push({ driver: 'Sponsorship stated', value: 'yes', effect: '+' }); }
  const { data: rules } = await admin().from('visa_rules').select('status,rule_type,value').eq('country_code', o.country_code).neq('status', 'superseded'); const rv = (rules || []).filter(r => r.status === 'verified').length, rt = (rules || []).length; if (rt) { pts += (rv / rt - 0.5) * 10; drivers.push({ driver: 'Destination rules verified', value: rv + '/' + rt, effect: rv / rt >= 0.5 ? '+' : '0' }); }
  let docsOk = null; try { const ck = await require('./vault').checklist(userId, o.kind === 'work' ? 'work' : 'study'); docsOk = ck.required.length ? ck.required.filter(r => r.state === 'ok').length / ck.required.length : null; if (docsOk != null) { pts += (docsOk - 0.5) * 16; drivers.push({ driver: 'Documents ready', value: Math.round(docsOk * 100) + '%', effect: docsOk >= 0.8 ? '+' : docsOk < 0.5 ? '-' : '0' }); } } catch (e) {}
  if (o.deadline) { const d = (new Date(o.deadline) - Date.now()) / 86400000; if (d < 0) { pts -= 40; drivers.push({ driver: 'Deadline', value: 'passed', effect: '-' }); } else if (d < 5) { pts -= 6; drivers.push({ driver: 'Deadline', value: Math.round(d) + ' days', effect: '-' }); } }
  const lang = (p && p.mobility && (p.mobility.ielts || p.mobility.english_test)) || null; if (o.req_language && o.req_language !== 'none' && !lang) { pts -= 8; drivers.push({ driver: 'Language proof', value: 'missing', effect: '-' }); }
  try { const { data: hist } = await admin().from('applications').select('status').eq('country_code', o.country_code).in('status', ['offer', 'rejected', 'interview']).limit(500); if (hist && hist.length >= 20) { const off = hist.filter(h => h.status === 'offer' || h.status === 'interview').length / hist.length; pts += (off - 0.3) * 20; drivers.push({ driver: 'Platform outcomes for ' + o.country_code, value: Math.round(off * 100) + '% reached interview or offer (' + hist.length + ' cases)', effect: off >= 0.3 ? '+' : '-' }); } } catch (e) {}
  pts = Math.max(3, Math.min(92, Math.round(pts))); const band = pts >= 70 ? 'strong' : pts >= 50 ? 'good' : pts >= 30 ? 'fair' : 'low';
  const raise = []; if (docsOk != null && docsOk < 1) raise.push('Complete the missing documents in the vault'); if (o.req_language && !lang) raise.push('Add your language test result'); if (rt && rv / rt < 0.5) raise.push('Ask us to verify the destination rules (verify-assist)'); if (match < 60) raise.push('Add the experience or projects that match the posting to your profile'); if (!raise.length) raise.push('Send early; earlier applications are read more carefully');
  const out = { band, range: [Math.max(1, pts - 12), Math.min(95, pts + 8)], point: pts, drivers: drivers.slice(0, 8), raise: raise.slice(0, 3), honesty: 'This is an estimate from your profile, the posting and our rules and outcomes; no platform can promise a result. Anyone who guarantees a visa or a job is not telling the truth.' };
  if (appId) { try { await admin().from('applications').update({ success_estimate: out }).eq('id', appId).eq('user_id', userId); } catch (e) {} } return out;
}
module.exports = { estimate };
