// lib/visa_seed5.js — completion pass: study fee/PR rules for the seed2 routes, and dentist/physiotherapist licence
// rules for every destination that has a health regulator on record (same authority as the doctor rule unless a
// separate board exists in the seeds). All UNVERIFIED with sources.
const { seed: s2 } = require('./visa_seed2'); const { seed: s3 } = require('./visa_seed3'); const { seed: s1 } = require('./visa_seed');
const P = require('./professions').P;
const seed = [];
const routes2 = {}; for (const r of s2) routes2[r.country_code] = routes2[r.country_code] || r;
const FEE_PR = { NL: ['https://ind.nl/en/fees', 'https://ind.nl/en/residence-permits/permanent-residence'], SE: ['https://www.migrationsverket.se/English/Private-individuals/Studying-and-researching-in-Sweden/Higher-education/Fees.html', 'https://www.migrationsverket.se/English/Private-individuals/Working-in-Sweden/Employed/Permanent-residence-permit.html'], FI: ['https://migri.fi/en/processing-fees', 'https://migri.fi/en/permanent-residence-permit'], NO: ['https://www.udi.no/en/word-definitions/fees/', 'https://www.udi.no/en/want-to-apply/permanent-residence/'], DK: ['https://www.nyidanmark.dk/en-GB/You-want-to-apply/Fees', 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Permanent-residence-permit'], IT: ['https://vistoperitalia.esteri.it/home/en', 'https://www.interno.gov.it/'], FR: ['https://france-visas.gouv.fr/en/web/france-visas/visa-fees', 'https://www.service-public.fr/particuliers/vosdroits/N110'], ES: ['https://www.exteriores.gob.es/', 'https://www.inclusion.gob.es/web/migraciones'], PL: ['https://www.gov.pl/web/udsc-en', 'https://www.gov.pl/web/udsc-en/permanent-residence'], NZ: ['https://www.immigration.govt.nz/new-zealand-visas/preparing-a-visa-application/fees-and-costs', 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/skilled-migrant-category-resident-visa'] };
for (const [cc, r] of Object.entries(routes2)) {
  const [feeU, prU] = FEE_PR[cc] || [r.source_url, r.source_url];
  seed.push({ country_code: cc, route_key: r.route_key, route_name: r.route_name, lane: 'study', rule_type: 'fee', text: 'Visa/permit application fee as listed on the official fee page (figure recorded at verification).', source_url: feeU, source_title: r.source_title });
  if (!s2.some(x => x.country_code === cc && x.rule_type === 'pr_path')) seed.push({ country_code: cc, route_key: r.route_key, route_name: r.route_name, lane: 'study', rule_type: 'pr_path', text: 'After graduation: a job-search stay where the country offers one, then a work residence permit with an employer, then long-term residence after the qualifying years (EU: 5 years).', source_url: prU, source_title: r.source_title });
  if (!s2.some(x => x.country_code === cc && x.rule_type === 'dependants')) seed.push({ country_code: cc, route_key: r.route_key, route_name: r.route_name, lane: 'study', rule_type: 'dependants', text: 'Family reunification for students depends on funds and housing; check the authority page for the current rule.', source_url: prU, source_title: r.source_title });
}
// Dentist and physiotherapist licence rules where a doctor rule exists but no dentist/physio rule does.
const all = s1.concat(s2, s3); const seen = new Set(all.filter(r => r.rule_type === 'licence').map(r => r.country_code + '|' + (r.value && r.value.profession)));
for (const prof of ['dentist', 'physiotherapist']) for (const [cc, v] of Object.entries(P[prof] || {})) { if (cc === 'isco') continue; seen.add(cc + '|' + prof); }
const docRules = all.filter(r => r.rule_type === 'licence' && r.value && r.value.profession === 'doctor');
for (const d of docRules) for (const prof of ['dentist', 'physiotherapist']) if (!seen.has(d.country_code + '|' + prof)) { seen.add(d.country_code + '|' + prof); seed.push({ country_code: d.country_code, route_key: d.country_code.toLowerCase() + '_licence_' + prof, route_name: 'Licence: ' + prof + ' in ' + d.country_code, lane: 'work', rule_type: 'licence', text: (prof === 'dentist' ? 'Dentists: ' : 'Physiotherapists: ') + 'recognition and registration with the same national health authority that licenses doctors (' + d.text.split(/[;,(]/)[0].trim() + '); a separate professional board may apply, verify on the source.', value: { profession: prof, isco: prof === 'dentist' ? '2261' : '2264' }, source_url: d.source_url, source_title: d.source_title }); }
module.exports = { seed };
