// lib/visa_strategy.js — HOW A VISA STATUS IS LEARNED, in order of trust and least intrusion:
//   1. the decision email on the applicant's ForiForeign address (read by the mail reader) — nothing else is touched;
//   2. the applicant or the consultant updates it by hand (with the date and a note);
//   3. only after the country's usual processing time has passed, ONE portal check (the connected portal, or a Portal Assist prompt);
//      if the portal blocks or fails, no second attempt: the applicant and the consultancy are told to check by hand.
// Never daily. Every step keyed to the specific open case: country, route, submitted date, tracking reference.
const { admin } = require('./supa');
async function planAfterSubmit(visaCaseId) { const { data: f } = await admin().from('visa_cases').select('id,user_id,country_code,route_key,submitted_on,expected_decision_to,expected_decision_from').eq('id', visaCaseId).maybeSingle(); if (!f) return null; let to = f.expected_decision_to; if (!to) { try { const C = require('./checkins'); const r = await C.schedule(visaCaseId); to = r && r.expected_decision_to; } catch (e) {} } const base = to ? new Date(to) : new Date(new Date(f.submitted_on || Date.now()).getTime() + 45 * 86400000); const checkAfter = new Date(base.getTime() + 3 * 86400000).toISOString().slice(0, 10); await admin().from('visa_cases').update({ check_after: checkAfter, check_attempts: 0, decision_source: null, check_note: 'One status check after ' + checkAfter + ' unless a decision email or a manual update comes first.' }).eq('id', visaCaseId); return { check_after: checkAfter }; }
async function manualUpdate(visaCaseId, userId, { status, decided_on, note, by }) { const allowed = ['submitted', 'decision_pending', 'granted', 'refused', 'withdrawn']; const st = allowed.includes(status) ? status : null; if (!st) throw new Error('status must be one of ' + allowed.join(', ')); const patch = { status: st, decision_source: 'manual', manual_note: String(note || '').slice(0, 300) || null, updated_at: new Date().toISOString() }; if (st === 'granted' || st === 'refused') patch.decision_on = decided_on || new Date().toISOString().slice(0, 10); const { data: upd } = await admin().from('visa_cases').update(patch).eq('id', visaCaseId).eq('user_id', userId).select('id'); if (!upd || !upd.length) { const e = new Error('Visa file not found'); e.status = 404; throw e; } try { await require('./notify').push(userId, 'visa', 'Visa status set by ' + (by || 'you') + ': ' + st, patch.manual_note || '', 'profile'); } catch (e) {} return patch; }
async function markFromEmail(visaCaseId, status) { await admin().from('visa_cases').update({ status, decision_source: 'email', decision_on: (status === 'granted' || status === 'refused') ? new Date().toISOString().slice(0, 10) : null, updated_at: new Date().toISOString() }).eq('id', visaCaseId); }
/* The single check, only when due. Uses the connected portal (headless watch) if one exists for this applicant; otherwise asks the applicant (and the consultancy) to run Portal Assist or update by hand. */
async function sweep() { const today = new Date().toISOString().slice(0, 10); const { data: files } = await admin().from('visa_cases').select('id,user_id,country_code,route_key,tracking_ref,check_after,check_attempts,status').in('status', ['submitted', 'decision_pending']).lte('check_after', today).eq('check_attempts', 0).limit(200); let checked = 0, asked = 0; const N = require('./notify'); for (const f of (files || [])) { await admin().from('visa_cases').update({ check_attempts: 1 }).eq('id', f.id); let result = null; try { const { data: conn } = await admin().from('portal_connections').select('id,portal_name').eq('user_id', f.user_id).eq('status', 'active').eq('consent', true).limit(1); if (conn && conn[0]) { const B = require('./browserbot'); result = await B.watch(conn[0].id).catch(e => ({ error: e.message })); } } catch (e) { result = { error: e.message }; } const WORDS = [[/(granted|approved|issued|visa has been issued)/i, 'granted'], [/(refused|rejected|denied|unsuccessful)/i, 'refused'], [/(under process|in process|processing|being processed|under review|pending|received|submitted)/i, 'processing'], [/(additional documents|further documents|request for information)/i, 'documents requested'], [/(dispatched|ready for collection|collect your passport|courier)/i, 'ready for collection']]; const label = result && !result.error && result.outcome && result.outcome !== 'blocked' && result.status_text ? ((WORDS.find(([re]) => re.test(result.status_text)) || [null, null])[1]) : null; if (result && result.outcome === 'blocked') result.error = result.error || 'blocked'; const orgIds = []; try { const { data: cl } = await admin().from('clients').select('org_id').eq('user_id', f.user_id).limit(3); for (const c of (cl || [])) if (c.org_id) orgIds.push(c.org_id); } catch (e) {} const tellOrg = async (title, body) => { for (const oid of orgIds) { const { data: mem } = await admin().from('org_members').select('user_id').eq('org_id', oid).eq('status', 'active').in('role', ['owner', 'manager', 'consultant']).limit(20); for (const m of (mem || [])) await N.push(m.user_id, 'visa', title, body, 'work', oid); } };
    if (result && !result.error && label && /granted|refused|processing|documents|collection/.test(label)) { const st = /granted/.test(label) ? 'granted' : /refused/.test(label) ? 'refused' : 'decision_pending'; await admin().from('visa_cases').update({ status: st, decision_source: 'portal', decision_on: (st === 'granted' || st === 'refused') ? today : null, check_note: 'Portal checked once on ' + today + ': ' + label, updated_at: new Date().toISOString() }).eq('id', f.id); await N.push(f.user_id, 'visa', 'Visa status from the portal: ' + label, 'Checked once, after the usual processing time for ' + f.country_code + '.', 'profile'); await tellOrg('Client visa status: ' + label, 'Portal checked once after the processing window.'); checked++; }
    else { const why = result && result.error ? 'The portal could not be read (' + String(result.error).slice(0, 80) + ').' : 'No portal is connected for this file.'; await admin().from('visa_cases').update({ check_note: why + ' Please check by hand and update the status; no automatic retry will be made.' }).eq('id', f.id); await N.push(f.user_id, 'visa', 'Please check your visa status by hand', why + ' The usual processing time for ' + f.country_code + ' has passed. Open the portal, or run Portal Assist, then update the status here. We will not try again automatically.', 'profile'); await tellOrg('Client visa: please check by hand', why + ' Processing time passed; update the status on the client\'s visa file.'); asked++; } }
  return { checked, asked }; }
module.exports = { planAfterSubmit, manualUpdate, markFromEmail, sweep };
