// lib/visa_tracking.js — the honest answer to "real-time visa tracking for 54 countries":
// no government publishes a public status API; tracking happens on the official/VFS portal with
// the applicant's own reference. ForiForeign gives, per destination, the official tracking page,
// keeps the applicant's own status log, and (Phase 3 partners) receives live status from
// lodgement partners where they exist. Entries are sourced and marked for verification.
const T = {
  GB: ['https://www.gov.uk/track-your-visa-application', 'GOV.UK - Track your visa application (via VFS/TLS)'], IE: ['https://www.irishimmigration.ie/visa-decisions/', 'Irish Immigration Service - Visa decisions'], DE: ['https://digital.diplo.de/', 'German Federal Foreign Office - Consular services portal'], FR: ['https://france-visas.gouv.fr/en/web/france-visas/suivi-de-demande', 'France-Visas - Track your application'],
  NL: ['https://ind.nl/en/service-contact/track-your-application', 'IND - Track your application'], SE: ['https://www.migrationsverket.se/English/Contact-us/Check-your-application.html', 'Swedish Migration Agency - Check your application'], FI: ['https://enterfinland.fi/', 'Enter Finland'], NO: ['https://www.udi.no/en/checklists-and-application-status/', 'UDI - Application status'], DK: ['https://www.nyidanmark.dk/en-GB/Applying/Check-status-of-your-case', 'New to Denmark - Check case status'],
  IT: ['https://vistoperitalia.esteri.it/home/en', 'Visa for Italy (status via VFS Global)'], ES: ['https://sutramiteconsular.maec.es/', 'Spain - Consular application status'], PL: ['https://www.gov.pl/web/udsc-en', 'Office for Foreigners (status via VFS)'], PT: ['https://aima.gov.pt/', 'AIMA Portugal'], AT: ['https://www.migration.gv.at/en/', 'Migration Austria'], BE: ['https://dofi.ibz.be/en', 'Belgian Immigration Office'], CH: ['https://www.sem.admin.ch/', 'SEM Switzerland'],
  US: ['https://ceac.state.gov/CEACStatTracker/Status.aspx', 'US CEAC visa status check'], CA: ['https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-status.html', 'IRCC - Check application status'], AU: ['https://online.immi.gov.au/lusc/login', 'ImmiAccount'], NZ: ['https://onlineservices.immigration.govt.nz/', 'Immigration NZ online services'],
  AE: ['https://smartservices.icp.gov.ae/echannels/web/client/default.html#/fileValidity', 'ICP smart services - status'], SA: ['https://visa.mofa.gov.sa/VisaInquiry', 'Saudi visa inquiry (MOFA)'], QA: ['https://portal.moi.gov.qa/wps/portal/MOIInternet/services/inquiries/visaservices', 'Qatar MOI - Visa inquiry'], OM: ['https://evisa.rop.gov.om/', 'ROP eVisa - track'], BH: ['https://www.evisa.gov.bh/', 'Bahrain eVisa - track'], KW: ['https://www.moi.gov.kw/', 'Kuwait MOI'],
  TR: ['https://www.evisa.gov.tr/en/status/', 'Türkiye e-Visa status'], MY: ['https://visa.educationmalaysia.gov.my/guidelines/track-your-application.html', 'EMGS - Track your application'], SG: ['https://www.ica.gov.sg/', 'ICA e-Services'], JP: ['https://www.mofa.go.jp/', 'Japan MOFA'], KR: ['https://www.hikorea.go.kr/', 'HiKorea'], CN: ['https://www.visaforchina.cn/', 'China Visa Application Service Center - track'], HK: ['https://www.immd.gov.hk/eng/status_enquiry/index.html', 'Hong Kong ImmD - status enquiry'], TW: ['https://www.boca.gov.tw/', 'Taiwan BOCA'], TH: ['https://www.thaievisa.go.th/', 'Thailand e-Visa'],
  AZ: ['https://evisa.gov.az/en/', 'Azerbaijan ASAN Visa - status'], GE: ['https://www.geoconsul.gov.ge/en', 'Georgia e-Visa - status'], UZ: ['https://e-visa.gov.uz/', 'Uzbekistan e-Visa - status'], KZ: ['https://www.gov.kz/', 'Kazakhstan MFA'], EE: ['https://www.politsei.ee/en', 'Estonian PBGB'], LV: ['https://www.pmlp.gov.lv/en', 'OCMA Latvia'], LT: ['https://migracija.lrv.lt/en/', 'Lithuanian Migration Department (MIGRIS)'], HU: ['https://enterhungary.gov.hu/', 'Enter Hungary'], CZ: ['https://www.mvcr.cz/mvcren/', 'Czech MOI'], SK: ['https://www.mic.iom.sk/en/', 'MIC Slovakia'], SI: ['https://www.gov.si/en/', 'Slovenia gov.si'], HR: ['https://mup.gov.hr/', 'Croatia MUP'], BG: ['https://www.mfa.bg/en', 'Bulgaria MFA'], RO: ['https://igi.mai.gov.ro/en/', 'Romania IGI'], GR: ['https://migration.gov.gr/en/', 'Greece Migration'], CY: ['https://www.moi.gov.cy/', 'Cyprus CRMD'], MT: ['https://identita.gov.mt/', 'Identità Malta'], LU: ['https://guichet.public.lu/en/', 'Guichet.lu'], BN: ['https://www.immigration.gov.bn/', 'Brunei Immigration']
};
const VFS = 'https://www.vfsglobal.com/en/individuals/track-your-application.html';
module.exports = { TRACK: T, VFS, trackingFor: cc => ({ official: T[cc] ? { url: T[cc][0], title: T[cc][1] } : null, vfs: { url: VFS, title: 'VFS Global - track your application (where the mission uses VFS)' }, live_api: false, note: 'Governments do not publish public status APIs. Track with your own reference on the official page; record each status change here so your consultant and your checklist follow it. Live status arrives automatically only through a lodgement partner (e.g. Australia/New Zealand).' }) };
