// lib/visa_portals.js — Day 8 · the official immigration entry point for every one of the 54
// destinations. Seeded as an UNVERIFIED "note" rule with its source so no destination is ever
// blank; the team verifies and expands each one from the admin Visa-rules screen.
const P = {
  DE: ['https://www.make-it-in-germany.com/en/visa-residence', 'Make it in Germany - Visa & residence'], NO: ['https://www.udi.no/en/', 'UDI - Norwegian Directorate of Immigration'], FI: ['https://migri.fi/en/home', 'Migri - Finnish Immigration Service'],
  SE: ['https://www.migrationsverket.se/English.html', 'Swedish Migration Agency'], DK: ['https://www.nyidanmark.dk/en-GB', 'New to Denmark'], NL: ['https://ind.nl/en', 'IND - Immigration and Naturalisation Service'], AT: ['https://www.migration.gv.at/en/', 'Migration Austria'],
  BE: ['https://dofi.ibz.be/en', 'Belgian Immigration Office'], IE: ['https://www.irishimmigration.ie/', 'Irish Immigration Service'], GB: ['https://www.gov.uk/browse/visas-immigration', 'GOV.UK - Visas and immigration'], PL: ['https://www.gov.pl/web/udsc-en', 'Office for Foreigners, Poland'],
  CZ: ['https://www.mvcr.cz/mvcren/article/third-country-nationals.aspx', 'Czech Ministry of the Interior'], HU: ['https://enterhungary.gov.hu/', 'Enter Hungary'], EE: ['https://www.politsei.ee/en/instructions/residence-permits', 'Estonian Police and Border Guard'], LV: ['https://www.pmlp.gov.lv/en', 'OCMA Latvia'],
  LT: ['https://migracija.lrv.lt/en/', 'Migration Department, Lithuania'], PT: ['https://aima.gov.pt/', 'AIMA Portugal'], ES: ['https://www.inclusion.gob.es/web/migraciones', 'Spain - Migraciones'], IT: ['https://vistoperitalia.esteri.it/home/en', 'Visa for Italy'], FR: ['https://france-visas.gouv.fr/en/', 'France-Visas'],
  CH: ['https://www.sem.admin.ch/sem/en/home.html', 'SEM Switzerland'], LU: ['https://guichet.public.lu/en/citoyens/immigration.html', 'Guichet.lu - Immigration'], MT: ['https://identita.gov.mt/', 'Identità Malta'], CY: ['https://www.moi.gov.cy/moi/crmd/crmd.nsf/index_en/index_en', 'Cyprus Civil Registry and Migration'], GR: ['https://migration.gov.gr/en/', 'Greek Ministry of Migration'],
  HR: ['https://mup.gov.hr/aliens-281621/281621', 'Croatia MUP - Aliens'], SI: ['https://www.gov.si/en/topics/entry-and-residence-of-foreigners/', 'Slovenia - Entry and residence'], SK: ['https://www.mic.iom.sk/en/', 'Migration Information Centre Slovakia'], BG: ['https://www.mfa.bg/en/services-travel/consular-services/travel-bulgaria/visa-bulgaria', 'Bulgaria MFA - Visas'], RO: ['https://igi.mai.gov.ro/en/', 'Romanian General Inspectorate for Immigration'],
  US: ['https://travel.state.gov/content/travel/en/us-visas.html', 'US Department of State - Visas'], CA: ['https://www.canada.ca/en/immigration-refugees-citizenship.html', 'IRCC Canada'], AU: ['https://immi.homeaffairs.gov.au/', 'Australian Home Affairs'], NZ: ['https://www.immigration.govt.nz/', 'Immigration New Zealand'],
  AE: ['https://u.ae/en/information-and-services/visa-and-emirates-id', 'u.ae - Visa and Emirates ID'], SA: ['https://visa.mofa.gov.sa/', 'Saudi Visa Platform'], QA: ['https://hukoomi.gov.qa/en/', 'Hukoomi Qatar'], OM: ['https://evisa.rop.gov.om/', 'Royal Oman Police eVisa'], BH: ['https://www.evisa.gov.bh/', 'Bahrain eVisa'], KW: ['https://www.moi.gov.kw/', 'Kuwait Ministry of Interior'],
  TR: ['https://www.evisa.gov.tr/en/', 'Türkiye e-Visa'], AZ: ['https://evisa.gov.az/en/', 'Azerbaijan ASAN Visa'], GE: ['https://www.geoconsul.gov.ge/en', 'Georgia e-Visa portal'], KZ: ['https://www.gov.kz/memleket/entities/mfa?lang=en', 'Kazakhstan MFA'], UZ: ['https://e-visa.gov.uz/', 'Uzbekistan e-Visa'],
  MY: ['https://www.imi.gov.my/', 'Immigration Department of Malaysia'], SG: ['https://www.ica.gov.sg/', 'ICA Singapore'], JP: ['https://www.mofa.go.jp/j_info/visit/visa/index.html', 'Japan MOFA - Visa'], KR: ['https://www.hikorea.go.kr/', 'HiKorea'], CN: ['https://www.visaforchina.cn/', 'China Visa Application Service Center'], HK: ['https://www.immd.gov.hk/eng/', 'Hong Kong Immigration Department'],
  TW: ['https://www.boca.gov.tw/mp-2.html', 'Taiwan BOCA'], TH: ['https://www.thaievisa.go.th/', 'Thailand e-Visa'], BN: ['https://www.immigration.gov.bn/', 'Brunei Immigration']
};
module.exports = { PORTALS: P, portalRules: () => Object.entries(P).map(([cc, [url, title]]) => ({ country_code: cc, route_key: cc.toLowerCase() + '_entry', route_name: 'Official immigration entry point', lane: 'both', rule_type: 'note', text: 'Official immigration portal for ' + cc + '. Requirements, fees and processing times for every route start here; the team records specific routes for this destination from this source.', value: {}, source_url: url, source_title: title })) };
