// lib/visa_seed.js — starting rules for the first ten destinations.
// EVERY entry is seeded as UNVERIFIED with its official source page. The admin verifies each rule
// against that page (one tap) before it is shown as a fact; until then the UI labels it "verify".
// Amounts and thresholds are intentionally omitted where they change often; the source page is the
// authority and the verifier records the current figure into `value` at verification time.
const S = (country_code, route_key, route_name, lane, rules) => rules.map(r => Object.assign({ country_code, route_key, route_name, lane }, r));
const doc = (doc_type, text, extra) => Object.assign({ rule_type: 'document', text, value: { doc_type } }, extra || {});
const seed = [
  ...S('GB', 'uk_student', 'UK Student visa', 'study', [
    { rule_type: 'eligibility', text: 'Unconditional offer (CAS) from a licensed student sponsor is required before applying.', source_url: 'https://www.gov.uk/student-visa', source_title: 'GOV.UK - Student visa' },
    { rule_type: 'financial', text: 'Show funds for course fees for the first year plus living costs for up to 9 months, held for 28 consecutive days (unless exempt).', value: { per: 'month', months: 9 }, source_url: 'https://www.gov.uk/student-visa/money', source_title: 'GOV.UK - Student visa: money' },
    { rule_type: 'language', text: 'English at CEFR B2 for degree level (B1 below degree), via an approved SELT or an exempting qualification.', value: { cefr: 'B2' }, source_url: 'https://www.gov.uk/student-visa/knowledge-of-english', source_title: 'GOV.UK - Knowledge of English' },
    { rule_type: 'fee', text: 'Application fee plus the Immigration Health Surcharge per year of leave.', source_url: 'https://www.gov.uk/student-visa/how-much-it-costs', source_title: 'GOV.UK - Costs' },
    { rule_type: 'processing', text: 'Apply up to 6 months before the course starts; standard decision is usually 3 weeks from outside the UK.', value: { days: 21 }, source_url: 'https://www.gov.uk/student-visa/apply', source_title: 'GOV.UK - Apply' },
    doc('passport', 'Valid passport with a blank page.'), doc('admission_letter', 'CAS reference and the offer letter.'), doc('bank_statement', '28-day funds evidence (bank statement / official financial sponsorship letter).'), doc('language_test', 'SELT certificate or exemption evidence.'), doc('degree', 'Academic qualifications named on the CAS.'), doc('photo', 'Biometric photo taken at the visa application centre.'),
    { rule_type: 'work_rights', text: 'Term-time work limited to 20 hours a week for degree-level students; full-time in vacations.', source_url: 'https://www.gov.uk/student-visa', source_title: 'GOV.UK - Student visa' },
    { rule_type: 'dependants', text: 'Dependants are only allowed for postgraduate research programmes and government-sponsored students (rules changed January 2024).', source_url: 'https://www.gov.uk/student-visa/family-members', source_title: 'GOV.UK - Family members' },
    { rule_type: 'pr_path', text: 'Graduate visa (2 years, 3 for PhD) after completing the course; Skilled Worker route can lead to settlement.', source_url: 'https://www.gov.uk/graduate-visa', source_title: 'GOV.UK - Graduate visa' }
  ]),
  ...S('GB', 'uk_skilled_worker', 'UK Skilled Worker visa', 'work', [
    { rule_type: 'eligibility', text: 'A Certificate of Sponsorship from a licensed sponsor for an eligible occupation, paid at or above the route salary threshold and the occupation going rate.', source_url: 'https://www.gov.uk/skilled-worker-visa', source_title: 'GOV.UK - Skilled Worker visa' },
    { rule_type: 'language', text: 'English at CEFR B1.', value: { cefr: 'B1' }, source_url: 'https://www.gov.uk/skilled-worker-visa/knowledge-of-english', source_title: 'GOV.UK - Knowledge of English' },
    { rule_type: 'financial', text: 'Maintenance funds unless the sponsor certifies maintenance on the CoS.', source_url: 'https://www.gov.uk/skilled-worker-visa/documents-you-must-provide', source_title: 'GOV.UK - Documents' },
    doc('passport', 'Valid passport.'), doc('offer_letter', 'Certificate of Sponsorship reference and the job offer.'), doc('language_test', 'SELT or exemption.'), doc('police_certificate', 'Criminal record certificate for certain occupations (health, education, social care).'),
    { rule_type: 'pr_path', text: 'Settlement after 5 years of continuous residence on the route (subject to rule changes).', source_url: 'https://www.gov.uk/skilled-worker-visa', source_title: 'GOV.UK - Skilled Worker visa' }
  ]),
  ...S('DE', 'de_national_study', 'Germany national visa for study', 'study', [
    { rule_type: 'eligibility', text: 'Admission letter (Zulassung) or conditional admission from a German university, or Studienkolleg placement.', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/study', source_title: 'Make it in Germany - Study visa' },
    { rule_type: 'financial', text: 'Proof of funds for one year, usually a blocked account (Sperrkonto) at the amount set annually by the federal government, or a scholarship / formal obligation letter.', value: { per: 'year', instrument: 'blocked_account' }, source_url: 'https://www.auswaertiges-amt.de/en/visa-service/buergerservice/faq/-/606848', source_title: 'Federal Foreign Office - Studying in Germany' },
    { rule_type: 'language', text: 'Language proof matching the programme language (German for German-taught, English for English-taught).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/study', source_title: 'Make it in Germany' },
    { rule_type: 'processing', text: 'Appointments at the German mission in Pakistan can take months; apply as soon as admission is confirmed.', source_url: 'https://pakistan.diplo.de', source_title: 'German Missions in Pakistan' },
    doc('passport', 'Passport valid beyond the intended stay.'), doc('admission_letter', 'University admission letter.'), doc('bank_statement', 'Blocked account confirmation or scholarship award / obligation letter.'), doc('insurance', 'Travel health insurance for the entry period.'), doc('degree', 'Degrees and transcripts, with APS certificate where required for Pakistani applicants.'), doc('language_test', 'Language certificate.'), doc('photo', 'Biometric photos.'), doc('sop', 'Motivation letter / CV.'),
    { rule_type: 'work_rights', text: 'Students may work 140 full days or 280 half days a year (from March 2024).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/study', source_title: 'Make it in Germany' },
    { rule_type: 'pr_path', text: '18-month job-seeker residence after graduation; settlement possible after qualifying employment (Skilled Immigration Act).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/study', source_title: 'Make it in Germany' }
  ]),
  ...S('DE', 'de_skilled_worker', 'Germany skilled worker / EU Blue Card', 'work', [
    { rule_type: 'eligibility', text: 'Recognised qualification (or comparable) and a concrete job offer; Blue Card needs a university degree and a salary above the annual threshold (lower for shortage occupations).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', source_title: 'Make it in Germany - EU Blue Card' },
    { rule_type: 'eligibility', text: 'Regulated professions (doctors, pharmacists, nurses, teachers) require professional recognition before or as part of the visa.', source_url: 'https://www.anerkennung-in-deutschland.de/en', source_title: 'Recognition in Germany' },
    doc('passport', 'Valid passport.'), doc('contract', 'Employment contract / binding job offer.'), doc('degree', 'Degree with recognition (anabin / ZAB statement of comparability).'), doc('licence', 'Professional licence for regulated professions.'), doc('cv', 'CV.'),
    { rule_type: 'pr_path', text: 'Blue Card holders may qualify for settlement after 27 months (21 with B1 German).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', source_title: 'Make it in Germany' }
  ]),
  ...S('CA', 'ca_study_permit', 'Canada study permit', 'study', [
    { rule_type: 'eligibility', text: 'Letter of acceptance from a Designated Learning Institution and, for most applicants, a Provincial/Territorial Attestation Letter.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html', source_title: 'IRCC - Study permit' },
    { rule_type: 'financial', text: 'Proof of funds for tuition plus the living-cost amount set by IRCC (raised in 2024); check the current figure on the page.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/get-documents.html', source_title: 'IRCC - Documents' },
    { rule_type: 'language', text: 'Language test as required by the institution; a test may be required for expedited streams.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html', source_title: 'IRCC' },
    doc('passport', 'Valid passport.'), doc('admission_letter', 'Letter of acceptance.'), doc('bank_statement', 'Proof of financial support (GIC accepted in some streams).'), doc('photo', 'Photo.'), doc('police_certificate', 'Police certificate if requested.'), doc('sop', 'Statement of purpose / explanation letter.'),
    { rule_type: 'processing', text: 'Biometrics and possibly a medical exam; processing times are published per country.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html', source_title: 'IRCC - Processing times' },
    { rule_type: 'work_rights', text: 'Off-campus work allowed up to the weekly cap set by IRCC during term.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/work-off-campus.html', source_title: 'IRCC - Work off campus' },
    { rule_type: 'pr_path', text: 'Post-Graduation Work Permit (eligibility narrowed in 2024) then Express Entry / provincial nomination.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation/about.html', source_title: 'IRCC - PGWP' }
  ]),
  ...S('AU', 'au_500', 'Australia Student visa (subclass 500)', 'study', [
    { rule_type: 'eligibility', text: 'Confirmation of Enrolment (CoE) and the Genuine Student requirement.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500', source_title: 'Home Affairs - Student visa 500' },
    { rule_type: 'financial', text: 'Evidence of funds for living costs (amount set by Home Affairs), course fees and travel, or a sponsor income alternative.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500', source_title: 'Home Affairs' },
    { rule_type: 'language', text: 'English test at the level set for the visa (raised in 2024) unless exempt.', source_url: 'https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language', source_title: 'Home Affairs - English requirements' },
    doc('passport', 'Valid passport.'), doc('admission_letter', 'CoE.'), doc('insurance', 'Overseas Student Health Cover for the full stay.'), doc('bank_statement', 'Financial capacity evidence.'), doc('language_test', 'English test result.'), doc('sop', 'Genuine Student statement.'),
    { rule_type: 'work_rights', text: 'Work capped at 48 hours a fortnight during term.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500', source_title: 'Home Affairs' },
    { rule_type: 'pr_path', text: 'Temporary Graduate visa (485) after study, then skilled migration streams.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485', source_title: 'Home Affairs - 485' }
  ]),
  ...S('AE', 'ae_employment', 'UAE employment visa / work permit', 'work', [
    { rule_type: 'eligibility', text: 'Employer-sponsored: the employer applies for the work permit and entry visa through MOHRE / the relevant free zone.', source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-working-in-the-uae', source_title: 'u.ae - Residence visa for working' },
    { rule_type: 'eligibility', text: 'Degree attestation (MOFA Pakistan then UAE) and, for healthcare, DHA/DOH/MOHAP licensing before practice.', source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id', source_title: 'u.ae' },
    doc('passport', 'Passport valid at least 6 months.'), doc('offer_letter', 'Signed offer letter / contract.'), doc('degree', 'Attested degree.'), doc('photo', 'Photo, white background.'), doc('licence', 'Professional licence (healthcare, engineering, teaching).'),
    { rule_type: 'processing', text: 'Medical fitness test and Emirates ID after entry; residence stamped after.', source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id', source_title: 'u.ae' },
    { rule_type: 'dependants', text: 'Family sponsorship possible above a minimum salary set by the authority.', source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/sponsoring-family-residency-visa', source_title: 'u.ae - Family sponsorship' },
    { rule_type: 'pr_path', text: 'Golden Visa (10 years) for specified professions, researchers and high earners.', source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/golden-visa', source_title: 'u.ae - Golden visa' }
  ]),
  ...S('SA', 'sa_work', 'Saudi Arabia work visa (Iqama)', 'work', [
    { rule_type: 'eligibility', text: 'Employer obtains a block visa and work visa authorisation; the applicant applies through the Saudi mission / Enjaz.', source_url: 'https://www.mofa.gov.sa', source_title: 'Saudi Ministry of Foreign Affairs' },
    { rule_type: 'eligibility', text: 'Healthcare professionals require Saudi Commission for Health Specialties (SCFHS) classification (Mumaris Plus / DataFlow).', source_url: 'https://scfhs.org.sa', source_title: 'SCFHS' },
    doc('passport', 'Passport valid at least 6 months.'), doc('contract', 'Employment contract attested.'), doc('degree', 'Attested degree (MOFA + Saudi Culture attestation).'), doc('police_certificate', 'Police character certificate.'), doc('photo', 'Photos.'), doc('licence', 'SCFHS classification for health roles.'),
    { rule_type: 'processing', text: 'GAMCA / Wafid medical examination is required before the visa is issued.', source_url: 'https://wafid.com', source_title: 'Wafid (medical)' },
    { rule_type: 'dependants', text: 'Family visas (Iqama for dependants) available subject to profession and salary.', source_url: 'https://www.mofa.gov.sa', source_title: 'MOFA' }
  ]),
  ...S('QA', 'qa_work', 'Qatar work visa', 'work', [
    { rule_type: 'eligibility', text: 'Employer sponsorship through the Ministry of Labour; contract approval precedes the visa.', source_url: 'https://hukoomi.gov.qa', source_title: 'Hukoomi - Qatar e-Government' },
    doc('passport', 'Passport valid at least 6 months.'), doc('contract', 'Approved employment contract.'), doc('degree', 'Attested degree.'), doc('police_certificate', 'Police certificate.'), doc('photo', 'Photos.'),
    { rule_type: 'processing', text: 'Medical test and biometrics at the Qatar Visa Center in Pakistan before travel.', source_url: 'https://www.qatarvisacenter.com', source_title: 'Qatar Visa Center' },
    { rule_type: 'eligibility', text: 'Health professionals require DHP (MOPH) licensing via DataFlow.', source_url: 'https://dhp.moph.gov.qa', source_title: 'Qatar DHP' }
  ]),
  ...S('TR', 'tr_student', 'Türkiye student visa and residence', 'study', [
    { rule_type: 'eligibility', text: 'Acceptance letter from a Turkish university (or Türkiye Bursları award); apply for a student visa at the consulate, then a student residence permit within the first weeks.', source_url: 'https://www.turkiyeburslari.gov.tr', source_title: 'Türkiye Scholarships' },
    doc('passport', 'Passport valid beyond the stay.'), doc('admission_letter', 'Acceptance / scholarship letter.'), doc('insurance', 'Health insurance for the residence permit.'), doc('bank_statement', 'Proof of means (unless fully scholarship-funded).'), doc('photo', 'Biometric photos.'),
    { rule_type: 'processing', text: 'Residence permit applications go through e-ikamet after arrival.', source_url: 'https://e-ikamet.goc.gov.tr', source_title: 'e-ikamet (Presidency of Migration Management)' }
  ]),
  ...S('MY', 'my_student_pass', 'Malaysia Student Pass', 'study', [
    { rule_type: 'eligibility', text: 'Offer letter from an EMGS-registered institution; the institution applies for the Visa Approval Letter through EMGS.', source_url: 'https://visa.educationmalaysia.gov.my', source_title: 'EMGS' },
    doc('passport', 'Passport valid at least 18 months.'), doc('admission_letter', 'Offer letter.'), doc('degree', 'Academic certificates and transcripts.'), doc('photo', 'Photo per EMGS spec.'), doc('bank_statement', 'Financial evidence if requested.'),
    { rule_type: 'processing', text: 'Pre-arrival medical screening and post-arrival medical within the first weeks.', source_url: 'https://visa.educationmalaysia.gov.my', source_title: 'EMGS' },
    { rule_type: 'work_rights', text: 'Part-time work limited to 20 hours a week during semester breaks, with approval.', source_url: 'https://visa.educationmalaysia.gov.my', source_title: 'EMGS' }
  ]),
  ...S('IE', 'ie_study', 'Ireland study visa (long stay D)', 'study', [
    { rule_type: 'eligibility', text: 'Letter of acceptance for a full-time course on the Interim List of Eligible Programmes / a recognised degree course.', source_url: 'https://www.irishimmigration.ie/coming-to-study-in-ireland/', source_title: 'Irish Immigration Service - Study' },
    { rule_type: 'financial', text: 'Evidence of fees paid and access to living funds at the level published by the Immigration Service.', source_url: 'https://www.irishimmigration.ie/coming-to-study-in-ireland/', source_title: 'Irish Immigration Service' },
    doc('passport', 'Passport valid 12 months beyond arrival.'), doc('admission_letter', 'Acceptance letter and fee receipt.'), doc('bank_statement', 'Financial evidence.'), doc('insurance', 'Private medical insurance.'), doc('language_test', 'English test as required by the course.'), doc('photo', 'Photos.'),
    { rule_type: 'pr_path', text: 'Third Level Graduate Scheme (up to 2 years) after graduation.', source_url: 'https://www.irishimmigration.ie/coming-to-study-in-ireland/', source_title: 'Irish Immigration Service' }
  ]),
  ...S('GB', 'uk_skilled_worker', 'UK Skilled Worker visa', 'work', [
    { rule_type: 'processing', text: 'EMPLOYER TRACK: the employer must hold a sponsor licence, assign a Certificate of Sponsorship (CoS) and pay the Immigration Skills Charge before the applicant can apply.', value: { track: 'employer', steps: ['Sponsor licence', 'Assign CoS', 'Pay Immigration Skills Charge'] }, source_url: 'https://www.gov.uk/uk-visa-sponsorship-employers', source_title: 'GOV.UK - Sponsorship for employers' },
    { rule_type: 'processing', text: 'APPLICANT TRACK: with the CoS reference, apply online, pay the fee and Immigration Health Surcharge, give biometrics, then await the decision.', value: { track: 'applicant', steps: ['Online application with CoS', 'Fee + IHS', 'Biometrics', 'Decision'] }, source_url: 'https://www.gov.uk/skilled-worker-visa/apply-from-outside-the-uk', source_title: 'GOV.UK - Apply from outside the UK' }
  ]),
  ...S('DE', 'de_skilled_worker', 'Germany skilled worker / EU Blue Card', 'work', [
    { rule_type: 'processing', text: 'EMPLOYER TRACK: the employer provides the contract and, where required, the Federal Employment Agency (BA) pre-approval / declaration of employment relationship; fast-track procedure is optional via the foreigners authority.', value: { track: 'employer', steps: ['Employment contract', 'BA approval / declaration', 'Optional fast-track (§81a)'] }, source_url: 'https://www.make-it-in-germany.com/en/visa-residence/procedure/fast-track-procedure', source_title: 'Make it in Germany - Fast-track procedure' },
    { rule_type: 'processing', text: 'APPLICANT TRACK: recognition/comparability of the degree, visa application at the German mission with the contract, then residence permit after arrival.', value: { track: 'applicant', steps: ['Degree recognition', 'Visa at the mission', 'Residence permit after arrival'] }, source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', source_title: 'Make it in Germany - EU Blue Card' }
  ]),
  ...S('CA', 'ca_work_permit', 'Canada employer-specific work permit (LMIA / IMP)', 'work', [
    { rule_type: 'eligibility', text: 'Most employer-specific permits need either an LMIA from ESDC or an LMIA-exempt offer of employment (International Mobility Program).', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/employer-specific.html', source_title: 'IRCC - Employer-specific work permit' },
    { rule_type: 'processing', text: 'EMPLOYER TRACK: apply for the LMIA (or submit the IMP offer and pay the compliance fee) and give the applicant the LMIA / offer number.', value: { track: 'employer', steps: ['LMIA application (or IMP offer)', 'Compliance fee', 'Provide number to applicant'] }, source_url: 'https://www.canada.ca/en/employment-social-development/services/foreign-workers.html', source_title: 'ESDC - Hire a temporary foreign worker' },
    { rule_type: 'processing', text: 'APPLICANT TRACK: apply online with the LMIA/offer number, biometrics, medical if required, then the permit at the port of entry.', value: { track: 'applicant', steps: ['Online application', 'Biometrics', 'Medical if required', 'Port of entry'] }, source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/apply.html', source_title: 'IRCC - Apply for a work permit' },
    doc('passport', 'Valid passport.'), doc('offer_letter', 'Job offer with LMIA / IMP number.'), doc('degree', 'Qualifications.'), doc('experience_letter', 'Experience letters.'), doc('police_certificate', 'Police certificate if requested.')
  ]),
  ...S('AU', 'au_482', 'Australia Skills in Demand visa (subclass 482)', 'work', [
    { rule_type: 'processing', text: 'EMPLOYER TRACK: the employer must be an approved sponsor and lodge a nomination for the position before the visa application.', value: { track: 'employer', steps: ['Sponsorship approval', 'Nomination'] }, source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand', source_title: 'Home Affairs - Skills in Demand' },
    { rule_type: 'processing', text: 'APPLICANT TRACK: apply online against the nomination with skills, English and health/character evidence.', value: { track: 'applicant', steps: ['Online application', 'Skills assessment where required', 'English', 'Health and character'] }, source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand', source_title: 'Home Affairs' },
    doc('passport', 'Valid passport.'), doc('offer_letter', 'Nomination / employment contract.'), doc('degree', 'Qualifications.'), doc('language_test', 'English test.'), doc('police_certificate', 'Police certificates.')
  ]),
  ...S('AE', 'ae_employment', 'UAE employment visa / work permit', 'work', [
    { rule_type: 'processing', text: 'EMPLOYER TRACK: the employer applies for the work permit and entry permit via MOHRE / free zone and sponsors the residence visa.', value: { track: 'employer', steps: ['Work permit (MOHRE/free zone)', 'Entry permit', 'Residence sponsorship'] }, source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-working-in-the-uae', source_title: 'u.ae' },
    { rule_type: 'processing', text: 'APPLICANT TRACK: attested documents, entry, medical fitness, Emirates ID, residence stamping.', value: { track: 'applicant', steps: ['Attested degree', 'Entry', 'Medical fitness', 'Emirates ID', 'Residence stamp'] }, source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id', source_title: 'u.ae' }
  ])
];
module.exports = { seed };
