// lib/visa_seed4.js — shortage lists and missing fee/dependants/PR rules for the four Band-A destinations and the Gulf work routes.
const S = (country_code, route_key, route_name, lane, rules) => rules.map(r => Object.assign({ country_code, route_key, route_name, lane }, r));
const seed = [
  ...S('GB', 'uk_skilled_worker', 'UK Skilled Worker visa', 'work', [
    { rule_type: 'shortage', text: 'Immigration Salary List (formerly Shortage Occupation List): occupations on it may be paid at a lower threshold. Check the current list.', value: { list: 'ISL' }, source_url: 'https://www.gov.uk/government/publications/skilled-worker-visa-immigration-salary-list', source_title: 'GOV.UK - Immigration Salary List' },
    { rule_type: 'fee', text: 'Application fee by visa length plus the Immigration Health Surcharge per year (figures recorded at verification).', source_url: 'https://www.gov.uk/skilled-worker-visa/how-much-it-costs', source_title: 'GOV.UK - Costs' },
    { rule_type: 'dependants', text: 'Partner and children may apply as dependants of a Skilled Worker (care workers excluded since March 2024).', source_url: 'https://www.gov.uk/skilled-worker-visa/your-partner-and-children', source_title: 'GOV.UK - Partner and children' }
  ]),
  ...S('GB', 'uk_student', 'UK Student visa', 'study', [{ rule_type: 'shortage', text: 'Graduate visa lets students stay 2 years (3 for PhD) to work in any role, a bridge to Skilled Worker sponsorship.', value: { list: 'graduate_route' }, source_url: 'https://www.gov.uk/graduate-visa', source_title: 'GOV.UK - Graduate visa' }]),
  ...S('AU', 'au_482', 'Australia Skills in Demand visa (subclass 482)', 'work', [
    { rule_type: 'shortage', text: 'Core Skills Occupation List (CSOL) governs eligibility for the Core Skills stream; the Specialist Skills stream is salary-based.', value: { list: 'CSOL' }, source_url: 'https://immi.homeaffairs.gov.au/visas/working-in-australia/skills-in-demand-visa', source_title: 'Home Affairs - Skills in Demand' },
    { rule_type: 'fee', text: 'Visa application charge per applicant plus employer nomination and SAF levy (figures at verification).', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/fees-and-charges', source_title: 'Home Affairs - Fees' },
    { rule_type: 'dependants', text: 'Partner and dependent children may be included; partners have work rights.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand', source_title: 'Home Affairs' },
    { rule_type: 'pr_path', text: 'Employer Nomination Scheme (186) after two years with the employer, or points-based skilled visas.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/employer-nomination-scheme-186', source_title: 'Home Affairs - 186' }
  ]),
  ...S('AU', 'au_500', 'Australia Student visa (subclass 500)', 'study', [{ rule_type: 'fee', text: 'Student visa application charge (raised in 2024) plus OSHC premiums.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/fees-and-charges', source_title: 'Home Affairs - Fees' }, { rule_type: 'dependants', text: 'Family members may be included as secondary applicants with their own conditions.', source_url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500', source_title: 'Home Affairs' }]),
  ...S('CA', 'ca_work_permit', 'Canada employer-specific work permit (LMIA / IMP)', 'work', [
    { rule_type: 'shortage', text: 'Express Entry category-based selection (healthcare, STEM, trades, transport, agriculture, French) and provincial nominee streams reflect current demand.', value: { list: 'EE_categories' }, source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/rounds-invitations/category-based-selection.html', source_title: 'IRCC - Category-based selection' },
    { rule_type: 'dependants', text: 'Spouse open work permit eligibility depends on the principal\'s occupation TEER level (narrowed in 2025).', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/spouse-open-work-permit.html', source_title: 'IRCC - Spouse open work permit' },
    { rule_type: 'pr_path', text: 'Express Entry (Canadian Experience Class) or provincial nomination after Canadian work experience.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', source_title: 'IRCC - Express Entry' },
    { rule_type: 'fee', text: 'Work permit fee and biometrics fee; employer compliance fee for IMP (figures at verification).', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html', source_title: 'IRCC' }
  ]),
  ...S('CA', 'ca_study_permit', 'Canada study permit', 'study', [{ rule_type: 'fee', text: 'Study permit fee plus biometrics (figures at verification).', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html', source_title: 'IRCC' }, { rule_type: 'dependants', text: 'Spousal open work permits for study-permit holders are limited to master\'s/doctoral and certain programmes since 2024.', source_url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/help-spouse-common-law-partner-work-canada.html', source_title: 'IRCC - Spouse of a student' }]),
  ...S('DE', 'de_skilled_worker', 'Germany skilled worker / EU Blue Card', 'work', [
    { rule_type: 'shortage', text: 'Bottleneck occupations (Engpassberufe) qualify for the lower Blue Card threshold; IT specialists may qualify on experience without a degree.', value: { list: 'Engpassberufe' }, source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', source_title: 'Make it in Germany' },
    { rule_type: 'fee', text: 'Visa fee at the mission and residence permit fee after arrival (figures at verification).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/procedure', source_title: 'Make it in Germany - Procedure' },
    { rule_type: 'dependants', text: 'Spouses of Blue Card holders join without a German language requirement and may work.', source_url: 'https://www.make-it-in-germany.com/en/living-in-germany/family-life/family-reunification', source_title: 'Make it in Germany - Family' }
  ]),
  ...S('DE', 'de_national_study', 'Germany national visa for study', 'study', [{ rule_type: 'fee', text: 'National visa fee and residence permit fee (figures at verification).', source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/study', source_title: 'Make it in Germany' }, { rule_type: 'dependants', text: 'Family reunification for students requires secured livelihood and housing.', source_url: 'https://www.make-it-in-germany.com/en/living-in-germany/family-life/family-reunification', source_title: 'Make it in Germany - Family' }]),
  ...S('SA', 'sa_work', 'Saudi Arabia work visa (Iqama)', 'work', [{ rule_type: 'processing', text: 'EMPLOYER TRACK: block visa and work visa authorisation from the Ministry of Human Resources, Qiwa contract, then visa authorisation on Enjaz.', value: { track: 'employer', steps: ['Block visa quota', 'Work visa authorisation', 'Qiwa contract', 'Enjaz visa authorisation'] }, source_url: 'https://www.mofa.gov.sa', source_title: 'MOFA' }, { rule_type: 'processing', text: 'APPLICANT TRACK: attested documents, Wafid medical, Enjaz application at the embassy or agent, Iqama after arrival.', value: { track: 'applicant', steps: ['Attestation', 'Wafid medical', 'Enjaz application', 'Iqama'] }, source_url: 'https://visa.mofa.gov.sa/', source_title: 'Saudi Visa Platform' }, { rule_type: 'pr_path', text: 'Premium Residency (permanent or renewable) by application; no route by years alone.', source_url: 'https://www.saprc.gov.sa/', source_title: 'Premium Residency Center' }, { rule_type: 'fee', text: 'Work visa fee, Iqama and levies (recorded at verification).', source_url: 'https://visa.mofa.gov.sa/', source_title: 'Saudi Visa Platform' }]),
  ...S('QA', 'qa_work', 'Qatar work visa', 'work', [{ rule_type: 'processing', text: 'EMPLOYER TRACK: Ministry of Labour contract approval, work visa issuance, then residence permit sponsorship.', value: { track: 'employer', steps: ['Contract approval (MOL)', 'Work visa', 'Residence permit (QID) sponsorship'] }, source_url: 'https://hukoomi.gov.qa', source_title: 'Hukoomi' }, { rule_type: 'processing', text: 'APPLICANT TRACK: attested documents, medical and biometrics at the Qatar Visa Center, entry, QID.', value: { track: 'applicant', steps: ['Attestation', 'QVC medical and biometrics', 'Entry', 'QID'] }, source_url: 'https://www.qatarvisacenter.com', source_title: 'Qatar Visa Center' }, { rule_type: 'dependants', text: 'Family residence for eligible salary levels.', source_url: 'https://hukoomi.gov.qa', source_title: 'Hukoomi' }, { rule_type: 'pr_path', text: 'Permanent residency by application under the 2018 law, limited numbers.', source_url: 'https://hukoomi.gov.qa', source_title: 'Hukoomi' }, { rule_type: 'fee', text: 'Visa and residence fees (recorded at verification).', source_url: 'https://hukoomi.gov.qa', source_title: 'Hukoomi' }]),
  ...S('QA', 'qa_licence_dentist', 'Licence: dentist in QA', 'work', [{ rule_type: 'licence', text: 'Dentists: DHP (MOPH) licensing via DataFlow and Prometric.', value: { profession: 'dentist', isco: '2261' }, source_url: 'https://dhp.moph.gov.qa', source_title: 'Qatar DHP' }]),
  ...S('QA', 'qa_licence_physiotherapist', 'Licence: physiotherapist in QA', 'work', [{ rule_type: 'licence', text: 'Physiotherapists: DHP (MOPH) licensing via DataFlow.', value: { profession: 'physiotherapist', isco: '2264' }, source_url: 'https://dhp.moph.gov.qa', source_title: 'Qatar DHP' }]),
  ...S('QA', 'qa_licence_nurse', 'Licence: nurse in QA', 'work', [{ rule_type: 'licence', text: 'Nurses: DHP (MOPH) licensing via DataFlow and Prometric.', value: { profession: 'nurse', isco: '2221' }, source_url: 'https://dhp.moph.gov.qa', source_title: 'Qatar DHP' }]),
  ...S('AE', 'ae_employment', 'UAE employment visa / work permit', 'work', [{ rule_type: 'fee', text: 'Work permit, entry permit, medical, Emirates ID and residence fees (recorded at verification).', source_url: 'https://u.ae/en/information-and-services/visa-and-emirates-id', source_title: 'u.ae' }]),
  ...S('IE', 'ie_study', 'Ireland study visa (long stay D)', 'study', [{ rule_type: 'fee', text: 'Visa fee and IRP registration fee (recorded at verification).', source_url: 'https://www.irishimmigration.ie/', source_title: 'Irish Immigration Service' }, { rule_type: 'dependants', text: 'Dependants generally cannot accompany degree students (research and certain postgraduate cases differ).', source_url: 'https://www.irishimmigration.ie/coming-to-study-in-ireland/', source_title: 'Irish Immigration Service' }, { rule_type: 'work_rights', text: 'Students on the ILEP list may work 20 hours a week during term and 40 in holidays.', source_url: 'https://www.irishimmigration.ie/coming-to-study-in-ireland/', source_title: 'Irish Immigration Service' }]),
  ...S('TR', 'tr_student', 'Türkiye student visa and residence', 'study', [{ rule_type: 'work_rights', text: 'Postgraduate students may work with a permit; undergraduates after the first year with limits.', source_url: 'https://www.csgb.gov.tr/', source_title: 'Ministry of Labour' }, { rule_type: 'pr_path', text: 'Work permit with an employer after graduation; long-term residence after 8 years.', source_url: 'https://www.goc.gov.tr/', source_title: 'Presidency of Migration Management' }, { rule_type: 'fee', text: 'Visa and residence permit fees (recorded at verification).', source_url: 'https://www.evisa.gov.tr/en/', source_title: 'Türkiye e-Visa' }, { rule_type: 'dependants', text: 'Family residence permits for dependants of residence permit holders.', source_url: 'https://www.goc.gov.tr/', source_title: 'Presidency of Migration Management' }]),
  ...S('MY', 'my_student_pass', 'Malaysia Student Pass', 'study', [{ rule_type: 'pr_path', text: 'Employment Pass with an employer after graduation; no general permanent residence.', source_url: 'https://esd.imi.gov.my/', source_title: 'ESD' }, { rule_type: 'fee', text: 'EMGS processing, pass and insurance fees (recorded at verification).', source_url: 'https://visa.educationmalaysia.gov.my', source_title: 'EMGS' }, { rule_type: 'dependants', text: 'Dependant passes for postgraduate students in some cases.', source_url: 'https://visa.educationmalaysia.gov.my', source_title: 'EMGS' }])
];
module.exports = { seed };
