// tools/build-guides.js — generates public/help.html (applicant guide) and public/crm-guide.html (FF-CRM staff guide) from docs/guides.json.
// Runs at build; edit the JSON when a feature ships so both guides stay current in every session.
const fs = require('fs'); const path = require('path');
const G = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'docs', 'guides.json'), 'utf8'));
const esc = t => String(t || '').replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
const shell = (title, body, sub) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title>
<link rel="icon" href="/favicon.ico" sizes="any"><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>:root{--ink:#0B1B3A;--soft:#3B4B6B;--muted:#5C6B8A;--line:#E3E9F6;--accent:#1683FF;--gold:#C9A227}*{box-sizing:border-box}body{margin:0;background:#F7F9FF;color:var(--ink);font:16px/1.6 Inter,system-ui,sans-serif}a{color:var(--accent);text-decoration:none}h1,h2{font-family:Fraunces,serif;letter-spacing:-.02em;margin:0}header{background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:5}.bar{max-width:1080px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;padding:12px 20px}.brand{display:inline-flex;align-items:center;gap:10px;color:var(--ink);font:800 22px Fraunces,serif}.brand img{width:36px;height:36px}.brand b{color:var(--accent)}nav a{margin-left:18px;color:var(--soft);font-size:14px}
.wrap{max-width:1080px;margin:0 auto;padding:36px 20px 80px;display:grid;grid-template-columns:240px 1fr;gap:30px}.toc{position:sticky;top:76px;align-self:start;background:#fff;border:1px solid var(--line);border-radius:14px;padding:14px}.toc a{display:block;padding:6px 0;font-size:13.5px;color:var(--soft);border-top:1px solid #EEF2FA}.toc a:first-child{border:0}
h1{font-size:40px;line-height:1.05;margin-bottom:6px}.lead{color:var(--soft);margin:0 0 24px;font-size:17px}section{background:#fff;border:1px solid var(--line);border-top:3px solid var(--gold);border-radius:16px;padding:20px 22px;margin-bottom:14px}section h2{font-size:20px;margin-bottom:10px}section ol{margin:0;padding-left:20px}section li{margin:6px 0;color:var(--soft)}section li b{color:var(--ink)}
.faq{background:#fff;border:1px solid var(--line);border-radius:16px;padding:8px 22px}.faq details{border-top:1px solid #EEF2FA;padding:10px 0}.faq details:first-child{border:0}.faq summary{font-weight:700;cursor:pointer;color:var(--ink)}.faq p{color:var(--soft);margin:6px 0 0}
.stamp{color:var(--muted);font-size:12px;margin-top:20px}@media (max-width:820px){.wrap{grid-template-columns:1fr}.toc{position:static}}</style></head>
<body><header><div class="bar"><a class="brand" href="/" aria-label="Go to ForiForeign Home"><img src="/brand/ff-mark-64.png" alt="" width="36" height="36"><span>Fori<b>Foreign</b></span></a><nav><a href="/help.html">Applicant guide</a><a href="/crm-guide.html">FF-CRM guide</a><a href="/app#signin">Sign in</a></nav></div></header>
<main class="wrap">${body}</main></body></html>`;
function render(g, kind) { const toc = g.sections.map((s, i) => `<a href="#s${i + 1}">${esc(s.h)}</a>`).join('') + '<a href="#faq">Questions</a>'; const secs = g.sections.map((s, i) => `<section id="s${i + 1}"><h2>${esc(s.h)}</h2><ol>${s.items.map(t => { const m = t.match(/^([^.:]{3,60}[.:])\s(.*)$/); return '<li>' + (m ? '<b>' + esc(m[1]) + '</b> ' + esc(m[2]) : esc(t)) + '</li>'; }).join('')}</ol></section>`).join(''); const faq = `<div class="faq" id="faq"><h2 style="font-size:20px;padding:10px 0">Questions</h2>${g.faqs.map(([q, a]) => `<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div>`; const ld = kind === 'applicant' ? `<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: g.faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }).replace(/</g, '\\u003c')}</script>` : ''; const body = ld + `<aside class="toc">${toc}</aside><div><h1>${esc(g.title)}</h1><p class="lead">${esc(g.subtitle)}</p>${secs}${faq}<div class="stamp">Guide version ${esc(G.version)} · updated with every release · questions: admin@foriforeign.com</div></div>`; return shell(g.title, body, g.subtitle); }
fs.writeFileSync(path.join(__dirname, '..', 'public', 'help.html'), render(G.applicant, 'applicant'));
fs.writeFileSync(path.join(__dirname, '..', 'public', 'crm-guide.html'), render(G.crm, 'crm'));
fs.writeFileSync(path.join(__dirname, '..', 'public', 'help-data.json'), JSON.stringify({ version: G.version, crm: { faqs: G.crm.faqs }, applicant: { faqs: G.applicant.faqs } }));
console.log('guides built', G.version);
