// Day 26 · runtime QA: render Profile and Workspace in a headless browser with stubbed APIs and catch exceptions.
const {JSDOM}=require('jsdom');const fs=require('fs');let html=fs.readFileSync('/home/claude/repo/public/index.html','utf8');
const cfg={payment:{easypaisa_number:'03455216903'},packages:{tiers:[{name:'Basic',credits:2,view:5,usd:25,promo_usd:19}]},agency:{tiers:[{key:'starter',name:'Starter',usd_month:59,cases_month:10,seats:3,sub_agents:0}]},fair_use:{},gateway:{card:false},fx:{currency:'PKR',rate:280}};
const pre=`<script>window.fetch=async(u)=>({ok:true,json:async()=>String(u).includes('site-config')?{config:${JSON.stringify(cfg)}}:String(u).includes('/api/i18n')?{langs:{en:{name:'English',dir:'ltr'},ur:{name:'Urdu',dir:'rtl'}},origins:{PK:{name:'Pakistan',currency:'PKR'},IN:{name:'India',currency:'INR'}},strings:{nav_dashboard:{en:'Dashboard',ur:'x'}}}:String(u).includes('/api/config')?{supabaseUrl:''}:{build:'x'}});</script>`;
html=html.replace(/<script src="[^"]*"><\/script>/,pre);
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://foriforeign.com/'});const w=dom.window;const errs=[];w.addEventListener('error',e=>errs.push(String(e.message)));


const views=['vHome','vExplore','vApps','vMail','vProfile','vBuy','vWorkspace','vAdmin','vBrowse'];
(async()=>{await new Promise(r=>setTimeout(r,1500));const report={};for(const v of views){try{w.document.body.classList.add('light','authed');w.eval("TAB='"+v.replace(/^v/,'').toLowerCase()+"'");await w.eval(v+'()');await new Promise(r=>setTimeout(r,500));const view=w.document.getElementById('view');const btns=[...view.querySelectorAll('button')];const noLabel=btns.filter(b=>!b.textContent.trim()&&!b.getAttribute('aria-label')).length;const noHandler=btns.filter(b=>!b.getAttribute('onclick')&&b.type!=='submit'&&!b.onclick).length;const unresolved=(view.innerHTML.match(/\$\{/g)||[]).length;const anchors=[...view.querySelectorAll('a[onclick]:not([href])')];const anchorsNoTab=anchors.filter(a=>!a.getAttribute('tabindex')).length;const inputs=[...view.querySelectorAll('input:not([type=hidden]):not([type=file]),select,textarea')];const unlabeledEls=inputs.filter(i=>!i.getAttribute('aria-label')&&!i.getAttribute('placeholder'));const unlabeled=unlabeledEls.length;if(unlabeled)console.log(v,'UNLABELED:',JSON.stringify(unlabeledEls.map(i=>(i.outerHTML||'').slice(0,90))));const labels=btns.map(b=>b.textContent.trim()).filter(Boolean);const dupPrimary=labels.filter((l,i,a)=>/^(Continue|Find my matches|Complete Profile|Upload CV)$/.test(l)&&a.indexOf(l)!==i).length;report[v]={buttons:btns.length,noLabel,noHandler,unresolved,anchors:anchors.length,anchorsNoTab,inputs:inputs.length,unlabeled,dupPrimary,chars:view.innerHTML.length}}catch(e){report[v]={error:String(e.message).slice(0,120)}}}console.log(JSON.stringify(report));process.exit(0)})();
